// Code generated by tygo. DO NOT EDIT.
// GENERATED by tygo from server/internal/protocol — do not edit.
// Regenerate with `make protocol`.

//////////
// source: protocol.go
/*
Package protocol defines the WebSocket message types. These Go structs are
the single source of truth; `make protocol` generates the TypeScript types
via tygo (see WATTROOM.md decisions: WS protocol).
*/

/**
 * RiderMetrics is one rider's live sample, sent client -> server at ~1 Hz.
 */
export interface RiderMetrics {
  watts: number /* int */;
  hr?: number /* int */;
  cadence?: number /* int */;
  seq: number /* int */; // monotonic per ride, for reconnect dedup
}
/**
 * Control is a coach/owner command over the shared session (SPEC roles matrix:
 * pick workout, start countdown, pause/end). The server enforces the role.
 */
export interface Control {
  action: string; // "pick" | "start" | "pause" | "resume" | "end"
  /**
   * Workout definition, opaque to the server: the docs/SPEC.md JSON as a
   * string. The server owns the clock, the clients own the targets.
   */
  workoutName?: string;
  workoutJson?: string;
  /**
   * Total length in seconds, so the server can end the session on time
   * without parsing the workout.
   */
  totalSeconds?: number /* int */;
}
/**
 * Backfill is a reconnect's replay: samples the client buffered while the
 * socket was down (WATTROOM.md crash safety). The server dedupes by Seq, so
 * resending is always safe and never double-counts.
 */
export interface Backfill {
  samples: RiderMetrics[];
}
/**
 * JukeboxCommand is any member's jukebox action — the matrix defaults
 * play/pause/skip to members, and adding is everyone's.
 */
export interface JukeboxCommand {
  action: string; // "add" | "remove" | "play" | "pause" | "skip" | "ended"
  videoId?: string;
  title?: string;
}
/**
 * ClientMessage is the envelope for everything a client sends.
 */
export interface ClientMessage {
  metrics?: RiderMetrics;
  control?: Control;
  backfill?: Backfill;
  jukebox?: JukeboxCommand;
}
/**
 * Rider is presence: who is in the room right now, with what the dashboard
 * needs to render them. FTP crosses the wire so every screen can show %FTP —
 * room-scoped by design, the same visibility WATTROOM.md grants live watts.
 */
export interface Rider {
  id: string;
  name: string;
  role: string;
  ftpWatts: number /* int */;
  /**
   * For w/kg on room screens — room-scoped like FTP, and for the same reason:
   * every contest in docs/SPEC.md is scored on it.
   */
  weightKg: number /* int */;
}
/**
 * SessionState is the shared timeline, server-owned. Late joiners need no
 * catch-up protocol: every tick carries the whole truth.
 */
export interface SessionState {
  phase: string; // "idle" | "countdown" | "running" | "paused" | "done"
  /**
   * Seconds into the workout timeline. Advances only while running.
   */
  elapsed: number /* int */;
  /**
   * Seconds until the timeline starts, while in countdown.
   */
  countdownRemaining?: number /* int */;
  workoutName?: string;
  workoutJson?: string;
  totalSeconds?: number /* int */;
}
export interface JukeboxEntry {
  videoId: string;
  title: string;
  addedBy: string;
}
/**
 * JukeboxState is the server's truth about what plays where. Clients chase the
 * anchor: position = PositionSec, plus wall time since AnchorMs while playing.
 * The audio itself is local per rider — their iframe, their volume — and never
 * enters the voice path (SPEC room audio defaults).
 */
export interface JukeboxState {
  queue: JukeboxEntry[];
  current?: JukeboxEntry;
  playing: boolean;
  positionSec: number /* float64 */;
  anchorMs: number /* int64 */;
}
/**
 * ServerTick is the coalesced 1 Hz room broadcast: every rider's latest
 * sample, the roster, and the shared session state.
 */
export interface ServerTick {
  at: number /* int64 */; // unix millis
  state: SessionState;
  jukebox: JukeboxState;
  roster: Rider[];
  riders: { [key: string]: RiderMetrics};
}
/**
 * Error tells a client why its connection or command was refused.
 */
export interface Error {
  code: string;
  message: string;
}
/**
 * ServerMessage is the envelope for everything the server sends.
 */
export interface ServerMessage {
  tick?: ServerTick;
  error?: Error;
}
