// Code generated by tygo. DO NOT EDIT.
// GENERATED by tygo from server/internal/protocol — do not edit.
// Regenerate with `make protocol`.

//////////
// source: limits.go

/**
 * From docs/SPEC.md: the rider's two numbers (ADR-0048) and the anchor the HR
 * zones derive from (ADR-0014). Both sides read these; neither retypes them.
 */
export const MinFtpWatts = 50;
/**
 * From docs/SPEC.md: the rider's two numbers (ADR-0048) and the anchor the HR
 * zones derive from (ADR-0014). Both sides read these; neither retypes them.
 */
export const MaxFtpWatts = 600;
/**
 * From docs/SPEC.md: the rider's two numbers (ADR-0048) and the anchor the HR
 * zones derive from (ADR-0014). Both sides read these; neither retypes them.
 */
export const MinWeightKg = 30;
/**
 * From docs/SPEC.md: the rider's two numbers (ADR-0048) and the anchor the HR
 * zones derive from (ADR-0014). Both sides read these; neither retypes them.
 */
export const MaxWeightKg = 200;
/**
 * From docs/SPEC.md: the rider's two numbers (ADR-0048) and the anchor the HR
 * zones derive from (ADR-0014). Both sides read these; neither retypes them.
 */
export const MinLthrBpm = 100;
/**
 * From docs/SPEC.md: the rider's two numbers (ADR-0048) and the anchor the HR
 * zones derive from (ADR-0014). Both sides read these; neither retypes them.
 */
export const MaxLthrBpm = 210;
/**
 * A chat line, in CHARACTERS: the server counts runes because counting
 * bytes cut non-Latin scripts off at half the advertised limit (#219),
 * and the box that types it has to cap at the same number.
 */
export const MaxMessageChars = 500;
/**
 * The two codes a rider is handed, and the one thing that tells them
 * apart at a glance (#1236): a friend's is eight characters, a crew's
 * six. Both sides check the length to say WHICH door a pasted code is
 * for, so both sides have to agree on it.
 */
export const FriendCodeLen = 8;
/**
 * From docs/SPEC.md: the rider's two numbers (ADR-0048) and the anchor the HR
 * zones derive from (ADR-0014). Both sides read these; neither retypes them.
 */
export const CrewCodeLen = 6;
/**
 * What the rider says about a finished ride (#2328, docs/SPEC.md "How a
 * ride felt"): the Borg CR10 session rating, and the sentence beside it.
 * 0 is CR10's "rest" and no saved ride is one, so the floor is 1. The
 * picker draws exactly this many buttons and the server refuses anything
 * else, which is only true while both read the same pair.
 */
export const MinRPE = 1;
/**
 * From docs/SPEC.md: the rider's two numbers (ADR-0048) and the anchor the HR
 * zones derive from (ADR-0014). Both sides read these; neither retypes them.
 */
export const MaxRPE = 10;
/**
 * A ride note, in CHARACTERS — runes, MaxMessageChars' rule. Its own
 * constant rather than a second name for that one: the two happen to
 * agree on 500 today, and a chat line's limit moving is no reason for a
 * note's to follow.
 */
export const MaxRideNoteChars = 500;
/**
 * A crew's pin board (ADR-0056, docs/SPEC.md "Pins"). Both sides read
 * these: the editor caps its boxes at the first two, the server refuses
 * anything longer, and the count is what the "Pin something" button
 * disables itself on rather than letting a rider write a pin the POST
 * will then refuse.
 * The two lengths are in CHARACTERS — runes, MaxMessageChars' rule.
 */
export const MaxPinTitleChars = 40;
/**
 * From docs/SPEC.md: the rider's two numbers (ADR-0048) and the anchor the HR
 * zones derive from (ADR-0014). Both sides read these; neither retypes them.
 */
export const MaxPinBodyChars = 1000;
/**
 * Twenty is a board; two hundred is a wiki. The ceiling is what keeps a
 * pin worth reading — a crew that needs more of them needs a document,
 * and this feature is deliberately not one.
 */
export const MaxCrewPins = 20;
/**
 * A crew's reaction palette (#223, docs/SPEC.md): the picker stops at it
 * and the server refuses past it.
 */
export const MaxCheers = 8;
/**
 * A crew's own emoji (#2643, docs/SPEC.md): how many a crew holds and how
 * big one picture may be. The upload refuses past both, and the crew's
 * settings disable "Add emoji" at the count rather than offering an
 * upload the POST will refuse. A name is MinEmojiNameChars to
 * MaxEmojiNameChars of a–z, 0–9 and _ — ASCII, so bytes and characters
 * agree — and the crew_emoji CHECK holds the same pair as a literal.
 */
export const MaxCrewEmoji = 50;
/**
 * From docs/SPEC.md: the rider's two numbers (ADR-0048) and the anchor the HR
 * zones derive from (ADR-0014). Both sides read these; neither retypes them.
 */
export const MaxEmojiBytes = 256 << 10;
/**
 * From docs/SPEC.md: the rider's two numbers (ADR-0048) and the anchor the HR
 * zones derive from (ADR-0014). Both sides read these; neither retypes them.
 */
export const MinEmojiNameChars = 2;
/**
 * From docs/SPEC.md: the rider's two numbers (ADR-0048) and the anchor the HR
 * zones derive from (ADR-0014). Both sides read these; neither retypes them.
 */
export const MaxEmojiNameChars = 32;
/**
 * A rider's status line (ADR-0060, docs/SPEC.md "Personal status"), in
 * CHARACTERS — MaxMessageChars' rule.
 */
export const MaxStatusChars = 100;
/**
 * A crew's name (docs/SPEC.md "Names"), in CHARACTERS — MaxMessageChars'
 * rule.
 */
export const MaxCrewNameChars = 60;
/**
 * How many crews a rider founds (docs/SPEC.md "Caps", default — tune in
 * alpha), counted over the crews they founded and still own. "Start a
 * crew" disables at it rather than offering a POST that is refused.
 */
export const MaxFoundedCrews = 3;
/**
 * A channel's name (ADR-0058, docs/SPEC.md "Names"), in CHARACTERS —
 * MaxMessageChars' rule — and the bound the channels table's CHECK holds.
 */
export const MaxChannelNameChars = 60;
/**
 * How many text channels a crew holds (docs/SPEC.md "Caps", default —
 * tune in alpha). The settings page disables "New channel" at it rather
 * than offering a create the POST will refuse.
 */
export const MaxCrewTextChannels = 20;
/**
 * How many voice channels a crew holds — MaxCrewTextChannels' rule.
 */
export const MaxCrewVoiceChannels = 10;
/**
 * The tolerance band a second is scored in: within ±5 % of target, floor
 * ±10 W (#2159). The floor is what keeps an easy block scoreable — at
 * 60 W, 5 % is 3 W, which is inside a trainer's own error.
 */
export const TargetBandFraction = 0.05;
/**
 * From docs/SPEC.md: the rider's two numbers (ADR-0048) and the anchor the HR
 * zones derive from (ADR-0014). Both sides read these; neither retypes them.
 */
export const TargetBandFloorWatts = 10;
/**
 * A temporary message's timer (#2644, docs/SPEC.md "Text channel chat"),
 * in seconds: the three a sender picks from. The composer offers exactly
 * these and the server refuses any other, so both read them from here.
 */
export const TemporaryHour = 60 * 60;
/**
 * From docs/SPEC.md: the rider's two numbers (ADR-0048) and the anchor the HR
 * zones derive from (ADR-0014). Both sides read these; neither retypes them.
 */
export const TemporaryDay = 24 * TemporaryHour;
/**
 * From docs/SPEC.md: the rider's two numbers (ADR-0048) and the anchor the HR
 * zones derive from (ADR-0014). Both sides read these; neither retypes them.
 */
export const TemporaryWeek = 7 * TemporaryDay;

//////////
// source: protocol.go
/*
Package protocol defines the WebSocket message types. These Go structs are
the single source of truth; `make protocol` generates the TypeScript types
via tygo (see WATTROOM.md decisions: WS protocol).
*/

/**
 * RiderMetrics is one rider's live sample, sent client -> server at ~1 Hz.
 */
export interface RiderMetrics {
  watts: number /* int */;
  hr?: number /* int */;
  cadence?: number /* int */;
  seq: number /* int */; // monotonic per ride, for reconnect dedup
  /**
   * The rider's personal trim on their own targets at this second, 0.8–1.2
   * (docs/SPEC.md). A score answers "did you ride the plan you were on?",
   * and this is what the plan was — so the second is scored against the
   * biased target, not the prescribed one (#795). It rides every sample
   * because bias moves mid-ride, and it is stored with them, which is what
   * lets the saved score agree with the live one.
   * Zero means "not sent": every sample recorded before this existed, and
   * any client that does not send it, scores at 1.0.
   */
  bias?: number /* float64 */;
  /**
   * The WORKOUT second this sample was ridden at (#1733). A solo ride's
   * record counts wall seconds — the ride clock stops while auto-paused,
   * and skip and extend make it jump — so the array index stops being the
   * workout second at the first pause, and every sample after it would be
   * scored against the wrong block. Absent (0 on every sample) is a ride
   * that sends none: a session ride, where the hub's clock IS the workout
   * clock, or one recorded before this existed; those score by index.
   */
  clock?: number /* int */;
  /**
   * The rider's own guard had the trainer off the target this second
   * (#1796): auto-pause, the resume countdown, the spiral release. The
   * live meter on the client never scores such a second; the saved ride
   * and the session's live score used to, against the full target — a
   * spiral trip was ten pedalling seconds against no resistance, out of
   * band by construction. Absent means scored.
   */
  released?: boolean;
}
/**
 * SprintScore is one rider's place on the mini-podium.
 */
export interface SprintScore {
  riderId: string;
  name: string;
  wkg: number /* float64 */;
  watts: number /* int */;
  /**
   * Ramp modes (#1593): the rounds the rider survived — the number the
   * podium shows, where Wkg is only a placing score.
   */
  rounds?: number /* int */;
}
/**
 * SprintState rides the tick while a sprint moment is armed, live, or just
 * scored. Times are server-clock millis, the same clock as ServerTick.At —
 * clients render the klaxon countdown and the window from these anchors.
 */
export interface SprintState {
  startsAtMs: number /* int64 */;
  endsAtMs: number /* int64 */;
  /**
   * Filled once the window closes; podium order.
   */
  results?: SprintScore[];
}
/**
 * GameRider is one rider's standing inside a game mode.
 */
export interface GameRider {
  eliminated?: boolean;
  lives?: number /* int */;
  score?: number /* float64 */;
  onFront?: boolean;
  /**
   * The rider's personal target as a fraction of their FTP; 0 = ride free.
   */
  targetPct?: number /* float64 */;
}
/**
 * GameState is a running game mode on the tick (#31). One generic shape for
 * all seven modes: the client renders labels per mode, the server owns every
 * rule. Riders execute their own %FTP targets, so mixed groups stay fair.
 */
export interface GameState {
  mode: string;
  phase: string; // "running" | "done"
  round?: number /* int */;
  /**
   * The shared line as a fraction of FTP (ramp modes), the called zone
   * (lava), or the hole target pct (golf) — mode-dependent, one at a time.
   */
  linePct?: number /* float64 */;
  calledZone?: number /* int */;
  roundEndsAtMs?: number /* int64 */;
  /**
   * Sprint Roulette's window opens here (#1578): the length is random, so
   * the client cannot derive the 3-2-1 from the end alone.
   */
  roundStartsAtMs?: number /* int64 */;
  meterHidden?: boolean;
  teamDistance?: number /* float64 */;
  riders: { [key: string]: GameRider};
  podium?: SprintScore[];
}
/**
 * Control is a coach/owner command over the shared session (SPEC roles matrix:
 * pick workout, start countdown, pause/end). The server enforces the role.
 */
export interface Control {
  action: string; // "pick" | "start" | "pause" | "resume" | "end" | "handoff" | "game" | "game-end" | "sprint" | "join" | "leave"
  /**
   * Workout definition, opaque to the server: the docs/SPEC.md JSON as a
   * string. The server owns the clock, the clients own the targets.
   */
  workoutName?: string;
  workoutJson?: string;
  /**
   * Total length in seconds, so the server can end the session on time
   * without parsing the workout.
   */
  totalSeconds?: number /* int */;
  /**
   * For action "game": which mode to start.
   */
  gameMode?: string;
  /**
   * For action "handoff": the rider id the session's coach hands it to
   * (#2438) — someone in the voice channel.
   */
  rider?: string;
}
/**
 * Backfill is a reconnect's replay: samples the client buffered while the
 * socket was down (WATTROOM.md crash safety). The server dedupes by Seq, so
 * resending is always safe and never double-counts.
 */
export interface Backfill {
  samples: RiderMetrics[];
}
/**
 * JukeboxCommand is any member's jukebox action — the matrix defaults
 * play/pause/skip to members, and adding is everyone's.
 */
export interface JukeboxCommand {
  action: string; // "add" | "remove" | "vote" | "move" | "play" | "pause" | "skip" | "back" | "skipPlaylist" | "seek" | "ended" | "restore"
  videoId?: string;
  title?: string;
  /**
   * For "add": queue a whole YouTube playlist as one entry (#615). The
   * client resolves the tracks — the server still knows nothing about
   * YouTube, it just holds the list the paste produced.
   */
  playlistId?: string;
  playlistTitle?: string;
  tracks?: JukeboxTrack[];
  /**
   * For "add": a track from the pool rather than a YouTube video (#267).
   * Mutually exclusive with VideoID; Title and Artist ride along for
   * display, because the deck carries no metadata of its own.
   */
  trackId?: string;
  artist?: string;
  /**
   * The track's tempo, when its tags say (#1431): read off the library
   * row by whoever adds it, shown on the queue row, and matched against
   * the block's cadence while a session runs. 0 = untagged.
   */
  bpm?: number /* int */;
  /**
   * For "add" of a library track: its length as the server measured it at
   * upload (#1509), so the deck can draw a seek bar before — or without —
   * any client's <audio> reporting one. 0 = unknown.
   */
  durationMs?: number /* int */;
  /**
   * For "remove" | "vote" | "move": which queue entry (#286). Video ids
   * are not unique — the same track queued twice is two entries, and
   * addressing by video used to hit the wrong one.
   */
  entryId?: string;
  /**
   * For "move": the entry's new index in the queue, clamped to it.
   */
  index?: number /* int */;
  /**
   * For "seek": the new shared playhead. For "add": start the entry here
   * (a pasted ?t= timestamp) — 0 means the beginning, like any URL.
   */
  positionSec?: number /* float64 */;
  /**
   * For "ended": the anchor the client was playing against. Every client
   * (and tab) reports the end — the epoch match makes N echoes advance
   * the queue exactly once even when the same video is queued twice.
   */
  anchorMs?: number /* int64 */;
}
/**
 * ChatLine is one chat message as the HTTP chat answers it (ADR-0010
 * amended, #201; off the tick since #2437). Warm-up and phone talk;
 * mid-effort stays the cheers' job.
 */
export interface ChatLine {
  /**
   * Persisted identity (ADR-0010 amended, #201) — what reactions attach to.
   * Empty when the server runs without a database.
   */
  id?: string;
  from: string; // filled by the server, like cheers
  /**
   * The author's rider id (#219): display names are not unique, and the
   * client's own-message suppression must not mute a namesake.
   */
  fromId?: string;
  text: string;
  /**
   * A pasted image (#279): id of a channel-scoped blob the client uploaded
   * via POST /api/channels/{id}/chat/images before sending; rendered from
   * the matching GET. A line may be image-only (empty text).
   */
  imageId?: string;
  at: number /* int64 */; // server millis, for ordering only
  /**
   * When the author last rewrote this line (#865); 0 for a line as sent.
   * The client renders "edited" off this, so it is a fact about the line
   * and not a separate event to remember.
   */
  editedAt?: number /* int64 */;
  /**
   * When a temporary line runs out (#2644), server millis; 0 for a line
   * that stays. Readers drop it by their own clock at that moment — the
   * server stops serving it then and sweeps it within the minute.
   */
  expiresAt?: number /* int64 */;
}
/**
 * ChatEdit is one line rewritten by its author (#865): the new text lands
 * on the line already in the log, rather than arriving as a second message
 * that would push the conversation along.
 */
export interface ChatEdit {
  messageId: string;
  text: string;
  editedAt: number /* int64 */;
}
/**
 * ChatReactionCount is a changed total, as the toggle answers it — plus who
 * changed it and which way (#219), so the actor reconciles their "did I
 * react" highlight from the server instead of trusting the click.
 */
export interface ChatReactionCount {
  messageId: string;
  emoji: string;
  count: number /* int */;
  by?: string; // rider id of the toggler
  added: boolean;
}
/**
 * ChannelEvent is something that happened in a voice channel rather than
 * something a rider said (#321): the jukebox changing under everyone is half
 * of what happens there, and thirty seconds later "who put this on?" has no
 * other answer. Structured, not a sentence — the client owns the wording, so
 * the lounge and the dock name a track identically.
 * Ephemeral by design (ADR-0022): it rides the tick like cheers and is never
 * written to the chat table. A month of "now playing" in the backlog is noise.
 */
export interface ChannelEvent {
  /**
   * Unique within the voice channel, and stable across re-broadcasts: a
   * growing burst re-sends the SAME id with a higher Count, and clients
   * replace the line in place.
   */
  id: string;
  kind: string; // "jukebox" | "session" | "presence"
  /**
   * jukebox: "queued" | "removed" | "skipped" | "playing" | "restored"
   * session: "planned" | "moved" | "cancelled" | "started" | "ended" |
   *          "won" | "gameEnded"
   * presence: "joined" | "left" | "away" | "back"
   */
  verb: string;
  /**
   * Who did it. Empty when nobody did — the deck advancing on its own, or
   * a session the clock started.
   */
  actor?: string;
  /**
   * The title the dock shows, so both surfaces name the same track. Empty
   * on a coalesced burst, which has no single title left to show.
   */
  track?: string;
  /**
   * The workout a session line is about.
   */
  subject?: string;
  /**
   * When that session is planned for, server millis. 0 on a line with no
   * time of its own ("started", "ended").
   */
  when?: number /* int64 */;
  /**
   * For "playing": who put this track in the queue.
   */
  queuedBy?: string;
  /**
   * How many things this one line covers — 1 normally, more when a burst
   * coalesced ("queued 8 tracks", "Ana and 2 others joined"). Eight lines
   * would push the actual conversation off the screen. On "gameEnded" it
   * is instead the round the game reached, which for a collective ramp is
   * the score the whole session rode for.
   */
  count: number /* int */;
  at: number /* int64 */; // server millis, for ordering only
}
/**
 * Cheer is a voice channel's reaction layer (#74) — and the spectator's one
 * verb.
 */
export interface Cheer {
  emoji: string;
  /**
   * Sender name, filled by the server: cheering is presence.
   */
  from?: string;
}
/**
 * Board is one rider firing a pad on their soundboard (#877, ADR-0033). The
 * client sends only ClipID; the hub fills the sender from authenticated
 * presence, and every listener fetches the clip and mixes it locally, on their
 * own board fader.
 * The hub deliberately does not check that the clip exists or belongs to the
 * sender. Fetching is what authorizes (board.canHear), so a forged id costs a
 * 404 on every machine and nothing else — and the check it would take is a
 * database round trip on the voice channel's tick path.
 * An empty ClipID is the rider stopping their own voice (#1321). Every
 * listener already keys what is sounding by rider — SPEC's retrigger rule —
 * so a stop is a fire with nothing to start.
 */
export interface Board {
  clipId: string;
  /**
   * Filled by the server: firing is presence, and a listener needs to know
   * whose per-rider fader this rides.
   */
  fromId?: string;
  from?: string;
}
/**
 * SensorClaim is one socket telling the hub which sensors it has connected
 * (#610).
 * A Web Bluetooth grant cannot leave the browser that made it, so pairing
 * itself stays client-owned (ARCHITECTURE seam 1). What the hub owns is which
 * of a rider's sockets holds each kind — so the rider's other tabs and devices
 * stop offering to pair a second one, and so only one of them feeds the ride
 * record.
 */
export interface SensorClaim {
  /**
   * Kinds this socket holds: "trainer", "heart-rate", "power-meter" or
   * "cadence". Always the socket's WHOLE current set, never a delta — a
   * message lost to a reconnect can then never leave a claim stuck behind.
   */
  held: string[];
  /**
   * Which tab this is, so a reload reclaims what it already had instead of
   * locking itself out behind its own not-yet-reaped socket. Client-minted
   * and per-tab (sessionStorage); the hub treats it as an opaque label and
   * scopes it to the rider, so it can only ever address that rider's own
   * claims.
   */
  tab?: string;
  /**
   * A coarse word for the rider's OTHER screens to render: "phone",
   * "tablet" or "desktop". Never leaves the rider's own sockets.
   */
  device?: string;
}
/**
 * Poke is one rider asking for another rider's attention. The client sends
 * only To; the hub replaces every sender field from authenticated presence
 * before routing it to the addressed rider's sockets.
 * Between friends a poke is a DM line (#2721), and the DM service hands the
 * hub the same shape with Dm set: the thread is where it lives, and At is
 * the line's own time, so the socket and the thread's poll announce it once.
 */
export interface Poke {
  to?: string;
  fromId?: string;
  from?: string;
  at?: number /* int64 */;
  /**
   * The words a friend sent with it; never read from a client's socket.
   */
  text?: string;
  /**
   * A line in your DM thread with the poker, not only a moment in a channel.
   */
  dm?: boolean;
}
/**
 * PokeCooldownSeconds is how long before one rider may poke the same rider
 * again, through either door — a channel's socket or the DM thread. A poke
 * asks one person's machine for attention and must not become a harassment
 * button.
 */
export const PokeCooldownSeconds = 10;
/**
 * Moved tells a rider's sockets in one voice channel that the crew's owner or
 * an admin moved them into another (#2730), Discord's drag. The client goes
 * there the way a sidebar click would, and the call comes along.
 */
export interface Moved {
  /**
   * The voice channel they now belong in, and its name for the toast.
   */
  channel: string;
  name: string;
  /**
   * Who moved them.
   */
  by: string;
}
/**
 * AwayState is a rider stepping out (#706) — the Lounge's button, never a
 * timer: being off the bike is not being away, and a coach watching the stage
 * is present and not pedalling.
 * The whole state every time rather than a toggle, for the reason SensorClaim
 * carries its whole set: a message lost to a reconnect can then never strand a
 * rider away on everyone else's screen.
 */
export interface AwayState {
  away: boolean;
  /**
   * Why, from AwayReasons — "" is the plain away the button's face has
   * always sent, and the only thing one tap can produce. Ignored when Away
   * is false: coming back has no reason.
   */
  reason?: string;
}
/**
 * DeviceKind is what a socket says it is running on (#2131): one of
 * "desktop", "phone" or "tablet", sent once when the socket opens and again
 * on every reconnect, the way SensorClaim is resent.
 * Its own message rather than a field on SensorClaim, which already carries a
 * device word: that one is arbitration between a rider's OWN screens and is
 * addressed back to them alone, so it says nothing to the voice channel and
 * only exists once a sensor has been paired — which a spectator on a phone
 * never does. This one is visible to the whole channel by design and arrives
 * whether or not anything is paired.
 * Unlike the ping beside it on the roster, this is the client's word for
 * itself and nothing checks it. That is the right trade for a label this
 * coarse: a rider who lies about being on a phone misleads nobody about
 * anything, and the alternative is parsing a user agent, which is a
 * fingerprint. Kept to the three words below for the same reason — the
 * channel learns roughly what screen someone is on, never which device it is.
 */
export interface DeviceKind {
  kind: string;
}
/**
 * ClientMessage is the envelope for everything a client sends.
 */
export interface ClientMessage {
  cheer?: Cheer;
  board?: Board;
  metrics?: RiderMetrics;
  control?: Control;
  backfill?: Backfill;
  jukebox?: JukeboxCommand;
  sensors?: SensorClaim;
  poke?: Poke;
  away?: AwayState;
  device?: DeviceKind;
}
/**
 * Rider is presence: who is in the voice channel right now, with what the
 * dashboard needs to render them. FTP crosses the wire so every screen can
 * show %FTP — scoped to the channel by design, the same visibility
 * WATTROOM.md grants live watts.
 */
export interface Rider {
  id: string;
  name: string;
  /**
   * The rider's crew role, as a voice channel reads it: "owner", "admin"
   * or "member" (#2438). Coach is not a role — it is the session's.
   */
  role: string;
  ftpWatts: number /* int */;
  /**
   * For w/kg on the channel's screens — scoped to it like FTP, and for the
   * same reason: every contest in docs/SPEC.md is scored on it.
   */
  weightKg: number /* int */;
  /**
   * Lifetime XP, so the roster's faces wear the level ring the rest of the
   * app already shows (#690). Identity the channel may see, the same rule
   * the member list has followed since #253 — rides stay private.
   */
  totalXp: number /* int64 */;
  /**
   * Stepped out (#706). Presence, not a metric: the rider said so with the
   * Lounge's button, and every screen renders the mark instead of leaving
   * an open mic over an empty trainer.
   */
  away?: boolean;
  /**
   * Which kind of away, from AwayReasons; empty for the plain one. Voice
   * channel scope only, deliberately: the presence rail and anyone outside
   * the channel keep the plain away dot they have always had, because a
   * reason is a new detail about a person and a new detail does not get a
   * wider audience than the old one had.
   */
  awayReason?: string;
  /**
   * Pedalling right now (#1016) — watts inside the hub's riding window, so
   * a coast holds the mark and sitting down loses it. The server owns the
   * word: every screen used to decide it from the current sample's watts,
   * which flickered, and the friends page decided it from "a trainer is
   * talking", which never went out at all.
   */
  riding?: boolean;
  /**
   * On the running session's timeline (ADR-0059). Everyone else in the
   * channel spectates it: not driven, not counted, and drawn apart.
   */
  inSession?: boolean;
  /**
   * What this rider's soundboard has playing right now, and how far into it
   * the channel already is (#1681). A fire is one tick and gone
   * (ADR-0022/0033), so a rider who walked in halfway through a clip heard
   * silence and saw nobody playing anything; this is the same press, still
   * true a second later. The clip's real length is the listener's to know —
   * they fetch it — so the hub holds this for at most one clip's ceiling and
   * the client stops at the clip's own end.
   */
  sounding?: string;
  soundingMs?: number /* int64 */;
  /**
   * Round trip to this rider's socket in milliseconds (#2131), measured by
   * the server's own keepalive ping rather than reported by the client — so
   * it is safe to show one rider about another, which a self-reported number
   * would not be. Absent until the first ping of theirs has been answered.
   * Scoped to the voice channel like the watts and the FTP above it, and
   * for the same reason: this is live data about someone in the channel,
   * visible inside it while they are there and nowhere else. It never
   * reaches ChannelPresence, the friends panel or anything public — a ping
   * is a weak location signal, and the voice channel is where WATTROOM.md
   * already grants that class of visibility.
   * One rider, several sockets: the hub folds them to the LOWEST, which is
   * the rider's best screen. Their own breakdown per tab is the client's,
   * off the device labels #610 already carries.
   */
  pingMs?: number /* int */;
  /**
   * What that same socket is running on (#2131) — "desktop", "phone" or
   * "tablet". The socket the ping came from, so the two describe one screen
   * rather than two of the rider's; absent from a client that has not said.
   * See DeviceKind for why this is the client's word and why that is fine
   * here when it would not be for the ping.
   */
  device?: string;
}
/**
 * OwnConnection is what a socket is told about ITSELF, and about no other
 * socket in the voice channel (#2131).
 * Its own message rather than a field on Rider, deliberately: Rider is the
 * roster, the roster rides every tick to everybody, and a "fill this in only
 * for the socket it belongs to" rule on a broadcast struct is one careless
 * refactor away from publishing every rider's address to their crew — a
 * refactor that would pass every test asserting the tick's shape. Addressed
 * delivery makes the guarantee structural. SensorPairing is delivered the
 * same way for the same kind of reason (see tick.go, "Addressed to this
 * socket alone").
 * Nothing persists it. It is read off the request that opened the socket and
 * sent straight back, so there is no stored address to export under Art. 15
 * or to purge with an account.
 */
export interface OwnConnection {
  /**
   * The address this socket reached the server from, as httpx.ClientIP
   * resolves it: the last X-Forwarded-For hop behind the deploy's proxy
   * (#1824), else the peer.
   */
  ip: string;
}
/**
 * SessionState is the shared timeline, server-owned. Late joiners need no
 * catch-up protocol: every tick carries the whole truth — except the workout
 * definition, which is named by hash on every tick and sent in full only to
 * a socket that has not seen that hash (its first tick, the tick after a
 * pick), so a 64 KiB definition does not ride every second at 1–4 Hz (#1710).
 */
export interface SessionState {
  phase: string; // "idle" | "countdown" | "running" | "paused" | "done"
  /**
   * The session's id while one is open in this voice channel (#2438):
   * from the pick that opened it until the next one replaces it. Empty
   * while nobody has opened one.
   */
  id?: string;
  /**
   * Who is coaching it, by rider id and by name (#2438): whoever opened
   * it, until they hand it off. The one rider whose controls the server
   * takes, besides the crew's owner and admins ending it.
   */
  coach?: string;
  coachName?: string;
  /**
   * Seconds into the workout timeline. Advances only while running.
   */
  elapsed: number /* int */;
  /**
   * Seconds until the timeline starts, while in countdown.
   */
  countdownRemaining?: number /* int */;
  workoutName?: string;
  workoutJson?: string;
  /**
   * Names WorkoutJSON on the wire (#1710). A client keeps the last
   * definition it heard and fills it back in while the hash matches.
   */
  workoutHash?: string;
  totalSeconds?: number /* int */;
  /**
   * The rpm the current block asks the session's riders to turn (#1431):
   * the block's cadence band, else docs/SPEC.md's effort tiers. 0 while
   * nothing runs or the block expresses no preference. What smart autoplay
   * weighs against, said on the wire so a queue row can show which tracks
   * fit.
   */
  targetRpm?: number /* int */;
}
/**
 * JukeboxTrack is one video inside a queued playlist (#615). Ids and titles
 * both ride the wire: the client resolves them once when the playlist is
 * pasted, and the server needs the title for the now-playing timeline line.
 */
export interface JukeboxTrack {
  videoId: string;
  title: string;
}
export interface JukeboxEntry {
  /**
   * Unique within the voice channel, server-assigned: what
   * remove/vote/move address (#286).
   */
  id: string;
  /**
   * What is on the deck RIGHT NOW. For a playlist entry (#615) this is
   * Tracks[Index] and changes as the entry plays through — which is why
   * the whole client playback path needed no playlist branch of its own.
   */
  videoId: string;
  title: string;
  addedBy: string;
  /**
   * Where playback begins when this entry reaches the deck (?t= paste).
   */
  startSec?: number /* float64 */;
  /**
   * Upvotes float an entry above lower-voted ones (#286). The voters are
   * rider ids, not a count — scoped to the channel like every other live
   * field, and the only way a client renders "you voted" from truth, not
   * from its own click. The count is len(voters); nothing to keep in sync.
   */
  voters?: string[];
  /**
   * Set when the entry is a whole YouTube playlist queued as one thing
   * (#615) — a playlist takes ONE queue slot, so a paste cannot own the
   * channel's 50 and the vote order keeps meaning something.
   */
  playlistId?: string;
  playlistTitle?: string;
  /**
   * The playlist in order, resolved by the client that pasted it. Empty
   * for a single video: len(Tracks) > 0 is what makes an entry a playlist.
   */
  tracks?: JukeboxTrack[];
  /**
   * Which track is on the deck. Only ever moves within [0, len(Tracks)):
   * running off the end advances to the next QUEUE entry rather than
   * wrapping — a playlist plays once through and never restarts itself.
   */
  index?: number /* int */;
  /**
   * A track from the self-hosted pool (#267, ADR-0015) instead of a
   * YouTube video: the id the client fetches audio for. VideoID is empty
   * on such an entry, and `TrackID != ""` is what makes an entry a pool
   * track — the deck's rules do not otherwise care where audio comes from.
   * RMF's tile rules bind only while a YouTube entry plays (WATTROOM.md),
   * which is the whole reason a pool track may be audio-only.
   */
  trackId?: string;
  /**
   * Display only, resolved by whoever queued it: the server holds no
   * track metadata on the deck, the same way it holds no YouTube titles.
   */
  artist?: string;
  /**
   * Tempo of a library entry, 0 when untagged (#1431).
   */
  bpm?: number /* int */;
  /**
   * Length of a library entry in milliseconds (#1509): measured by the
   * server at upload, so every client — muted, sitting out, still loading
   * — draws the same seek bar. 0 for a video, whose length only a player
   * that loaded it knows.
   */
  durationMs?: number /* int */;
}
/**
 * JukeboxState is the server's truth about what plays where. Clients chase the
 * anchor: position = PositionSec, plus SERVER time since AnchorMs while
 * playing — a client's own wall clock is skewed by seconds and applying it
 * here is what made the jukebox "not synced" (#286). Clients estimate the
 * offset from ServerTick.At and translate.
 * The audio itself is local per rider — their iframe, their volume — and never
 * enters the voice path (SPEC voice channel audio defaults).
 */
export interface JukeboxState {
  queue: JukeboxEntry[];
  current?: JukeboxEntry;
  playing: boolean;
  positionSec: number /* float64 */;
  anchorMs: number /* int64 */;
  /**
   * What the channel just played, newest first (#286) — the deck's short
   * memory, so "put that on again" is one tap and nobody retypes a link.
   */
  history: JukeboxEntry[];
}
/**
 * SessionRecapRider is one person a session saw, and when — the only two
 * things a recap may say about anybody (ADR-0034). No watts, no kJ, no
 * execution, no heart rate, no per-rider workout: everyone in the voice
 * channel watched the roster, so the card writes down what they already saw,
 * and WATTROOM.md's metrics rules stay exactly where they are.
 */
export interface SessionRecapRider {
  /**
   * The rider's user id, so the client can key a row and an account purge
   * can find the intervals it has to remove. A display name identifies
   * nobody reliably.
   */
  id: string;
  rider: string;
  /**
   * Unix millis: first and last time the session saw them present.
   */
  from: number /* int64 */;
  to: number /* int64 */;
  /**
   * They have a ride row for this session — a filled pip. False is the
   * coach without a trainer, or the person on the sofa in voice.
   */
  rode: boolean;
}
/**
 * SessionRecap is what a finished session leaves behind (ADR-0034): the first
 * thing in this app that survives a reload of a session's timeline. Written
 * once when the session ends, rendered as one collapsed card the chat pane
 * merges in by timestamp — the artifact ADR-0022 said to build if riders ever
 * asked, rather than the persisted event stream it refused.
 */
export interface SessionRecap {
  id: string;
  workout: string;
  /**
   * Unix millis, the shared timeline's own clock.
   */
  startedAt: number /* int64 */;
  endedAt: number /* int64 */;
  riders: SessionRecapRider[];
  /**
   * The VIEWER's own ride from this session, if they rode it — never
   * anybody else's (#1560). The card still carries no numbers, and none of
   * ADR-0034's four settled points move: this is a door to the page where
   * the rider's own numbers already live, filled per request and stored
   * nowhere. Empty for the coach without a trainer, and on the tick that
   * posts the recap, where the ride has not been written yet.
   */
  rideId?: string;
  /**
   * The session it recaps and the voice channel it ran in (#2600), where
   * the recap row keeps them: an ended session's address finds its way
   * back to the channel through these. Empty on a recap from before M9.
   */
  sessionId?: string;
  channelId?: string;
}
/**
 * ServerTick is a voice channel's coalesced 1 Hz broadcast: every rider's
 * latest sample, the roster, and the shared session state.
 */
export interface ServerTick {
  at: number /* int64 */; // unix millis
  state: SessionState;
  jukebox: JukeboxState;
  /**
   * This second's cheers, drained each tick like metrics.
   */
  cheers?: Cheer[];
  /**
   * This second's soundboard fires, drained the same way. The clip itself
   * is fetched over HTTP — only the trigger rides the tick (ADR-0033).
   */
  board?: Board[];
  /**
   * No chat (#2437, ADR-0058): a voice channel carries none, and a text
   * channel's chat is read over HTTP and re-read on the lobby ping.
   * The recap of the session that just ended (ADR-0034), on the tick where
   * the row lands — the async write's follow-up. Everyone else gets it from the backlog on their next
   * join, because unlike everything above it, this one is durable.
   */
  recap?: SessionRecap;
  /**
   * What happened in the channel this second (#321) — the lines the lounge
   * draws beside the deck. Ephemeral, like the cheers above.
   */
  events?: ChannelEvent[];
  /**
   * Sprint moment (#30): armed/live window and, after it closes, the podium.
   */
  sprint?: SprintState;
  /**
   * Running game mode (#31/#32), replacing the workout timeline while on.
   */
  game?: GameState;
  /**
   * Live execution per rider (#27) — the SPEC score so far this session.
   */
  execution?: { [key: string]: number /* float64 */};
  /**
   * Who the LiveKit webhooks say is in voice (#467), by rider id. A client
   * learns this from LiveKit only once it has joined itself, so without the
   * server's answer an empty voice roster is indistinguishable from a full
   * one you have not entered yet.
   */
  voice?: string[];
  roster: Rider[];
  riders: { [key: string]: RiderMetrics};
}
/**
 * ChannelPresence is the hub's live answer for one voice channel (#251, #2436):
 * the sidebar renders this shape. It rides the channel list rather than the
 * channel's WS, but it is shared vocabulary like Rider — one canonical home,
 * generated for the client like everything here.
 */
export interface ChannelPresence {
  /**
   * Riders connected to the channel WS, counted as people, not sockets.
   */
  connected?: number /* int */;
  phase?: string;
  /**
   * Display names — members-only server-side, scoped to the channel like
   * all live data. For rendering only: display names are not unique, so
   * anything asking "is this particular person in there?" reads RiderIDs
   * instead (#649).
   */
  riders?: string[];
  /**
   * The same riders by account id, in the same order as Riders.
   */
  riderIds?: string[];
  /**
   * Who is in the voice channel, and who has a camera live (LiveKit webhooks).
   */
  voice?: string[];
  cameras?: string[];
  /**
   * Names with live metrics in the last few seconds — the watt dot.
   */
  riding?: string[];
  /**
   * The same riders by account id, in the same order as Riding.
   */
  ridingIds?: string[];
  /**
   * Who said away (#1742), by account id: the sidebar's dot and the rider's
   * tile used to disagree — away on the tile, online two panels over.
   */
  awayIds?: string[];
  /**
   * The late-join radar: what is on and how far in, while a session runs.
   */
  workoutName?: string;
  elapsedSec?: number /* int */;
}
/**
 * LiveSession is one session running in a crew's voice channel (#2438), as
 * GET /api/crews/{id}/live answers it — only for channels the caller may
 * enter, like every other live read.
 */
export interface LiveSession {
  id: string;
  channel: string;
  workout: string;
  phase: string; // "countdown" | "running" | "paused"
  elapsed: number /* int */;
  coach: string;
  coachName: string;
  /**
   * Who is in the channel, by name and by id in the same order.
   */
  riders: string[];
  riderIds: string[];
}
/**
 * Error tells a client why its connection or command was refused.
 */
export interface Error {
  /**
   * One of errors.md's closed set — validation_error, invalid_request,
   * unauthorized, forbidden, not_found, conflict, rate_limited,
   * internal_error — optionally prefixed with the surface the refusal
   * belongs to ("jukebox_rate_limited"), so a client can land it beside
   * the control the rider touched instead of in the channel's own refusal
   * slot. The prefix routes; the part after it is always a code from the
   * set.
   */
  code: string;
  message: string;
}
/**
 * SensorPairing is the hub's answer to a SensorClaim: what this socket ended
 * up holding, and what one of the rider's other screens is already holding.
 * It goes ONLY to the sockets of the rider it describes, and deliberately not
 * on the tick: what a rider straps on is nobody else's business (privacy is
 * architecture, WATTROOM.md), and the tick stays one message per voice
 * channel per second (ARCHITECTURE seam 2) for state that changes every
 * second — this changes only when somebody pairs or unpairs.
 */
export interface SensorPairing {
  /**
   * Kinds this socket holds, as GRANTED — the claim minus anything another
   * of the rider's screens got to first.
   */
  held?: string[];
  /**
   * Kind -> the device word of the rider's other screen holding it. What
   * the sensor cards render instead of a pair button.
   */
  elsewhere?: { [key: string]: string};
}
/**
 * ServerMessage is the envelope for everything the server sends.
 */
export interface ServerMessage {
  tick?: ServerTick;
  error?: Error;
  pairing?: SensorPairing;
  poke?: Poke;
  moved?: Moved;
  /**
   * This socket's own address, sent once on join and to nobody else (#2131).
   */
  connection?: OwnConnection;
}
/**
 * LobbyPing is what the lobby socket says (#251): re-fetch. Channel names the
 * one text channel whose log changed (#2435, the first step of #2324), so a
 * client refetches only the channel it is looking at; absent, or when several
 * changes coalesced into one ping, everything is to be re-fetched. An id and
 * nothing else — the lines stay behind the channel's own gate — and only to
 * riders who may enter the channel (#2821): its activity is gated too.
 */
export interface LobbyPing {
  channel?: string;
}

//////////
// source: status.go

/**
 * StatusLine is a rider's own line (ADR-0060): what shows beside their name
 * wherever their name shows. Absent is no status; one whose ExpiresAt has
 * passed is never sent.
 */
export interface StatusLine {
  /**
   * A Unicode emoji, or a crew emoji's `:name:`.
   */
  emoji?: string;
  /**
   * The crew emoji's picture, at /api/emoji/{EmojiID}. Absent for a Unicode
   * emoji, and for a crew emoji the crew has since deleted — that one shows
   * its :name:.
   */
  emojiId?: string;
  text?: string;
  /**
   * When it clears, RFC 3339; absent is "don't clear".
   */
  expiresAt?: string;
}
