// Code generated by tygo. DO NOT EDIT.
// GENERATED by tygo from server/internal/protocol — do not edit.
// Regenerate with `make protocol`.

//////////
// source: protocol.go
/*
Package protocol defines the WebSocket message types. These Go structs are
the single source of truth; `make protocol` generates the TypeScript types
via tygo (see WATTROOM.md decisions: WS protocol).
*/

/**
 * RiderMetrics is one rider's live sample, sent client -> server at ~1 Hz.
 */
export interface RiderMetrics {
  watts: number /* int */;
  hr?: number /* int */;
  cadence?: number /* int */;
  seq: number /* int */; // monotonic per ride, for reconnect dedup
}
/**
 * SprintScore is one rider's place on the mini-podium.
 */
export interface SprintScore {
  riderId: string;
  name: string;
  wkg: number /* float64 */;
  watts: number /* int */;
}
/**
 * SprintState rides the tick while a sprint moment is armed, live, or just
 * scored. Times are server-clock millis, the same clock as ServerTick.At —
 * clients render the klaxon countdown and the window from these anchors.
 */
export interface SprintState {
  startsAtMs: number /* int64 */;
  endsAtMs: number /* int64 */;
  /**
   * Filled once the window closes; podium order.
   */
  results?: SprintScore[];
}
/**
 * GameRider is one rider's standing inside a game mode.
 */
export interface GameRider {
  eliminated?: boolean;
  lives?: number /* int */;
  score?: number /* float64 */;
  onFront?: boolean;
  /**
   * The rider's personal target as a fraction of their FTP; 0 = ride free.
   */
  targetPct?: number /* float64 */;
}
/**
 * GameState is a running game mode on the tick (#31). One generic shape for
 * all seven modes: the client renders labels per mode, the server owns every
 * rule. Riders execute their own %FTP targets, so mixed groups stay fair.
 */
export interface GameState {
  mode: string;
  phase: string; // "running" | "done"
  round?: number /* int */;
  /**
   * The shared line as a fraction of FTP (ramp modes), the called zone
   * (lava), or the hole target pct (golf) — mode-dependent, one at a time.
   */
  linePct?: number /* float64 */;
  calledZone?: number /* int */;
  roundEndsAtMs?: number /* int64 */;
  meterHidden?: boolean;
  roomDistance?: number /* float64 */;
  riders: { [key: string]: GameRider};
  podium?: SprintScore[];
}
/**
 * Control is a coach/owner command over the shared session (SPEC roles matrix:
 * pick workout, start countdown, pause/end). The server enforces the role.
 */
export interface Control {
  action: string; // "pick" | "start" | "pause" | "resume" | "end"
  /**
   * Workout definition, opaque to the server: the docs/SPEC.md JSON as a
   * string. The server owns the clock, the clients own the targets.
   */
  workoutName?: string;
  workoutJson?: string;
  /**
   * Total length in seconds, so the server can end the session on time
   * without parsing the workout.
   */
  totalSeconds?: number /* int */;
  /**
   * For action "game": which mode to start.
   */
  gameMode?: string;
}
/**
 * Backfill is a reconnect's replay: samples the client buffered while the
 * socket was down (WATTROOM.md crash safety). The server dedupes by Seq, so
 * resending is always safe and never double-counts.
 */
export interface Backfill {
  samples: RiderMetrics[];
}
/**
 * JukeboxCommand is any member's jukebox action — the matrix defaults
 * play/pause/skip to members, and adding is everyone's.
 */
export interface JukeboxCommand {
  action: string; // "add" | "remove" | "vote" | "move" | "play" | "pause" | "skip" | "back" | "skipPlaylist" | "seek" | "ended"
  videoId?: string;
  title?: string;
  /**
   * For "add": queue a whole YouTube playlist as one entry (#615). The
   * client resolves the tracks — the server still knows nothing about
   * YouTube, it just holds the list the paste produced.
   */
  playlistId?: string;
  playlistTitle?: string;
  tracks?: JukeboxTrack[];
  /**
   * For "remove" | "vote" | "move": which queue entry (#286). Video ids
   * are not unique — the same track queued twice is two entries, and
   * addressing by video used to hit the wrong one.
   */
  entryId?: string;
  /**
   * For "move": the entry's new index in the queue, clamped to it.
   */
  index?: number /* int */;
  /**
   * For "seek": the new shared playhead. For "add": start the entry here
   * (a pasted ?t= timestamp) — 0 means the beginning, like any URL.
   */
  positionSec?: number /* float64 */;
  /**
   * For "ended": the anchor the client was playing against. Every client
   * (and tab) reports the end — the epoch match makes N echoes advance
   * the queue exactly once even when the same video is queued twice.
   */
  anchorMs?: number /* int64 */;
}
/**
 * ChatLine is one ephemeral room message (#146, ADR-0010): room-scoped,
 * never persisted — it rides the tick like cheers and dies with the page.
 * Warm-up and phone talk; mid-effort stays the cheers' job.
 */
export interface ChatLine {
  /**
   * Persisted identity (ADR-0010 amended, #201) — what reactions attach to.
   * Empty when the server runs without a database.
   */
  id?: string;
  from: string; // filled by the server, like cheers
  /**
   * The author's rider id (#219): display names are not unique, and the
   * client's own-message suppression must not mute a namesake.
   */
  fromId?: string;
  text: string;
  /**
   * A pasted image (#279): id of a room-scoped blob the client uploaded via
   * POST /api/rooms/{slug}/chat/images before sending; rendered from the
   * matching GET. A line may be image-only (empty text).
   */
  imageId?: string;
  at: number /* int64 */; // server millis, for ordering only
}
/**
 * ChatID attaches the persisted identity to a line broadcast on an earlier
 * tick (#219): the save runs off the read loop, so the id follows the line.
 * FromID+At name the line — the 1/s per-rider chat limit makes the pair unique.
 */
export interface ChatID {
  fromId: string;
  at: number /* int64 */;
  id: string;
}
/**
 * ChatReact toggles one rider's emoji on one message (#201) — the cheer
 * vocabulary, attached instead of thrown.
 */
export interface ChatReact {
  messageId: string;
  emoji: string;
}
/**
 * ChatReactionCount is a changed total, broadcast on the tick — plus who
 * changed it and which way (#219): the actor's own tabs reconcile their
 * "did I react" highlight from the server instead of trusting the click.
 */
export interface ChatReactionCount {
  messageId: string;
  emoji: string;
  count: number /* int */;
  by?: string; // rider id of the toggler
  added: boolean;
}
/**
 * RoomEvent is something the ROOM did, next to what riders said (#321): the
 * jukebox changing under everyone is half of what happened here, and thirty
 * seconds later "who put this on?" has no other answer. Structured, not a
 * sentence — the client owns the wording, so the chat pane and the dock name
 * a track identically.
 * Ephemeral by design (ADR-0019): it rides the tick like cheers and is never
 * written to the chat table. A month of "now playing" in the backlog is noise.
 */
export interface RoomEvent {
  /**
   * Room-unique and stable across re-broadcasts: a growing burst re-sends
   * the SAME id with a higher Count, and clients replace the line in place.
   */
  id: string;
  kind: string; // "jukebox" | "session"
  /**
   * jukebox: "queued" | "removed" | "skipped" | "playing"
   * session: "planned" | "moved" | "cancelled" | "started" | "ended"
   */
  verb: string;
  /**
   * Who did it. Empty when nobody did — the deck advancing on its own, or
   * a session the clock started.
   */
  actor?: string;
  /**
   * The title the dock shows, so both surfaces name the same track. Empty
   * on a coalesced burst, which has no single title left to show.
   */
  track?: string;
  /**
   * The workout a session line is about.
   */
  subject?: string;
  /**
   * When that session is planned for, server millis. 0 on a line with no
   * time of its own ("started", "ended").
   */
  when?: number /* int64 */;
  /**
   * For "playing": who put this track in the queue.
   */
  queuedBy?: string;
  /**
   * How many tracks this one line covers — 1 normally, more when a burst
   * of adds coalesced ("queued 8 tracks"). Eight lines would push the
   * actual conversation off the screen.
   */
  count: number /* int */;
  at: number /* int64 */; // server millis, for ordering only
}
/**
 * Cheer is the room's reaction layer (#74) — and the spectator's one verb.
 */
export interface Cheer {
  emoji: string;
  /**
   * Sender name, filled by the server: cheering is presence.
   */
  from?: string;
}
/**
 * SensorClaim is one socket telling the hub which sensors it has connected
 * (#610).
 * A Web Bluetooth grant cannot leave the browser that made it, so pairing
 * itself stays client-owned (ARCHITECTURE seam 1). What the hub owns is which
 * of a rider's sockets holds each kind — so the rider's other tabs and devices
 * stop offering to pair a second one, and so only one of them feeds the ride
 * record.
 */
export interface SensorClaim {
  /**
   * Kinds this socket holds: "trainer", "heart-rate", "power-meter" or
   * "cadence". Always the socket's WHOLE current set, never a delta — a
   * message lost to a reconnect can then never leave a claim stuck behind.
   */
  held: string[];
  /**
   * Which tab this is, so a reload reclaims what it already had instead of
   * locking itself out behind its own not-yet-reaped socket. Client-minted
   * and per-tab (sessionStorage); the hub treats it as an opaque label and
   * scopes it to the rider, so it can only ever address that rider's own
   * claims.
   */
  tab?: string;
  /**
   * A coarse word for the rider's OTHER screens to render: "phone",
   * "tablet" or "desktop". Never leaves the rider's own sockets.
   */
  device?: string;
}
/**
 * Poke is one rider asking for another rider's attention. The client sends
 * only To; the hub replaces every sender field from authenticated presence
 * before routing it to the addressed rider's sockets.
 */
export interface Poke {
  to?: string;
  fromId?: string;
  from?: string;
  at?: number /* int64 */;
}
/**
 * ClientMessage is the envelope for everything a client sends.
 */
export interface ClientMessage {
  chat?: ChatLine;
  chatReact?: ChatReact;
  cheer?: Cheer;
  metrics?: RiderMetrics;
  control?: Control;
  backfill?: Backfill;
  jukebox?: JukeboxCommand;
  sensors?: SensorClaim;
  poke?: Poke;
}
/**
 * Rider is presence: who is in the room right now, with what the dashboard
 * needs to render them. FTP crosses the wire so every screen can show %FTP —
 * room-scoped by design, the same visibility WATTROOM.md grants live watts.
 */
export interface Rider {
  id: string;
  name: string;
  role: string;
  ftpWatts: number /* int */;
  /**
   * For w/kg on room screens — room-scoped like FTP, and for the same reason:
   * every contest in docs/SPEC.md is scored on it.
   */
  weightKg: number /* int */;
  /**
   * Lifetime XP, so the roster's faces wear the level ring the rest of the
   * app already shows (#690). Room-visible identity, the same rule the
   * member list has followed since #253 — rides stay private.
   */
  totalXp: number /* int64 */;
}
/**
 * SessionState is the shared timeline, server-owned. Late joiners need no
 * catch-up protocol: every tick carries the whole truth.
 */
export interface SessionState {
  phase: string; // "idle" | "countdown" | "running" | "paused" | "done"
  /**
   * Seconds into the workout timeline. Advances only while running.
   */
  elapsed: number /* int */;
  /**
   * Seconds until the timeline starts, while in countdown.
   */
  countdownRemaining?: number /* int */;
  workoutName?: string;
  workoutJson?: string;
  totalSeconds?: number /* int */;
}
/**
 * JukeboxTrack is one video inside a queued playlist (#615). Ids and titles
 * both ride the wire: the client resolves them once when the playlist is
 * pasted, and the server needs the title for the now-playing timeline line.
 */
export interface JukeboxTrack {
  videoId: string;
  title: string;
}
export interface JukeboxEntry {
  /**
   * Room-unique, server-assigned: what remove/vote/move address (#286).
   */
  id: string;
  /**
   * What is on the deck RIGHT NOW. For a playlist entry (#615) this is
   * Tracks[Index] and changes as the entry plays through — which is why
   * the whole client playback path needed no playlist branch of its own.
   */
  videoId: string;
  title: string;
  addedBy: string;
  /**
   * Where playback begins when this entry reaches the deck (?t= paste).
   */
  startSec?: number /* float64 */;
  /**
   * Upvotes float an entry above lower-voted ones (#286). The voters are
   * rider ids, not a count — room-scoped like every other live field, and
   * the only way a client renders "you voted" from truth, not from its
   * own click. The count is len(voters); nothing to keep in sync.
   */
  voters?: string[];
  /**
   * Set when the entry is a whole YouTube playlist queued as one thing
   * (#615) — a playlist takes ONE queue slot, so a paste cannot own the
   * room's 50 and the vote order keeps meaning something.
   */
  playlistId?: string;
  playlistTitle?: string;
  /**
   * The playlist in order, resolved by the client that pasted it. Empty
   * for a single video: len(Tracks) > 0 is what makes an entry a playlist.
   */
  tracks?: JukeboxTrack[];
  /**
   * Which track is on the deck. Only ever moves within [0, len(Tracks)):
   * running off the end advances to the next QUEUE entry rather than
   * wrapping — a playlist plays once through and never restarts itself.
   */
  index?: number /* int */;
}
/**
 * JukeboxState is the server's truth about what plays where. Clients chase the
 * anchor: position = PositionSec, plus SERVER time since AnchorMs while
 * playing — a client's own wall clock is skewed by seconds and applying it
 * here is what made the jukebox "not synced" (#286). Clients estimate the
 * offset from ServerTick.At and translate.
 * The audio itself is local per rider — their iframe, their volume — and never
 * enters the voice path (SPEC room audio defaults).
 */
export interface JukeboxState {
  queue: JukeboxEntry[];
  current?: JukeboxEntry;
  playing: boolean;
  positionSec: number /* float64 */;
  anchorMs: number /* int64 */;
  /**
   * What the room just played, newest first (#286) — the deck's short
   * memory, so "put that on again" is one tap and nobody retypes a link.
   */
  history: JukeboxEntry[];
}
/**
 * ServerTick is the coalesced 1 Hz room broadcast: every rider's latest
 * sample, the roster, and the shared session state.
 */
export interface ServerTick {
  at: number /* int64 */; // unix millis
  state: SessionState;
  jukebox: JukeboxState;
  /**
   * This second's cheers, drained each tick like metrics.
   */
  cheers?: Cheer[];
  /**
   * This second's chat lines, drained the same way. No backlog on join —
   * ephemeral means ephemeral.
   */
  chat?: ChatLine[];
  chatReactions?: ChatReactionCount[];
  /**
   * Persisted ids for lines already broadcast (#219) — the async save's
   * follow-up, unlocking reactions on them.
   */
  chatIds?: ChatID[];
  /**
   * What the room did this second (#321) — jukebox actions the chat pane
   * interleaves with the talking. Ephemeral, like the cheers above.
   */
  events?: RoomEvent[];
  /**
   * Sprint moment (#30): armed/live window and, after it closes, the podium.
   */
  sprint?: SprintState;
  /**
   * Running game mode (#31/#32), replacing the workout timeline while on.
   */
  game?: GameState;
  /**
   * Live execution per rider (#27) — the SPEC score so far this session.
   */
  execution?: { [key: string]: number /* float64 */};
  /**
   * Who the LiveKit webhooks say is in voice (#467), by rider id. A client
   * learns this from LiveKit only once it has joined itself, so without the
   * server's answer an empty voice roster is indistinguishable from a full
   * one you have not entered yet.
   */
  voice?: string[];
  roster: Rider[];
  riders: { [key: string]: RiderMetrics};
}
/**
 * RoomPresence is the hub's live answer for one room (#251): the rooms list,
 * the rail, and the /rooms page all render this shape. It rides GET /api/rooms
 * rather than the room WS, but it is shared vocabulary like Rider — one
 * canonical home, generated for the client like everything here.
 */
export interface RoomPresence {
  /**
   * Riders connected to the room WS, counted as people, not sockets.
   */
  connected?: number /* int */;
  phase?: string;
  /**
   * Display names — members-only server-side, room-scoped like all live data.
   */
  riders?: string[];
  /**
   * Who is in the voice channel, and who has a camera live (LiveKit webhooks).
   */
  voice?: string[];
  cameras?: string[];
  /**
   * Names with live metrics in the last few seconds — the watt dot.
   */
  riding?: string[];
  /**
   * The late-join radar: what is on and how far in, while a session runs.
   */
  workoutName?: string;
  elapsedSec?: number /* int */;
}
/**
 * Error tells a client why its connection or command was refused.
 */
export interface Error {
  code: string;
  message: string;
}
/**
 * SensorPairing is the hub's answer to a SensorClaim: what this socket ended
 * up holding, and what one of the rider's other screens is already holding.
 * It goes ONLY to the sockets of the rider it describes, and deliberately not
 * on the tick: what a rider straps on is nobody else's business (privacy is
 * architecture, WATTROOM.md), and the tick stays one message per room per
 * second (ARCHITECTURE seam 2) for state that changes every second — this
 * changes only when somebody pairs or unpairs.
 */
export interface SensorPairing {
  /**
   * Kinds this socket holds, as GRANTED — the claim minus anything another
   * of the rider's screens got to first.
   */
  held?: string[];
  /**
   * Kind -> the device word of the rider's other screen holding it. What
   * the sensor cards render instead of a pair button.
   */
  elsewhere?: { [key: string]: string};
}
/**
 * ServerMessage is the envelope for everything the server sends.
 */
export interface ServerMessage {
  tick?: ServerTick;
  error?: Error;
  pairing?: SensorPairing;
  poke?: Poke;
}
