// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audience.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const crewAudience = `-- name: CrewAudience :many

select c.owner_id as user_id from crews c where c.id = $1::uuid
union
select r.user_id from crew_roles r
where r.crew_id = $1::uuid and r.role in ('member', 'admin')
`

// Who a change concerns (#2324): the riders whose lobby sockets a presence
// ping should reach, and nobody else. internal/audience composes these.
// A crew's own change: its owner, its admins and its members. Not a banned
// rider — the crew is off their screen; a ban names them itself.
func (q *Queries) CrewAudience(ctx context.Context, crewID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, crewAudience, crewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const crewmatesOf = `-- name: CrewmatesOf :many
with mine as (
    select c.id from crews c where c.owner_id = $1::uuid
    union
    select r.crew_id from crew_roles r
    where r.user_id = $1::uuid and r.role in ('member', 'admin')
)
select c.owner_id as user_id from crews c where c.id in (select id from mine)
union
select r.user_id from crew_roles r
where r.crew_id in (select id from mine) and r.role in ('member', 'admin')
`

// Everyone in any crew this rider is in, owner or member.
func (q *Queries) CrewmatesOf(ctx context.Context, rider pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, crewmatesOf, rider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const friendsOf = `-- name: FriendsOf :many
select (case when f.requester_id = any($1::uuid[]) then f.addressee_id
             else f.requester_id end)::uuid as user_id
from friendships f
where f.status = 'accepted'
  and (f.requester_id = any($1::uuid[]) or f.addressee_id = any($1::uuid[]))
  and not rider_hidden(f.requester_id, f.addressee_id)
`

// The accepted friends of any of these riders — who sees them on a friends
// list (ADR-0012). A hidden pair is not (#3202): neither lists the other.
func (q *Queries) FriendsOf(ctx context.Context, riders []pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, friendsOf, riders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
