// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdentity = `-- name: CreateIdentity :exec
insert into identities (provider, provider_user_id, user_id, access_token, refresh_token, refresh_token_enc, token_expires_at)
values ($1, $2, $3, $4, $5, $6, $7)
`

type CreateIdentityParams struct {
	Provider        string
	ProviderUserID  string
	UserID          pgtype.UUID
	AccessToken     *string
	RefreshToken    *string
	RefreshTokenEnc []byte
	TokenExpiresAt  pgtype.Timestamptz
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) error {
	_, err := q.db.Exec(ctx, createIdentity,
		arg.Provider,
		arg.ProviderUserID,
		arg.UserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.RefreshTokenEnc,
		arg.TokenExpiresAt,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
insert into sessions (token_hash, user_id, expires_at)
values ($1, $2, $3)
`

type CreateSessionParams struct {
	TokenHash []byte
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
delete from sessions
 where ctid in (select ctid from sessions where expires_at <= now() limit 10000)
`

// Bounded (audit 2026-09-09): the caller loops while a batch comes back full.
func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteIdentity = `-- name: DeleteIdentity :execrows
delete from identities where user_id = $1 and provider = $2
`

type DeleteIdentityParams struct {
	UserID   pgtype.UUID
	Provider string
}

func (q *Queries) DeleteIdentity(ctx context.Context, arg DeleteIdentityParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIdentity, arg.UserID, arg.Provider)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
delete from sessions where token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteUserSessionsExcept = `-- name: DeleteUserSessionsExcept :execrows
delete from sessions where user_id = $1 and token_hash <> $2
`

type DeleteUserSessionsExceptParams struct {
	UserID    pgtype.UUID
	TokenHash []byte
}

// Every other screen signed in to the account (#1607): the one asking keeps
// its session — pass a hash no session has to end them all.
func (q *Queries) DeleteUserSessionsExcept(ctx context.Context, arg DeleteUserSessionsExceptParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserSessionsExcept, arg.UserID, arg.TokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdentity = `-- name: GetIdentity :one
select provider, provider_user_id, user_id, access_token, refresh_token, token_expires_at, created_at, refresh_token_enc from identities where provider = $1 and provider_user_id = $2
`

type GetIdentityParams struct {
	Provider       string
	ProviderUserID string
}

func (q *Queries) GetIdentity(ctx context.Context, arg GetIdentityParams) (Identity, error) {
	row := q.db.QueryRow(ctx, getIdentity, arg.Provider, arg.ProviderUserID)
	var i Identity
	err := row.Scan(
		&i.Provider,
		&i.ProviderUserID,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
		&i.RefreshTokenEnc,
	)
	return i, err
}

const getSessionUser = `-- name: GetSessionUser :one
select u.id, u.display_name, u.avatar_url, u.ftp_watts, u.weight_kg, u.created_at, u.strava_upload, u.email, u.notify_planned, u.unsub_token, u.friend_code, u.ics_token, u.accent_palette, u.color_scheme, u.email_verified_at, u.email_pending, u.email_verify_hash, u.email_verify_expires, u.email_required, u.timezone, u.lthr, u.ftp_source, u.weight_source, u.recover_hash, u.recover_expires
from sessions s
join users u on u.id = s.user_id
where s.token_hash = $1 and s.expires_at > now()
`

func (q *Queries) GetSessionUser(ctx context.Context, tokenHash []byte) (User, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.FtpWatts,
		&i.WeightKg,
		&i.CreatedAt,
		&i.StravaUpload,
		&i.Email,
		&i.NotifyPlanned,
		&i.UnsubToken,
		&i.FriendCode,
		&i.IcsToken,
		&i.AccentPalette,
		&i.ColorScheme,
		&i.EmailVerifiedAt,
		&i.EmailPending,
		&i.EmailVerifyHash,
		&i.EmailVerifyExpires,
		&i.EmailRequired,
		&i.Timezone,
		&i.Lthr,
		&i.FtpSource,
		&i.WeightSource,
		&i.RecoverHash,
		&i.RecoverExpires,
	)
	return i, err
}

const getUserIdentity = `-- name: GetUserIdentity :one
select provider, provider_user_id, user_id, access_token, refresh_token, token_expires_at, created_at, refresh_token_enc from identities where user_id = $1 and provider = $2
`

type GetUserIdentityParams struct {
	UserID   pgtype.UUID
	Provider string
}

func (q *Queries) GetUserIdentity(ctx context.Context, arg GetUserIdentityParams) (Identity, error) {
	row := q.db.QueryRow(ctx, getUserIdentity, arg.UserID, arg.Provider)
	var i Identity
	err := row.Scan(
		&i.Provider,
		&i.ProviderUserID,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
		&i.RefreshTokenEnc,
	)
	return i, err
}

const listPlaintextRefreshTokens = `-- name: ListPlaintextRefreshTokens :many
select provider, provider_user_id, refresh_token from identities
where refresh_token is not null and refresh_token <> '' and refresh_token_enc is null
limit 500
`

type ListPlaintextRefreshTokensRow struct {
	Provider       string
	ProviderUserID string
	RefreshToken   *string
}

// Rows still holding a plaintext refresh token, for the one-time backfill
// (#697). Bounded by the number of third-party connections, not by riders.
func (q *Queries) ListPlaintextRefreshTokens(ctx context.Context) ([]ListPlaintextRefreshTokensRow, error) {
	rows, err := q.db.Query(ctx, listPlaintextRefreshTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlaintextRefreshTokensRow
	for rows.Next() {
		var i ListPlaintextRefreshTokensRow
		if err := rows.Scan(&i.Provider, &i.ProviderUserID, &i.RefreshToken); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserProviders = `-- name: ListUserProviders :many
select provider from identities where user_id = $1 order by created_at
`

func (q *Queries) ListUserProviders(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserProviders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var provider string
		if err := rows.Scan(&provider); err != nil {
			return nil, err
		}
		items = append(items, provider)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sealRefreshToken = `-- name: SealRefreshToken :exec

update identities set refresh_token_enc = $3, refresh_token = null
where provider = $1 and provider_user_id = $2
`

type SealRefreshTokenParams struct {
	Provider        string
	ProviderUserID  string
	RefreshTokenEnc []byte
}

// a page (audit 2026-09-09); the backfill loops while pages are full
// Seal one row in place. The plaintext goes in the same statement it is
// replaced by, so a crash mid-backfill leaves every row either sealed or
// untouched, never neither.
func (q *Queries) SealRefreshToken(ctx context.Context, arg SealRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, sealRefreshToken, arg.Provider, arg.ProviderUserID, arg.RefreshTokenEnc)
	return err
}

const updateIdentityTokens = `-- name: UpdateIdentityTokens :exec
update identities
set access_token = $3, refresh_token = $4, refresh_token_enc = $5, token_expires_at = $6
where provider = $1 and provider_user_id = $2
`

type UpdateIdentityTokensParams struct {
	Provider        string
	ProviderUserID  string
	AccessToken     *string
	RefreshToken    *string
	RefreshTokenEnc []byte
	TokenExpiresAt  pgtype.Timestamptz
}

func (q *Queries) UpdateIdentityTokens(ctx context.Context, arg UpdateIdentityTokensParams) error {
	_, err := q.db.Exec(ctx, updateIdentityTokens,
		arg.Provider,
		arg.ProviderUserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.RefreshTokenEnc,
		arg.TokenExpiresAt,
	)
	return err
}
