// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdentity = `-- name: CreateIdentity :exec
insert into identities (provider, provider_user_id, user_id, access_token, refresh_token, token_expires_at)
values ($1, $2, $3, $4, $5, $6)
`

type CreateIdentityParams struct {
	Provider       string
	ProviderUserID string
	UserID         pgtype.UUID
	AccessToken    *string
	RefreshToken   *string
	TokenExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) error {
	_, err := q.db.Exec(ctx, createIdentity,
		arg.Provider,
		arg.ProviderUserID,
		arg.UserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
insert into sessions (token_hash, user_id, expires_at)
values ($1, $2, $3)
`

type CreateSessionParams struct {
	TokenHash []byte
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
delete from sessions where expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
delete from sessions where token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getIdentity = `-- name: GetIdentity :one
select provider, provider_user_id, user_id, access_token, refresh_token, token_expires_at, created_at from identities where provider = $1 and provider_user_id = $2
`

type GetIdentityParams struct {
	Provider       string
	ProviderUserID string
}

func (q *Queries) GetIdentity(ctx context.Context, arg GetIdentityParams) (Identity, error) {
	row := q.db.QueryRow(ctx, getIdentity, arg.Provider, arg.ProviderUserID)
	var i Identity
	err := row.Scan(
		&i.Provider,
		&i.ProviderUserID,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionUser = `-- name: GetSessionUser :one
select u.id, u.display_name, u.avatar_url, u.ftp_watts, u.weight_kg, u.created_at, u.strava_upload, u.email, u.notify_planned, u.unsub_token, u.friend_code, u.avatar_preset
from sessions s
join users u on u.id = s.user_id
where s.token_hash = $1 and s.expires_at > now()
`

func (q *Queries) GetSessionUser(ctx context.Context, tokenHash []byte) (User, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.FtpWatts,
		&i.WeightKg,
		&i.CreatedAt,
		&i.StravaUpload,
		&i.Email,
		&i.NotifyPlanned,
		&i.UnsubToken,
		&i.FriendCode,
		&i.AvatarPreset,
	)
	return i, err
}

const getUserIdentity = `-- name: GetUserIdentity :one
select provider, provider_user_id, user_id, access_token, refresh_token, token_expires_at, created_at from identities where user_id = $1 and provider = $2
`

type GetUserIdentityParams struct {
	UserID   pgtype.UUID
	Provider string
}

func (q *Queries) GetUserIdentity(ctx context.Context, arg GetUserIdentityParams) (Identity, error) {
	row := q.db.QueryRow(ctx, getUserIdentity, arg.UserID, arg.Provider)
	var i Identity
	err := row.Scan(
		&i.Provider,
		&i.ProviderUserID,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listUserProviders = `-- name: ListUserProviders :many
select provider from identities where user_id = $1 order by created_at
`

func (q *Queries) ListUserProviders(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserProviders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var provider string
		if err := rows.Scan(&provider); err != nil {
			return nil, err
		}
		items = append(items, provider)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIdentityTokens = `-- name: UpdateIdentityTokens :exec
update identities
set access_token = $3, refresh_token = $4, token_expires_at = $5
where provider = $1 and provider_user_id = $2
`

type UpdateIdentityTokensParams struct {
	Provider       string
	ProviderUserID string
	AccessToken    *string
	RefreshToken   *string
	TokenExpiresAt pgtype.Timestamptz
}

func (q *Queries) UpdateIdentityTokens(ctx context.Context, arg UpdateIdentityTokensParams) error {
	_, err := q.db.Exec(ctx, updateIdentityTokens,
		arg.Provider,
		arg.ProviderUserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
	)
	return err
}
