// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blocks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const exportUserHiddenRiders = `-- name: ExportUserHiddenRiders :many
select u.display_name, b.created_at
from rider_blocks b
join users u on u.id = b.blocked_id
where b.blocker_id = $1
order by b.created_at
`

type ExportUserHiddenRidersRow struct {
	DisplayName string
	CreatedAt   pgtype.Timestamptz
}

// Mine to see in Settings, so mine to export — by name, like friends.json.
func (q *Queries) ExportUserHiddenRiders(ctx context.Context, blockerID pgtype.UUID) ([]ExportUserHiddenRidersRow, error) {
	rows, err := q.db.Query(ctx, exportUserHiddenRiders, blockerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportUserHiddenRidersRow
	for rows.Next() {
		var i ExportUserHiddenRidersRow
		if err := rows.Scan(&i.DisplayName, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hiddenBetween = `-- name: HiddenBetween :one

select exists (select 1 from rider_blocks v where v.blocker_id = $1::uuid and v.blocked_id = $2::uuid) as viewer_hid,
       exists (select 1 from rider_blocks o where o.blocker_id = $2::uuid and o.blocked_id = $1::uuid) as other_hid
`

type HiddenBetweenParams struct {
	Viewer pgtype.UUID
	Other  pgtype.UUID
}

type HiddenBetweenRow struct {
	ViewerHid bool
	OtherHid  bool
}

// an engineering bound (#1416), far past anyone's list
// Which way a pair is hidden, from `viewer`'s side: whether they hid the
// other, and whether the other hid them. The second is only ever acted on,
// never said.
func (q *Queries) HiddenBetween(ctx context.Context, arg HiddenBetweenParams) (HiddenBetweenRow, error) {
	row := q.db.QueryRow(ctx, hiddenBetween, arg.Viewer, arg.Other)
	var i HiddenBetweenRow
	err := row.Scan(&i.ViewerHid, &i.OtherHid)
	return i, err
}

const hideRider = `-- name: HideRider :one
with target as (select id from users where id = $1::uuid),
hidden as (
    insert into rider_blocks (blocker_id, blocked_id)
    select $2::uuid, id from target
    on conflict do nothing
)
select exists (select 1 from target)
`

type HideRiderParams struct {
	Blocked pgtype.UUID
	Blocker pgtype.UUID
}

// False: there is no such rider. Hiding twice is hiding once — the first
// row's time stands. Checked rather than left to the foreign key, so a
// stale id is an answer and not an ERROR in Postgres's log (#2685).
func (q *Queries) HideRider(ctx context.Context, arg HideRiderParams) (bool, error) {
	row := q.db.QueryRow(ctx, hideRider, arg.Blocked, arg.Blocker)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAllHiddenPairs = `-- name: ListAllHiddenPairs :many
select blocker_id, blocked_id from rider_blocks
`

type ListAllHiddenPairsRow struct {
	BlockerID pgtype.UUID
	BlockedID pgtype.UUID
}

// Every block, for the hub's in-memory copy at boot: cheers and pokes are
// sorted per socket on the tick, where a query per frame is not an option.
func (q *Queries) ListAllHiddenPairs(ctx context.Context) ([]ListAllHiddenPairsRow, error) {
	rows, err := q.db.Query(ctx, listAllHiddenPairs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllHiddenPairsRow
	for rows.Next() {
		var i ListAllHiddenPairsRow
		if err := rows.Scan(&i.BlockerID, &i.BlockedID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHiddenRiders = `-- name: ListHiddenRiders :many
select u.id, u.display_name, u.avatar_url, b.created_at
from rider_blocks b
join users u on u.id = b.blocked_id
where b.blocker_id = $1
order by b.created_at desc
limit 1000
`

type ListHiddenRidersRow struct {
	ID          pgtype.UUID
	DisplayName string
	AvatarUrl   *string
	CreatedAt   pgtype.Timestamptz
}

// The blocker's own list (Settings → Hidden riders), newest first. Never the
// other direction: who hid you is not yours to read.
func (q *Queries) ListHiddenRiders(ctx context.Context, blockerID pgtype.UUID) ([]ListHiddenRidersRow, error) {
	rows, err := q.db.Query(ctx, listHiddenRiders, blockerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHiddenRidersRow
	for rows.Next() {
		var i ListHiddenRidersRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unhideRider = `-- name: UnhideRider :execrows
delete from rider_blocks where blocker_id = $1 and blocked_id = $2
`

type UnhideRiderParams struct {
	BlockerID pgtype.UUID
	BlockedID pgtype.UUID
}

func (q *Queries) UnhideRider(ctx context.Context, arg UnhideRiderParams) (int64, error) {
	result, err := q.db.Exec(ctx, unhideRider, arg.BlockerID, arg.BlockedID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
