// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: board.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const boardClipBytes = `-- name: BoardClipBytes :one
select coalesce(sum(octet_length(bytes)), 0)::bigint from board_clips where user_id = $1
`

// The quota, asked before every upload. Postgres sums the lengths; the bytes
// themselves never leave the database for this.
func (q *Queries) BoardClipBytes(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, boardClipBytes, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const clearBoardKey = `-- name: ClearBoardKey :exec
update board_clips set key = null where user_id = $1 and key = $2
`

type ClearBoardKeyParams struct {
	UserID pgtype.UUID
	Key    *string
}

// The key moves rather than colliding, the same way a pad does.
func (q *Queries) ClearBoardKey(ctx context.Context, arg ClearBoardKeyParams) error {
	_, err := q.db.Exec(ctx, clearBoardKey, arg.UserID, arg.Key)
	return err
}

const clearBoardPad = `-- name: ClearBoardPad :exec
update board_clips set pad = null where user_id = $1 and pad = $2
`

type ClearBoardPadParams struct {
	UserID pgtype.UUID
	Pad    *int16
}

func (q *Queries) ClearBoardPad(ctx context.Context, arg ClearBoardPadParams) error {
	_, err := q.db.Exec(ctx, clearBoardPad, arg.UserID, arg.Pad)
	return err
}

const deleteBoardClip = `-- name: DeleteBoardClip :execrows
delete from board_clips where id = $1 and user_id = $2
`

type DeleteBoardClipParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteBoardClip(ctx context.Context, arg DeleteBoardClipParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBoardClip, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBoardClip = `-- name: GetBoardClip :one
select user_id, bytes from board_clips where id = $1
`

type GetBoardClipRow struct {
	UserID pgtype.UUID
	Bytes  []byte
}

// Serving is by clip id alone: a clip is personal, so the authorization is
// "does the listener share a room with the owner" and only the hub knows it.
func (q *Queries) GetBoardClip(ctx context.Context, id pgtype.UUID) (GetBoardClipRow, error) {
	row := q.db.QueryRow(ctx, getBoardClip, id)
	var i GetBoardClipRow
	err := row.Scan(&i.UserID, &i.Bytes)
	return i, err
}

const getBoardClipSource = `-- name: GetBoardClipSource :one
select duration_ms from board_clips where id = $1 and user_id = $2
`

type GetBoardClipSourceParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

// What the edit is validated against: the uploaded file's own length.
func (q *Queries) GetBoardClipSource(ctx context.Context, arg GetBoardClipSourceParams) (int32, error) {
	row := q.db.QueryRow(ctx, getBoardClipSource, arg.ID, arg.UserID)
	var duration_ms int32
	err := row.Scan(&duration_ms)
	return duration_ms, err
}

const listBoardClips = `-- name: ListBoardClips :many
select id, name, pad, key, duration_ms, octet_length(bytes)::int as size_bytes,
       start_ms, end_ms, gain_db, fade_in_ms, fade_out_ms, created_at
from board_clips
where user_id = $1
order by created_at desc
`

type ListBoardClipsRow struct {
	ID         pgtype.UUID
	Name       string
	Pad        *int16
	Key        *string
	DurationMs int32
	SizeBytes  int32
	StartMs    int32
	EndMs      int32
	GainDb     float32
	FadeInMs   int32
	FadeOutMs  int32
	CreatedAt  pgtype.Timestamptz
}

// The library, newest first. Never selects `bytes` — a listing that carried
// the audio would be the whole quota in one response.
func (q *Queries) ListBoardClips(ctx context.Context, userID pgtype.UUID) ([]ListBoardClipsRow, error) {
	rows, err := q.db.Query(ctx, listBoardClips, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBoardClipsRow
	for rows.Next() {
		var i ListBoardClipsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Pad,
			&i.Key,
			&i.DurationMs,
			&i.SizeBytes,
			&i.StartMs,
			&i.EndMs,
			&i.GainDb,
			&i.FadeInMs,
			&i.FadeOutMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveBoardClip = `-- name: SaveBoardClip :one
insert into board_clips (user_id, name, duration_ms, bytes, end_ms)
values ($1, $2, $3, $4, $5)
returning id, created_at
`

type SaveBoardClipParams struct {
	UserID     pgtype.UUID
	Name       string
	DurationMs int32
	Bytes      []byte
	EndMs      int32
}

type SaveBoardClipRow struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) SaveBoardClip(ctx context.Context, arg SaveBoardClipParams) (SaveBoardClipRow, error) {
	row := q.db.QueryRow(ctx, saveBoardClip,
		arg.UserID,
		arg.Name,
		arg.DurationMs,
		arg.Bytes,
		arg.EndMs,
	)
	var i SaveBoardClipRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const setBoardClipEdit = `-- name: SetBoardClipEdit :execrows
update board_clips
set start_ms = $3, end_ms = $4, gain_db = $5, fade_in_ms = $6, fade_out_ms = $7
where id = $1 and user_id = $2
`

type SetBoardClipEditParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	StartMs   int32
	EndMs     int32
	GainDb    float32
	FadeInMs  int32
	FadeOutMs int32
}

// The edit is numbers, never a re-encode: the source bytes stay as uploaded.
func (q *Queries) SetBoardClipEdit(ctx context.Context, arg SetBoardClipEditParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBoardClipEdit,
		arg.ID,
		arg.UserID,
		arg.StartMs,
		arg.EndMs,
		arg.GainDb,
		arg.FadeInMs,
		arg.FadeOutMs,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setBoardClipKey = `-- name: SetBoardClipKey :execrows
update board_clips set key = $3 where id = $1 and user_id = $2
`

type SetBoardClipKeyParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
	Key    *string
}

// Null clears the binding: a clip with no key is tapped, never fired blind.
func (q *Queries) SetBoardClipKey(ctx context.Context, arg SetBoardClipKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBoardClipKey, arg.ID, arg.UserID, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setBoardClipName = `-- name: SetBoardClipName :execrows
update board_clips set name = $3 where id = $1 and user_id = $2
`

type SetBoardClipNameParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
	Name   string
}

// A name is the rider's to change (#981). It was set once, from the uploaded
// file's stem, and there was no way to fix a bad one but to upload again.
func (q *Queries) SetBoardClipName(ctx context.Context, arg SetBoardClipNameParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBoardClipName, arg.ID, arg.UserID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setBoardClipPad = `-- name: SetBoardClipPad :execrows
update board_clips set pad = $3 where id = $1 and user_id = $2
`

type SetBoardClipPadParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
	Pad    *int16
}

// Assign or clear a pad. The unique index makes "the pad is taken" a conflict
// rather than a race, and the clip that was there is bumped to the library.
func (q *Queries) SetBoardClipPad(ctx context.Context, arg SetBoardClipPadParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBoardClipPad, arg.ID, arg.UserID, arg.Pad)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
