// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channels.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelPrivateChannelPlans = `-- name: CancelPrivateChannelPlans :many
delete from scheduled_sessions s
using channels c
where c.id = $1 and c.private and s.channel_id = c.id
returning s.workout_name, s.starts_at, s.started_at
`

type CancelPrivateChannelPlansRow struct {
	WorkoutName string
	StartsAt    pgtype.Timestamptz
	StartedAt   pgtype.Timestamptz
}

// A private channel's plans are its own (#2610), so they go before it does.
// The foreign key would null them into plans every member and the crew's
// shared feed can read. An open channel's plans keep their slot on the
// crew's schedule, with no channel.
func (q *Queries) CancelPrivateChannelPlans(ctx context.Context, id pgtype.UUID) ([]CancelPrivateChannelPlansRow, error) {
	rows, err := q.db.Query(ctx, cancelPrivateChannelPlans, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CancelPrivateChannelPlansRow
	for rows.Next() {
		var i CancelPrivateChannelPlansRow
		if err := rows.Scan(&i.WorkoutName, &i.StartsAt, &i.StartedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const channelAudience = `-- name: ChannelAudience :many
select user_id from visible_channels where channel_id = $1
`

// Who may enter one channel (`visible_channels`): the only riders a ping about
// its log may reach (#2821) — its activity is part of what its gate keeps.
func (q *Queries) ChannelAudience(ctx context.Context, channelID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, channelAudience, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createChannel = `-- name: CreateChannel :one
insert into channels (crew_id, kind, name, position, private)
select $1, $2, $3,
       coalesce((select max(position) + 1 from channels where crew_id = $1 and kind = $2), 0),
       $4
where (select count(*) from channels where crew_id = $1 and kind = $2) < $5::int
returning id, crew_id, kind, name, position, private, sound_pack, created_at, announcement_id, autoplay_enabled, autoplay_order, autoplay_playlist_id
`

type CreateChannelParams struct {
	CrewID      pgtype.UUID
	Kind        string
	Name        string
	Private     bool
	MaxChannels int32
}

// Bounded per crew and kind (protocol.MaxCrewTextChannels,
// MaxCrewVoiceChannels), and the bound is enforced HERE rather than by a
// read-then-insert in the handler — the CreateCrewPin shape: the count and the
// insert are one statement, and no row returned is the refusal. A new channel
// goes to the end of its list.
func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.CrewID,
		arg.Kind,
		arg.Name,
		arg.Private,
		arg.MaxChannels,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.CrewID,
		&i.Kind,
		&i.Name,
		&i.Position,
		&i.Private,
		&i.SoundPack,
		&i.CreatedAt,
		&i.AnnouncementID,
		&i.AutoplayEnabled,
		&i.AutoplayOrder,
		&i.AutoplayPlaylistID,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :exec
delete from channels where id = $1
`

// Takes its chat, its play log and its recaps with it (the cascades on
// channel_id): the client confirms first (errors.md), because none of that
// comes back.
func (q *Queries) DeleteChannel(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteChannel, id)
	return err
}

const getChannel = `-- name: GetChannel :one
select id, crew_id, kind, name, position, private, sound_pack, created_at, announcement_id, autoplay_enabled, autoplay_order, autoplay_playlist_id from channels where id = $1
`

func (q *Queries) GetChannel(ctx context.Context, id pgtype.UUID) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannel, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.CrewID,
		&i.Kind,
		&i.Name,
		&i.Position,
		&i.Private,
		&i.SoundPack,
		&i.CreatedAt,
		&i.AnnouncementID,
		&i.AutoplayEnabled,
		&i.AutoplayOrder,
		&i.AutoplayPlaylistID,
	)
	return i, err
}

const isCrewPlaylist = `-- name: IsCrewPlaylist :one
select exists (select 1 from playlists where id = $1 and crew_id = $2)
`

type IsCrewPlaylistParams struct {
	ID     pgtype.UUID
	CrewID pgtype.UUID
}

// A voice channel's autoplay plays one of ITS crew's playlists, never a
// rider's own or another crew's.
func (q *Queries) IsCrewPlaylist(ctx context.Context, arg IsCrewPlaylistParams) (bool, error) {
	row := q.db.QueryRow(ctx, isCrewPlaylist, arg.ID, arg.CrewID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isNamedInChannel = `-- name: IsNamedInChannel :one
select exists (select 1 from channel_members where channel_id = $1 and user_id = $2)
`

type IsNamedInChannelParams struct {
	ChannelID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) IsNamedInChannel(ctx context.Context, arg IsNamedInChannelParams) (bool, error) {
	row := q.db.QueryRow(ctx, isNamedInChannel, arg.ChannelID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listChannelIDsOfKind = `-- name: ListChannelIDsOfKind :many
select id from channels
where crew_id = $1 and kind = $2
order by position, created_at, id
`

type ListChannelIDsOfKindParams struct {
	CrewID pgtype.UUID
	Kind   string
}

func (q *Queries) ListChannelIDsOfKind(ctx context.Context, arg ListChannelIDsOfKindParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listChannelIDsOfKind, arg.CrewID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelMembers = `-- name: ListChannelMembers :many
select cm.channel_id, u.id, u.display_name, u.avatar_url
from channel_members cm
join channels c on c.id = cm.channel_id
join users u on u.id = cm.user_id
where c.crew_id = $1
order by u.display_name, u.id
`

type ListChannelMembersRow struct {
	ChannelID   pgtype.UUID
	ID          pgtype.UUID
	DisplayName string
	AvatarUrl   *string
}

// A private channel's named members, for the channels of one crew.
func (q *Queries) ListChannelMembers(ctx context.Context, crewID pgtype.UUID) ([]ListChannelMembersRow, error) {
	rows, err := q.db.Query(ctx, listChannelMembers, crewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelMembersRow
	for rows.Next() {
		var i ListChannelMembersRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.ID,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCrewChannels = `-- name: ListCrewChannels :many

select id, crew_id, kind, name, position, private, sound_pack, created_at, announcement_id, autoplay_enabled, autoplay_order, autoplay_playlist_id from channels
where crew_id = $1
order by kind = 'voice', position, created_at, id
`

// A crew's channels (ADR-0058, #2434): text channels and voice channels,
// furniture under the crew. The crew's owner and admins keep them; who may
// enter one is `channels.mayEnter`, asked of the rows these return — nothing
// here decides it.
// Text before voice, each in its own order — the sidebar's two lists. The id
// breaks a tie, so two reads agree on the order.
func (q *Queries) ListCrewChannels(ctx context.Context, crewID pgtype.UUID) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listCrewChannels, crewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.CrewID,
			&i.Kind,
			&i.Name,
			&i.Position,
			&i.Private,
			&i.SoundPack,
			&i.CreatedAt,
			&i.AnnouncementID,
			&i.AutoplayEnabled,
			&i.AutoplayOrder,
			&i.AutoplayPlaylistID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const movedRoom = `-- name: MovedRoom :one
select m.crew_id, t.channel_id as text_channel_id, v.channel_id as voice_channel_id
from moved_rooms m
left join visible_channels t on t.channel_id = m.text_channel_id and t.user_id = $1
left join visible_channels v on v.channel_id = m.voice_channel_id and v.user_id = $1
where m.slug = $2
`

type MovedRoomParams struct {
	Viewer pgtype.UUID
	Slug   string
}

type MovedRoomRow struct {
	CrewID         pgtype.UUID
	TextChannelID  pgtype.UUID
	VoiceChannelID pgtype.UUID
}

// Where an old room link lands now (#2446, #2458): the crew the room became
// part of and the two channels it became, from the table kept for exactly
// this (#2558): the rooms themselves are gone (#2433). A channel is named only
// to a viewer who may enter it (`visible_channels`, #2821): an old link is no
// key, and a private channel's id is part of what its gate keeps.
func (q *Queries) MovedRoom(ctx context.Context, arg MovedRoomParams) (MovedRoomRow, error) {
	row := q.db.QueryRow(ctx, movedRoom, arg.Viewer, arg.Slug)
	var i MovedRoomRow
	err := row.Scan(&i.CrewID, &i.TextChannelID, &i.VoiceChannelID)
	return i, err
}

const nameChannelMember = `-- name: NameChannelMember :exec
insert into channel_members (channel_id, user_id, added_by) values ($1, $2, $3)
on conflict (channel_id, user_id) do nothing
`

type NameChannelMemberParams struct {
	ChannelID pgtype.UUID
	UserID    pgtype.UUID
	AddedBy   pgtype.UUID
}

func (q *Queries) NameChannelMember(ctx context.Context, arg NameChannelMemberParams) error {
	_, err := q.db.Exec(ctx, nameChannelMember, arg.ChannelID, arg.UserID, arg.AddedBy)
	return err
}

const namedChannelsFor = `-- name: NamedChannelsFor :many
select cm.channel_id
from channel_members cm
join channels c on c.id = cm.channel_id
where c.crew_id = $1 and cm.user_id = $2
`

type NamedChannelsForParams struct {
	CrewID pgtype.UUID
	UserID pgtype.UUID
}

// The crew's private channels that name this rider.
func (q *Queries) NamedChannelsFor(ctx context.Context, arg NamedChannelsForParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, namedChannelsFor, arg.CrewID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var channel_id pgtype.UUID
		if err := rows.Scan(&channel_id); err != nil {
			return nil, err
		}
		items = append(items, channel_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setChannelPosition = `-- name: SetChannelPosition :exec
update channels set position = $2 where id = $1
`

type SetChannelPositionParams struct {
	ID       pgtype.UUID
	Position int32
}

func (q *Queries) SetChannelPosition(ctx context.Context, arg SetChannelPositionParams) error {
	_, err := q.db.Exec(ctx, setChannelPosition, arg.ID, arg.Position)
	return err
}

const unnameChannelMember = `-- name: UnnameChannelMember :exec
delete from channel_members where channel_id = $1 and user_id = $2
`

type UnnameChannelMemberParams struct {
	ChannelID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) UnnameChannelMember(ctx context.Context, arg UnnameChannelMemberParams) error {
	_, err := q.db.Exec(ctx, unnameChannelMember, arg.ChannelID, arg.UserID)
	return err
}

const updateChannel = `-- name: UpdateChannel :one
update channels
set name = $1, private = $2, sound_pack = $3,
    autoplay_enabled = $4, autoplay_order = $5,
    autoplay_playlist_id = $6
where id = $7
returning id, crew_id, kind, name, position, private, sound_pack, created_at, announcement_id, autoplay_enabled, autoplay_order, autoplay_playlist_id
`

type UpdateChannelParams struct {
	Name               string
	Private            bool
	SoundPack          string
	AutoplayEnabled    bool
	AutoplayOrder      string
	AutoplayPlaylistID pgtype.UUID
	ID                 pgtype.UUID
}

// Everything a PATCH may change, written whole: the handler merges the
// request into the row it read. Position is not here — ReorderChannel owns it.
func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, updateChannel,
		arg.Name,
		arg.Private,
		arg.SoundPack,
		arg.AutoplayEnabled,
		arg.AutoplayOrder,
		arg.AutoplayPlaylistID,
		arg.ID,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.CrewID,
		&i.Kind,
		&i.Name,
		&i.Position,
		&i.Private,
		&i.SoundPack,
		&i.CreatedAt,
		&i.AnnouncementID,
		&i.AutoplayEnabled,
		&i.AutoplayOrder,
		&i.AutoplayPlaylistID,
	)
	return i, err
}

const voiceChannelsVisibleTo = `-- name: VoiceChannelsVisibleTo :many
select c.id as channel_id, c.name as channel_name, cw.id as crew_id, cw.name as crew_name
from channels c
join crews cw on cw.id = c.crew_id
join visible_channels v on v.channel_id = c.id and v.user_id = $1
where c.id = any($2::uuid[]) and c.kind = 'voice'
`

type VoiceChannelsVisibleToParams struct {
	Viewer     pgtype.UUID
	ChannelIds []pgtype.UUID
}

type VoiceChannelsVisibleToRow struct {
	ChannelID   pgtype.UUID
	ChannelName string
	CrewID      pgtype.UUID
	CrewName    string
}

// Which of these voice channels the viewer may enter, with the crew each
// belongs to: where a friend is, as the friends panel and a rider's page may
// say it (#2516). The hub names the channel; this names it only through
// `visible_channels` — `mayEnter` as one relation, the rule the crew's live
// read applies — so a channel the viewer may not enter is not in the answer
// at all. Its name and its crew are part of what its gate keeps (ADR-0012:
// friendship never pierces the boundary). One query for every channel asked
// about, however many friends are online (#687).
func (q *Queries) VoiceChannelsVisibleTo(ctx context.Context, arg VoiceChannelsVisibleToParams) ([]VoiceChannelsVisibleToRow, error) {
	rows, err := q.db.Query(ctx, voiceChannelsVisibleTo, arg.Viewer, arg.ChannelIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VoiceChannelsVisibleToRow
	for rows.Next() {
		var i VoiceChannelsVisibleToRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.ChannelName,
			&i.CrewID,
			&i.CrewName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
