// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channel_chat.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addChannelReaction = `-- name: AddChannelReaction :execrows
insert into chat_reactions (message_id, user_id, emoji)
select $1, $2, $3
where exists (select 1 from chat_messages where id = $1 and channel_id = $4)
on conflict do nothing
`

type AddChannelReactionParams struct {
	MessageID pgtype.UUID
	UserID    pgtype.UUID
	Emoji     string
	ChannelID pgtype.UUID
}

func (q *Queries) AddChannelReaction(ctx context.Context, arg AddChannelReactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, addChannelReaction,
		arg.MessageID,
		arg.UserID,
		arg.Emoji,
		arg.ChannelID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const chatImageInChannel = `-- name: ChatImageInChannel :one
select exists(select 1 from chat_images where id = $1 and channel_id = $2)::boolean
`

type ChatImageInChannelParams struct {
	ID        pgtype.UUID
	ChannelID pgtype.UUID
}

func (q *Queries) ChatImageInChannel(ctx context.Context, arg ChatImageInChannelParams) (bool, error) {
	row := q.db.QueryRow(ctx, chatImageInChannel, arg.ID, arg.ChannelID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const clearChannelAnnouncement = `-- name: ClearChannelAnnouncement :exec
update channels set announcement_id = null where id = $1
`

func (q *Queries) ClearChannelAnnouncement(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearChannelAnnouncement, id)
	return err
}

const deleteChannelMessage = `-- name: DeleteChannelMessage :execrows
delete from chat_messages where id = $1 and channel_id = $2
`

type DeleteChannelMessageParams struct {
	ID        pgtype.UUID
	ChannelID pgtype.UUID
}

// Reactions cascade, the picture is swept on the grace, and an announcement
// pointing at it is nulled by the FK (#2417).
func (q *Queries) DeleteChannelMessage(ctx context.Context, arg DeleteChannelMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannelMessage, arg.ID, arg.ChannelID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredChat = `-- name: DeleteExpiredChat :execrows
delete from chat_messages
where id in (
    select id from chat_messages
    where expires_at <= now()
    limit 10000
)
`

// Temporary lines whose timer ran out (#2644), a batch at a time; reactions
// cascade and a picture is swept with the orphans.
func (q *Queries) DeleteExpiredChat(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredChat)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const editChannelMessage = `-- name: EditChannelMessage :one
update chat_messages
set text = $1, edited_at = now()
where id = $2 and channel_id = $3 and user_id = $4
returning edited_at
`

type EditChannelMessageParams struct {
	Text      string
	ID        pgtype.UUID
	ChannelID pgtype.UUID
	UserID    pgtype.UUID
}

// Only the author, only the text (#865); the scope repeated, not trusted.
func (q *Queries) EditChannelMessage(ctx context.Context, arg EditChannelMessageParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, editChannelMessage,
		arg.Text,
		arg.ID,
		arg.ChannelID,
		arg.UserID,
	)
	var edited_at pgtype.Timestamptz
	err := row.Scan(&edited_at)
	return edited_at, err
}

const getChannelAnnouncement = `-- name: GetChannelAnnouncement :one
select m.id, m.text, u.display_name as from_name, m.created_at
from channels c
join chat_messages m on m.id = c.announcement_id
join users u on u.id = m.user_id
where c.id = $1
`

type GetChannelAnnouncementRow struct {
	ID        pgtype.UUID
	Text      string
	FromName  string
	CreatedAt pgtype.Timestamptz
}

// The author is the message's, not whoever marked it.
func (q *Queries) GetChannelAnnouncement(ctx context.Context, id pgtype.UUID) (GetChannelAnnouncementRow, error) {
	row := q.db.QueryRow(ctx, getChannelAnnouncement, id)
	var i GetChannelAnnouncementRow
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.FromName,
		&i.CreatedAt,
	)
	return i, err
}

const getChannelImage = `-- name: GetChannelImage :one
select mime, bytes from chat_images
where id = $1 and channel_id = $2
`

type GetChannelImageParams struct {
	ID        pgtype.UUID
	ChannelID pgtype.UUID
}

type GetChannelImageRow struct {
	Mime  string
	Bytes []byte
}

func (q *Queries) GetChannelImage(ctx context.Context, arg GetChannelImageParams) (GetChannelImageRow, error) {
	row := q.db.QueryRow(ctx, getChannelImage, arg.ID, arg.ChannelID)
	var i GetChannelImageRow
	err := row.Scan(&i.Mime, &i.Bytes)
	return i, err
}

const getChannelMessage = `-- name: GetChannelMessage :one
select user_id, text, image_id from chat_messages
where id = $1 and channel_id = $2
  and (expires_at is null or expires_at > now())
`

type GetChannelMessageParams struct {
	ID        pgtype.UUID
	ChannelID pgtype.UUID
}

type GetChannelMessageRow struct {
	UserID  pgtype.UUID
	Text    string
	ImageID pgtype.UUID
}

func (q *Queries) GetChannelMessage(ctx context.Context, arg GetChannelMessageParams) (GetChannelMessageRow, error) {
	row := q.db.QueryRow(ctx, getChannelMessage, arg.ID, arg.ChannelID)
	var i GetChannelMessageRow
	err := row.Scan(&i.UserID, &i.Text, &i.ImageID)
	return i, err
}

const getChannelReadAt = `-- name: GetChannelReadAt :one
select read_at from channel_reads where channel_id = $1 and user_id = $2
`

type GetChannelReadAtParams struct {
	ChannelID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) GetChannelReadAt(ctx context.Context, arg GetChannelReadAtParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getChannelReadAt, arg.ChannelID, arg.UserID)
	var read_at pgtype.Timestamptz
	err := row.Scan(&read_at)
	return read_at, err
}

const listChannelChat = `-- name: ListChannelChat :many
select m.id, m.user_id, u.display_name, m.text, m.image_id, m.created_at, m.edited_at, m.expires_at
from (
    select id, user_id, text, image_id, created_at, edited_at, expires_at from chat_messages
    where channel_id = $1
      and (expires_at is null or expires_at > now())
    order by created_at desc, id desc
    limit $2
) m
join users u on u.id = m.user_id
order by m.created_at, m.id
`

type ListChannelChatParams struct {
	ChannelID pgtype.UUID
	Limit     int32
}

type ListChannelChatRow struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	DisplayName string
	Text        string
	ImageID     pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	EditedAt    pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
}

// Newest $2, oldest first for rendering; the id breaks a same-millisecond tie.
// A line whose timer ran out is gone to every reader at once (#2644), not at
// the next sweep.
func (q *Queries) ListChannelChat(ctx context.Context, arg ListChannelChatParams) ([]ListChannelChatRow, error) {
	rows, err := q.db.Query(ctx, listChannelChat, arg.ChannelID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelChatRow
	for rows.Next() {
		var i ListChannelChatRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.Text,
			&i.ImageID,
			&i.CreatedAt,
			&i.EditedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelReactions = `-- name: ListChannelReactions :many
select r.message_id, r.emoji,
       count(*) as total,
       bool_or(r.user_id = $1) as mine
from chat_reactions r
join chat_messages m on m.id = r.message_id
where m.channel_id = $2
group by r.message_id, r.emoji
`

type ListChannelReactionsParams struct {
	Viewer    pgtype.UUID
	ChannelID pgtype.UUID
}

type ListChannelReactionsRow struct {
	MessageID pgtype.UUID
	Emoji     string
	Total     int64
	Mine      bool
}

func (q *Queries) ListChannelReactions(ctx context.Context, arg ListChannelReactionsParams) ([]ListChannelReactionsRow, error) {
	rows, err := q.db.Query(ctx, listChannelReactions, arg.Viewer, arg.ChannelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelReactionsRow
	for rows.Next() {
		var i ListChannelReactionsRow
		if err := rows.Scan(
			&i.MessageID,
			&i.Emoji,
			&i.Total,
			&i.Mine,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChannelRead = `-- name: MarkChannelRead :exec
insert into channel_reads (channel_id, user_id, read_at)
values ($1, $2, now())
on conflict (channel_id, user_id) do update set read_at = now()
`

type MarkChannelReadParams struct {
	ChannelID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) MarkChannelRead(ctx context.Context, arg MarkChannelReadParams) error {
	_, err := q.db.Exec(ctx, markChannelRead, arg.ChannelID, arg.UserID)
	return err
}

const newestCrewAnnouncement = `-- name: NewestCrewAnnouncement :one
select c.id as channel_id, c.name as channel_name, m.id, m.text, u.display_name as from_name, m.created_at
from channels c
join chat_messages m on m.id = c.announcement_id
join users u on u.id = m.user_id
where c.crew_id = $1 and c.kind = 'text'
  and ($2::boolean or not c.private
       or exists (select 1 from channel_members cm where cm.channel_id = c.id and cm.user_id = $3))
order by m.created_at desc
limit 1
`

type NewestCrewAnnouncementParams struct {
	CrewID pgtype.UUID
	Admin  bool
	Viewer pgtype.UUID
}

type NewestCrewAnnouncementRow struct {
	ChannelID   pgtype.UUID
	ChannelName string
	ID          pgtype.UUID
	Text        string
	FromName    string
	CreatedAt   pgtype.Timestamptz
}

// What the crew's Board leads with (ADR-0058): the newest announcement across
// its text channels — of those the viewer may enter, `channels.mayEnter`'s
// rule restated because it filters rows. The handler has proved the viewer
// an unbanned member; `admin` is the owner or an admin.
func (q *Queries) NewestCrewAnnouncement(ctx context.Context, arg NewestCrewAnnouncementParams) (NewestCrewAnnouncementRow, error) {
	row := q.db.QueryRow(ctx, newestCrewAnnouncement, arg.CrewID, arg.Admin, arg.Viewer)
	var i NewestCrewAnnouncementRow
	err := row.Scan(
		&i.ChannelID,
		&i.ChannelName,
		&i.ID,
		&i.Text,
		&i.FromName,
		&i.CreatedAt,
	)
	return i, err
}

const pruneChannelChat = `-- name: PruneChannelChat :exec
delete from chat_messages cm
where cm.channel_id = $1
  and cm.id is distinct from (select announcement_id from channels where id = $1)
  and cm.id not in (
    select keep.id from (
        select id from chat_messages
        where channel_id = $1
        order by created_at desc
        limit 500
    ) keep
)
`

// The 500-message bound per text channel (docs/SPEC.md), keeping the
// channel's announcement whatever its age (ADR-0057).
func (q *Queries) PruneChannelChat(ctx context.Context, channelID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, pruneChannelChat, channelID)
	return err
}

const pruneChannelImages = `-- name: PruneChannelImages :exec
delete from chat_images i
where i.channel_id = $1
  and i.created_at < now() - interval '15 minutes'
  and not exists (select 1 from chat_messages m where m.image_id = i.id)
`

// The room's sweep, per channel: an image outlives neither its message nor a
// 15-minute grace for an upload still awaiting its send.
func (q *Queries) PruneChannelImages(ctx context.Context, channelID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, pruneChannelImages, channelID)
	return err
}

const removeChannelReaction = `-- name: RemoveChannelReaction :execrows
delete from chat_reactions r
using chat_messages m
where r.message_id = $1 and r.user_id = $2 and r.emoji = $3
  and m.id = r.message_id and m.channel_id = $4
`

type RemoveChannelReactionParams struct {
	MessageID pgtype.UUID
	UserID    pgtype.UUID
	Emoji     string
	ChannelID pgtype.UUID
}

func (q *Queries) RemoveChannelReaction(ctx context.Context, arg RemoveChannelReactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeChannelReaction,
		arg.MessageID,
		arg.UserID,
		arg.Emoji,
		arg.ChannelID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveChannelImage = `-- name: SaveChannelImage :one
insert into chat_images (channel_id, user_id, mime, bytes)
values ($1, $2, $3, $4) returning id
`

type SaveChannelImageParams struct {
	ChannelID pgtype.UUID
	UserID    pgtype.UUID
	Mime      string
	Bytes     []byte
}

func (q *Queries) SaveChannelImage(ctx context.Context, arg SaveChannelImageParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, saveChannelImage,
		arg.ChannelID,
		arg.UserID,
		arg.Mime,
		arg.Bytes,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const saveChannelMessage = `-- name: SaveChannelMessage :one

insert into chat_messages (channel_id, user_id, text, image_id, created_at, expires_at)
select $1, $2, $3, $4, $5, $6::timestamptz
where $4::uuid is null
   or exists (select 1 from chat_images where id = $4 and channel_id = $1)
returning id
`

type SaveChannelMessageParams struct {
	ChannelID pgtype.UUID
	UserID    pgtype.UUID
	Text      string
	ImageID   pgtype.UUID
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

// A text channel's chat (ADR-0058, #2435): what the room's chat queries were,
// keyed on the channel.
// Every statement is scoped by the channel, which is the privacy boundary now:
// an id from another channel's log is not a line here.
// An attached image must be THIS channel's, for the room's reason: a foreign
// id would pin its bytes past the sweep.
func (q *Queries) SaveChannelMessage(ctx context.Context, arg SaveChannelMessageParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, saveChannelMessage,
		arg.ChannelID,
		arg.UserID,
		arg.Text,
		arg.ImageID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const setChannelAnnouncement = `-- name: SetChannelAnnouncement :execrows
update channels c set announcement_id = $1
where c.id = $2 and c.kind = 'text'
  and exists (select 1 from chat_messages m where m.id = $1 and m.channel_id = $2)
`

type SetChannelAnnouncementParams struct {
	MessageID pgtype.UUID
	ChannelID pgtype.UUID
}

// One per text channel (ADR-0057 as amended by ADR-0058). The message must be
// this channel's; 0 rows is the 404.
func (q *Queries) SetChannelAnnouncement(ctx context.Context, arg SetChannelAnnouncementParams) (int64, error) {
	result, err := q.db.Exec(ctx, setChannelAnnouncement, arg.MessageID, arg.ChannelID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
