// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addChatReaction = `-- name: AddChatReaction :execrows
insert into chat_reactions (message_id, user_id, emoji)
select $1, $2, $3
where exists (select 1 from chat_messages where id = $1 and room_id = $4)
on conflict do nothing
`

type AddChatReactionParams struct {
	MessageID pgtype.UUID
	UserID    pgtype.UUID
	Emoji     string
	RoomID    pgtype.UUID
}

// Toggle half 1: no-op when already reacted (the conflict), so the caller
// knows to remove instead.
func (q *Queries) AddChatReaction(ctx context.Context, arg AddChatReactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, addChatReaction,
		arg.MessageID,
		arg.UserID,
		arg.Emoji,
		arg.RoomID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countChatReaction = `-- name: CountChatReaction :one
select count(*) from chat_reactions where message_id = $1 and emoji = $2
`

type CountChatReactionParams struct {
	MessageID pgtype.UUID
	Emoji     string
}

func (q *Queries) CountChatReaction(ctx context.Context, arg CountChatReactionParams) (int64, error) {
	row := q.db.QueryRow(ctx, countChatReaction, arg.MessageID, arg.Emoji)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listChatReactions = `-- name: ListChatReactions :many
select r.message_id, r.emoji,
       count(*) as total,
       bool_or(r.user_id = $2) as mine
from chat_reactions r
join chat_messages m on m.id = r.message_id
where m.room_id = $1
group by r.message_id, r.emoji
`

type ListChatReactionsParams struct {
	RoomID pgtype.UUID
	UserID pgtype.UUID
}

type ListChatReactionsRow struct {
	MessageID pgtype.UUID
	Emoji     string
	Total     int64
	Mine      bool
}

// Counts per message+emoji for the backlog, plus whether the viewer is in.
func (q *Queries) ListChatReactions(ctx context.Context, arg ListChatReactionsParams) ([]ListChatReactionsRow, error) {
	rows, err := q.db.Query(ctx, listChatReactions, arg.RoomID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatReactionsRow
	for rows.Next() {
		var i ListChatReactionsRow
		if err := rows.Scan(
			&i.MessageID,
			&i.Emoji,
			&i.Total,
			&i.Mine,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomChat = `-- name: ListRoomChat :many
select m.id, u.display_name, m.text, m.created_at
from (
    select id, room_id, user_id, text, created_at from chat_messages
    where room_id = $1
    order by created_at desc
    limit $2
) m
join users u on u.id = m.user_id
order by m.created_at
`

type ListRoomChatParams struct {
	RoomID pgtype.UUID
	Limit  int32
}

type ListRoomChatRow struct {
	ID          pgtype.UUID
	DisplayName string
	Text        string
	CreatedAt   pgtype.Timestamptz
}

// Newest $2, oldest-first for rendering; a deleted author's rows are gone
// (cascade), so the join never dangles.
func (q *Queries) ListRoomChat(ctx context.Context, arg ListRoomChatParams) ([]ListRoomChatRow, error) {
	rows, err := q.db.Query(ctx, listRoomChat, arg.RoomID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomChatRow
	for rows.Next() {
		var i ListRoomChatRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneChat = `-- name: PruneChat :exec
delete from chat_messages cm
where cm.room_id = $1 and cm.id not in (
    select keep.id from (
        select id from chat_messages
        where room_id = $1
        order by created_at desc
        limit 500
    ) keep
)
`

// The 500-message bound (ADR-0010 amended) — run on write, the log never grows.
func (q *Queries) PruneChat(ctx context.Context, roomID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, pruneChat, roomID)
	return err
}

const removeChatReaction = `-- name: RemoveChatReaction :execrows
delete from chat_reactions r
using chat_messages m
where r.message_id = $1 and r.user_id = $2 and r.emoji = $3
  and m.id = r.message_id and m.room_id = $4
`

type RemoveChatReactionParams struct {
	MessageID pgtype.UUID
	UserID    pgtype.UUID
	Emoji     string
	RoomID    pgtype.UUID
}

// Room-scoped like the insert — a socket in room A must not toggle
// reactions on room B's messages (audit #219).
func (q *Queries) RemoveChatReaction(ctx context.Context, arg RemoveChatReactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeChatReaction,
		arg.MessageID,
		arg.UserID,
		arg.Emoji,
		arg.RoomID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveChatMessage = `-- name: SaveChatMessage :one
insert into chat_messages (room_id, user_id, text)
values ($1, $2, $3) returning id
`

type SaveChatMessageParams struct {
	RoomID pgtype.UUID
	UserID pgtype.UUID
	Text   string
}

func (q *Queries) SaveChatMessage(ctx context.Context, arg SaveChatMessageParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, saveChatMessage, arg.RoomID, arg.UserID, arg.Text)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
