// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listDmHeads = `-- name: ListDmHeads :many
select distinct on (peer.id)
    peer.id as peer_id, peer.display_name, peer.avatar_url, peer.avatar_preset,
    (select coalesce(sum(xp), 0) from rides r where r.user_id = peer.id)::bigint as total_xp,
    m.text, m.sender_id, m.created_at
from dm_messages m
join users peer
  on peer.id = case when m.sender_id = $1 then m.recipient_id else m.sender_id end
where m.sender_id = $1 or m.recipient_id = $1
order by peer.id, m.created_at desc
`

type ListDmHeadsRow struct {
	PeerID       pgtype.UUID
	DisplayName  string
	AvatarUrl    *string
	AvatarPreset *string
	TotalXp      int64
	Text         string
	SenderID     pgtype.UUID
	CreatedAt    pgtype.Timestamptz
}

// The conversation list: my peers with their latest line, newest first.
func (q *Queries) ListDmHeads(ctx context.Context, senderID pgtype.UUID) ([]ListDmHeadsRow, error) {
	rows, err := q.db.Query(ctx, listDmHeads, senderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDmHeadsRow
	for rows.Next() {
		var i ListDmHeadsRow
		if err := rows.Scan(
			&i.PeerID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.AvatarPreset,
			&i.TotalXp,
			&i.Text,
			&i.SenderID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDms = `-- name: ListDms :many
select m.id, m.sender_id, m.text, m.created_at
from dm_messages m
where least(m.sender_id, m.recipient_id) = least($1::uuid, $2::uuid)
  and greatest(m.sender_id, m.recipient_id) = greatest($1::uuid, $2::uuid)
  and m.created_at > $3
order by m.created_at
limit 200
`

type ListDmsParams struct {
	Column1   pgtype.UUID
	Column2   pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type ListDmsRow struct {
	ID        pgtype.UUID
	SenderID  pgtype.UUID
	Text      string
	CreatedAt pgtype.Timestamptz
}

// One pair's thread, oldest-first; `after` narrows a poll to the new tail.
func (q *Queries) ListDms(ctx context.Context, arg ListDmsParams) ([]ListDmsRow, error) {
	rows, err := q.db.Query(ctx, listDms, arg.Column1, arg.Column2, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDmsRow
	for rows.Next() {
		var i ListDmsRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneDms = `-- name: PruneDms :exec
delete from dm_messages dm
where least(dm.sender_id, dm.recipient_id) = least($1::uuid, $2::uuid)
  and greatest(dm.sender_id, dm.recipient_id) = greatest($1::uuid, $2::uuid)
  and dm.id not in (
    select keep.id from (
        select id from dm_messages
        where least(sender_id, recipient_id) = least($1::uuid, $2::uuid)
          and greatest(sender_id, recipient_id) = greatest($1::uuid, $2::uuid)
        order by created_at desc
        limit 500
    ) keep
)
`

type PruneDmsParams struct {
	Column1 pgtype.UUID
	Column2 pgtype.UUID
}

// The 500-message bound per pair, pruned on write like room chat.
func (q *Queries) PruneDms(ctx context.Context, arg PruneDmsParams) error {
	_, err := q.db.Exec(ctx, pruneDms, arg.Column1, arg.Column2)
	return err
}

const sendDm = `-- name: SendDm :one
insert into dm_messages (sender_id, recipient_id, text)
select $1, $2, $3
where exists (
    select 1 from friendships f
    where f.status = 'accepted'
      and ((f.requester_id = $1 and f.addressee_id = $2)
        or (f.requester_id = $2 and f.addressee_id = $1))
)
returning id, created_at
`

type SendDmParams struct {
	SenderID    pgtype.UUID
	RecipientID pgtype.UUID
	Text        string
}

type SendDmRow struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

// The friendship row IS the permission (ADR-0012 amended): no accepted
// friendship, no insert — the caller reads zero rows back and refuses.
func (q *Queries) SendDm(ctx context.Context, arg SendDmParams) (SendDmRow, error) {
	row := q.db.QueryRow(ctx, sendDm, arg.SenderID, arg.RecipientID, arg.Text)
	var i SendDmRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
