// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addDmReaction = `-- name: AddDmReaction :execrows
insert into dm_reactions (message_id, user_id, emoji)
select $1, $2, $3
where exists (
    select 1 from dm_messages
    where id = $1
      and least(sender_id, recipient_id) = least($4::uuid, $5::uuid)
      and greatest(sender_id, recipient_id) = greatest($4::uuid, $5::uuid)
)
on conflict do nothing
`

type AddDmReactionParams struct {
	MessageID pgtype.UUID
	UserID    pgtype.UUID
	Emoji     string
	Column4   pgtype.UUID
	Column5   pgtype.UUID
}

// Toggle half 1: no-op when already reacted (the conflict), so the caller
// knows to remove instead. Scoped to the message's own pair — no separate
// friendship recheck, same as viewing a delivered image (GetDmImage):
// unfriending ends new sends, it does not black out reacting to history.
func (q *Queries) AddDmReaction(ctx context.Context, arg AddDmReactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, addDmReaction,
		arg.MessageID,
		arg.UserID,
		arg.Emoji,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countDmReaction = `-- name: CountDmReaction :one
select count(*) from dm_reactions where message_id = $1 and emoji = $2
`

type CountDmReactionParams struct {
	MessageID pgtype.UUID
	Emoji     string
}

func (q *Queries) CountDmReaction(ctx context.Context, arg CountDmReactionParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDmReaction, arg.MessageID, arg.Emoji)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDmImage = `-- name: GetDmImage :one
select mime, bytes from dm_images
where id = $1
  and (sender_id = $2 or recipient_id = $2)
`

type GetDmImageParams struct {
	ImageID  pgtype.UUID
	ViewerID pgtype.UUID
}

type GetDmImageRow struct {
	Mime  string
	Bytes []byte
}

// The row's own pair is the permission: readable by its sender or recipient,
// nobody else — no friendship re-check, an unfriending must not black out
// pictures already delivered.
func (q *Queries) GetDmImage(ctx context.Context, arg GetDmImageParams) (GetDmImageRow, error) {
	row := q.db.QueryRow(ctx, getDmImage, arg.ImageID, arg.ViewerID)
	var i GetDmImageRow
	err := row.Scan(&i.Mime, &i.Bytes)
	return i, err
}

const listDmHeads = `-- name: ListDmHeads :many
select distinct on (peer.id)
    peer.id as peer_id, peer.display_name, peer.avatar_url, peer.avatar_preset,
    user_total_xp(peer.id)::bigint as total_xp,
    m.text, m.image_id, m.sender_id, m.created_at
from dm_messages m
join users peer
  on peer.id = case when m.sender_id = $1 then m.recipient_id else m.sender_id end
where m.sender_id = $1 or m.recipient_id = $1
order by peer.id, m.created_at desc
`

type ListDmHeadsRow struct {
	PeerID       pgtype.UUID
	DisplayName  string
	AvatarUrl    *string
	AvatarPreset *string
	TotalXp      int64
	Text         string
	ImageID      pgtype.UUID
	SenderID     pgtype.UUID
	CreatedAt    pgtype.Timestamptz
}

// The conversation list: my peers with their latest line, newest first.
func (q *Queries) ListDmHeads(ctx context.Context, senderID pgtype.UUID) ([]ListDmHeadsRow, error) {
	rows, err := q.db.Query(ctx, listDmHeads, senderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDmHeadsRow
	for rows.Next() {
		var i ListDmHeadsRow
		if err := rows.Scan(
			&i.PeerID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.AvatarPreset,
			&i.TotalXp,
			&i.Text,
			&i.ImageID,
			&i.SenderID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDmReactions = `-- name: ListDmReactions :many
select r.message_id, r.emoji,
       count(*) as total,
       bool_or(r.user_id = $3) as mine
from dm_reactions r
join dm_messages m on m.id = r.message_id
where least(m.sender_id, m.recipient_id) = least($1::uuid, $2::uuid)
  and greatest(m.sender_id, m.recipient_id) = greatest($1::uuid, $2::uuid)
group by r.message_id, r.emoji
`

type ListDmReactionsParams struct {
	Column1 pgtype.UUID
	Column2 pgtype.UUID
	UserID  pgtype.UUID
}

type ListDmReactionsRow struct {
	MessageID pgtype.UUID
	Emoji     string
	Total     int64
	Mine      bool
}

// Counts per message+emoji for the whole pair, plus whether the viewer is
// in — like ListChatReactions, but pair-scoped instead of room-scoped since
// a DM message already carries its own two participants.
func (q *Queries) ListDmReactions(ctx context.Context, arg ListDmReactionsParams) ([]ListDmReactionsRow, error) {
	rows, err := q.db.Query(ctx, listDmReactions, arg.Column1, arg.Column2, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDmReactionsRow
	for rows.Next() {
		var i ListDmReactionsRow
		if err := rows.Scan(
			&i.MessageID,
			&i.Emoji,
			&i.Total,
			&i.Mine,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDms = `-- name: ListDms :many
select m.id, m.sender_id, m.text, m.image_id, m.created_at
from dm_messages m
where least(m.sender_id, m.recipient_id) = least($1::uuid, $2::uuid)
  and greatest(m.sender_id, m.recipient_id) = greatest($1::uuid, $2::uuid)
  and m.created_at > $3
order by m.created_at
limit 200
`

type ListDmsParams struct {
	Column1   pgtype.UUID
	Column2   pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type ListDmsRow struct {
	ID        pgtype.UUID
	SenderID  pgtype.UUID
	Text      string
	ImageID   pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

// One pair's thread, oldest-first; `after` narrows a poll to the new tail.
func (q *Queries) ListDms(ctx context.Context, arg ListDmsParams) ([]ListDmsRow, error) {
	rows, err := q.db.Query(ctx, listDms, arg.Column1, arg.Column2, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDmsRow
	for rows.Next() {
		var i ListDmsRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.Text,
			&i.ImageID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneDmImages = `-- name: PruneDmImages :exec
delete from dm_images i
where least(i.sender_id, i.recipient_id) = least($1::uuid, $2::uuid)
  and greatest(i.sender_id, i.recipient_id) = greatest($1::uuid, $2::uuid)
  and i.created_at < now() - interval '15 minutes'
  and not exists (
      select 1 from dm_messages m where m.image_id = i.id
  )
`

type PruneDmImagesParams struct {
	Column1 pgtype.UUID
	Column2 pgtype.UUID
}

// Swept with the pair's 500-message bound: an image outlives neither its
// message nor a 15-minute grace for uploads still awaiting their send.
func (q *Queries) PruneDmImages(ctx context.Context, arg PruneDmImagesParams) error {
	_, err := q.db.Exec(ctx, pruneDmImages, arg.Column1, arg.Column2)
	return err
}

const pruneDms = `-- name: PruneDms :exec
delete from dm_messages dm
where least(dm.sender_id, dm.recipient_id) = least($1::uuid, $2::uuid)
  and greatest(dm.sender_id, dm.recipient_id) = greatest($1::uuid, $2::uuid)
  and dm.id not in (
    select keep.id from (
        select id from dm_messages
        where least(sender_id, recipient_id) = least($1::uuid, $2::uuid)
          and greatest(sender_id, recipient_id) = greatest($1::uuid, $2::uuid)
        order by created_at desc
        limit 500
    ) keep
)
`

type PruneDmsParams struct {
	Column1 pgtype.UUID
	Column2 pgtype.UUID
}

// The 500-message bound per pair, pruned on write like room chat.
func (q *Queries) PruneDms(ctx context.Context, arg PruneDmsParams) error {
	_, err := q.db.Exec(ctx, pruneDms, arg.Column1, arg.Column2)
	return err
}

const removeDmReaction = `-- name: RemoveDmReaction :execrows
delete from dm_reactions r
using dm_messages m
where r.message_id = $1 and r.user_id = $2 and r.emoji = $3
  and m.id = r.message_id
  and least(m.sender_id, m.recipient_id) = least($4::uuid, $5::uuid)
  and greatest(m.sender_id, m.recipient_id) = greatest($4::uuid, $5::uuid)
`

type RemoveDmReactionParams struct {
	MessageID pgtype.UUID
	UserID    pgtype.UUID
	Emoji     string
	Column4   pgtype.UUID
	Column5   pgtype.UUID
}

// Pair-scoped like the insert.
func (q *Queries) RemoveDmReaction(ctx context.Context, arg RemoveDmReactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeDmReaction,
		arg.MessageID,
		arg.UserID,
		arg.Emoji,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveDmImage = `-- name: SaveDmImage :one
insert into dm_images (sender_id, recipient_id, mime, bytes)
select $1, $2, $3, $4
where exists (
    select 1 from friendships f
    where f.status = 'accepted'
      and ((f.requester_id = $1 and f.addressee_id = $2)
        or (f.requester_id = $2 and f.addressee_id = $1))
)
returning id
`

type SaveDmImageParams struct {
	SenderID    pgtype.UUID
	RecipientID pgtype.UUID
	Mime        string
	Bytes       []byte
}

// Gated identically to SendDm (#285): an image is a message body, so it must
// clear the same friendship bar before a single byte is stored.
func (q *Queries) SaveDmImage(ctx context.Context, arg SaveDmImageParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, saveDmImage,
		arg.SenderID,
		arg.RecipientID,
		arg.Mime,
		arg.Bytes,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const sendDm = `-- name: SendDm :one
insert into dm_messages (sender_id, recipient_id, text, image_id)
select $1, $2, $3, $4
where exists (
    select 1 from friendships f
    where f.status = 'accepted'
      and ((f.requester_id = $1 and f.addressee_id = $2)
        or (f.requester_id = $2 and f.addressee_id = $1))
)
and ($4::uuid is null or exists (
    select 1 from dm_images i
    where i.id = $4
      and least(i.sender_id, i.recipient_id) = least($1::uuid, $2::uuid)
      and greatest(i.sender_id, i.recipient_id) = greatest($1::uuid, $2::uuid)
))
returning id, created_at
`

type SendDmParams struct {
	SenderID    pgtype.UUID
	RecipientID pgtype.UUID
	Text        string
	ImageID     pgtype.UUID
}

type SendDmRow struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

// The friendship row IS the permission (ADR-0012 amended): no accepted
// friendship, no insert — the caller reads zero rows back and refuses.
// An attached image must belong to THIS pair. Serving already scopes by pair,
// so a foreign id could never be viewed — but referencing one would pin its
// bytes past the sweep, which is how a client escapes the storage bound.
func (q *Queries) SendDm(ctx context.Context, arg SendDmParams) (SendDmRow, error) {
	row := q.db.QueryRow(ctx, sendDm,
		arg.SenderID,
		arg.RecipientID,
		arg.Text,
		arg.ImageID,
	)
	var i SendDmRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
