// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: emoji.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCrewEmoji = `-- name: CountCrewEmoji :one
select count(*) from crew_emoji where crew_id = $1
`

// Asked with the crew's row locked (LockCrew), in the transaction that
// inserts: a count and an insert apart are a ceiling a burst walks through
// (#1413).
func (q *Queries) CountCrewEmoji(ctx context.Context, crewID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCrewEmoji, crewID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCrewEmoji = `-- name: CreateCrewEmoji :one
insert into crew_emoji (crew_id, user_id, name, mime, bytes)
values ($1, $2, $3, $4, $5)
returning id, name, user_id, created_at
`

type CreateCrewEmojiParams struct {
	CrewID pgtype.UUID
	UserID pgtype.UUID
	Name   string
	Mime   string
	Bytes  []byte
}

type CreateCrewEmojiRow struct {
	ID        pgtype.UUID
	Name      string
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

// A name the crew already has is a unique violation, which the handler
// answers as a 409 — the constraint rather than a read first, so two members
// racing for the same :name: cannot both win.
func (q *Queries) CreateCrewEmoji(ctx context.Context, arg CreateCrewEmojiParams) (CreateCrewEmojiRow, error) {
	row := q.db.QueryRow(ctx, createCrewEmoji,
		arg.CrewID,
		arg.UserID,
		arg.Name,
		arg.Mime,
		arg.Bytes,
	)
	var i CreateCrewEmojiRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCrewEmoji = `-- name: DeleteCrewEmoji :execrows
delete from crew_emoji where id = $1 and crew_id = $2
`

type DeleteCrewEmojiParams struct {
	ID     pgtype.UUID
	CrewID pgtype.UUID
}

// The row count is the answer: 0 means no such emoji in this crew.
func (q *Queries) DeleteCrewEmoji(ctx context.Context, arg DeleteCrewEmojiParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCrewEmoji, arg.ID, arg.CrewID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCrewEmojiImage = `-- name: GetCrewEmojiImage :one
select mime, bytes from crew_emoji where id = $1 and crew_id = $2
`

type GetCrewEmojiImageParams struct {
	ID     pgtype.UUID
	CrewID pgtype.UUID
}

type GetCrewEmojiImageRow struct {
	Mime  string
	Bytes []byte
}

func (q *Queries) GetCrewEmojiImage(ctx context.Context, arg GetCrewEmojiImageParams) (GetCrewEmojiImageRow, error) {
	row := q.db.QueryRow(ctx, getCrewEmojiImage, arg.ID, arg.CrewID)
	var i GetCrewEmojiImageRow
	err := row.Scan(&i.Mime, &i.Bytes)
	return i, err
}

const getCrewEmojiUploader = `-- name: GetCrewEmojiUploader :one
select user_id from crew_emoji where id = $1 and crew_id = $2
`

type GetCrewEmojiUploaderParams struct {
	ID     pgtype.UUID
	CrewID pgtype.UUID
}

// Who may delete it is the uploader or the crew's keepers, so the delete
// reads the uploader first to tell "not yours" (403) from "not here" (404).
func (q *Queries) GetCrewEmojiUploader(ctx context.Context, arg GetCrewEmojiUploaderParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getCrewEmojiUploader, arg.ID, arg.CrewID)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const listCrewEmoji = `-- name: ListCrewEmoji :many

select id, name, user_id, created_at
from crew_emoji
where crew_id = $1
order by name
`

type ListCrewEmojiRow struct {
	ID        pgtype.UUID
	Name      string
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

// A crew's own emoji (#2643). Every statement is scoped by crew_id, including
// the ones that already have the emoji's own id — pins.sql's rule: the handler
// resolved the crew from the path and the membership from that, so an id from
// another crew must miss rather than be trusted.
// Not `bytes`: the listing is what a picker draws from, and each picture is
// fetched on its own immutable URL.
func (q *Queries) ListCrewEmoji(ctx context.Context, crewID pgtype.UUID) ([]ListCrewEmojiRow, error) {
	rows, err := q.db.Query(ctx, listCrewEmoji, crewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCrewEmojiRow
	for rows.Next() {
		var i ListCrewEmojiRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
