// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: export.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const exportUserAchievements = `-- name: ExportUserAchievements :many
select key, earned_at from achievements where user_id = $1 order by earned_at
`

type ExportUserAchievementsRow struct {
	Key      string
	EarnedAt pgtype.Timestamptz
}

func (q *Queries) ExportUserAchievements(ctx context.Context, userID pgtype.UUID) ([]ExportUserAchievementsRow, error) {
	rows, err := q.db.Query(ctx, exportUserAchievements, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportUserAchievementsRow
	for rows.Next() {
		var i ExportUserAchievementsRow
		if err := rows.Scan(&i.Key, &i.EarnedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportUserApiTokens = `-- name: ExportUserApiTokens :many

select name, created_at, last_used_at
from api_tokens
where user_id = $1
order by created_at desc
limit $2::int
`

type ExportUserApiTokensParams struct {
	UserID pgtype.UUID
	Lim    int32
}

type ExportUserApiTokensRow struct {
	Name       string
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
}

// Everything below was found by the sweep in #2089: every table with a column
// referencing users(id), read against the categories above. Each is on a
// screen the rider already has, so each is inside the Art. 15 scope the
// handler sets out, and each was missing.
//
// All of them are bounded by the handler's one row ceiling, because none of
// them is bounded by anything else a rider cannot raise on purpose. The
// manifest says when a bound bit; a category that goes short in silence is
// the failure this whole route exists to prevent.
// The coach-access tokens the rider minted (#2089, ADR-0017): the name they
// gave each, when it was made and when it was last used — the three columns
// Settings → Data lists. NEVER token_hash: the token itself was shown once at
// creation and we have only its hash, so there is nothing here to hand back
// even if it were wise to.
func (q *Queries) ExportUserApiTokens(ctx context.Context, arg ExportUserApiTokensParams) ([]ExportUserApiTokensRow, error) {
	rows, err := q.db.Query(ctx, exportUserApiTokens, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportUserApiTokensRow
	for rows.Next() {
		var i ExportUserApiTokensRow
		if err := rows.Scan(&i.Name, &i.CreatedAt, &i.LastUsedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportUserBoardClips = `-- name: ExportUserBoardClips :many
select id, name, pad, key, duration_ms, octet_length(bytes)::int as size_bytes,
       start_ms, end_ms, gain_db, fade_in_ms, fade_out_ms, created_at
from board_clips
where user_id = $1
order by created_at desc
limit $2::int
`

type ExportUserBoardClipsParams struct {
	UserID pgtype.UUID
	Lim    int32
}

type ExportUserBoardClipsRow struct {
	ID         pgtype.UUID
	Name       string
	Pad        *int16
	Key        *string
	DurationMs int32
	SizeBytes  int32
	StartMs    int32
	EndMs      int32
	GainDb     float32
	FadeInMs   int32
	FadeOutMs  int32
	CreatedAt  pgtype.Timestamptz
}

// The soundboard the rider built (#2089): every clip in their library, the
// name they typed, the pad and key they bound it to, and the edit they set —
// the same columns ListBoardClips renders, which is what they see.
//
// Rows in, AUDIO OUT, the reading ADR-0015 settled for uploaded music and
// #2081 applied to tracks.json: "metadata is; files are re-uploadable". It is
// also the only version that fits — a rider's clips may be 100 MB (SPEC's
// MaxRiderBytes) and this archive is built whole in memory. The clip's id
// comes along because a clip is served by id and nothing else, so a row still
// names its file. The bytes a rider uploaded are #2090.
func (q *Queries) ExportUserBoardClips(ctx context.Context, arg ExportUserBoardClipsParams) ([]ExportUserBoardClipsRow, error) {
	rows, err := q.db.Query(ctx, exportUserBoardClips, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportUserBoardClipsRow
	for rows.Next() {
		var i ExportUserBoardClipsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Pad,
			&i.Key,
			&i.DurationMs,
			&i.SizeBytes,
			&i.StartMs,
			&i.EndMs,
			&i.GainDb,
			&i.FadeInMs,
			&i.FadeOutMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportUserChat = `-- name: ExportUserChat :many

select c.text, c.created_at, c.edited_at, c.image_id,
       r.name as room_name, r.slug as room_slug
from chat_messages c
join rooms r on r.id = c.room_id
where c.user_id = $1
order by c.created_at
`

type ExportUserChatRow struct {
	Text      string
	CreatedAt pgtype.Timestamptz
	EditedAt  pgtype.Timestamptz
	ImageID   pgtype.UUID
	RoomName  string
	RoomSlug  string
}

// Export-all (#35, #696). One query per category the law says the export has
// to carry, each scoped to the requesting account and each returning what the
// rider can already see in the app — never another rider's health data, ids
// or contact details. The reasoning for the scope is in the handler.
// The rider's OWN room chat lines. Other people's lines in the same room are
// their personal data, not the requester's, so they are not here.
//
// The edit and the picture come too (#2089): messages.json has carried both
// for DMs since #1819 and chat.json carried neither, so an edited line
// exported as if it had always read that way and a picture-only line exported
// as an empty string.
func (q *Queries) ExportUserChat(ctx context.Context, userID pgtype.UUID) ([]ExportUserChatRow, error) {
	rows, err := q.db.Query(ctx, exportUserChat, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportUserChatRow
	for rows.Next() {
		var i ExportUserChatRow
		if err := rows.Scan(
			&i.Text,
			&i.CreatedAt,
			&i.EditedAt,
			&i.ImageID,
			&i.RoomName,
			&i.RoomSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportUserChatReactions = `-- name: ExportUserChatReactions :many

select r.emoji,
       m.created_at                            as line_at,
       rm.name                                 as room_name,
       rm.slug                                 as room_slug,
       (m.user_id = $1)::boolean as on_my_own_line,
       (case when m.user_id = $1 then m.text else '' end)::text as line
from chat_reactions r
join chat_messages m on m.id = r.message_id
join rooms rm on rm.id = m.room_id
where r.user_id = $1
order by m.created_at
limit $2::int
`

type ExportUserChatReactionsParams struct {
	UserID pgtype.UUID
	Lim    int32
}

type ExportUserChatReactionsRow struct {
	Emoji       string
	LineAt      pgtype.Timestamptz
	RoomName    string
	RoomSlug    string
	OnMyOwnLine bool
	Line        string
}

// The rider's own emoji reactions (#2089), asked of the two surfaces
// separately and written to one file: adding an emoji to something someone
// wrote is one act, and the reader should not have to open two files to find
// theirs. Two queries because sqlc cannot type a parameter comparison inside
// a UNION arm's select list, and the `mine` flag below is exactly that.
//
// A reaction is theirs; the line under it may not be. So a row locates the
// line by the moment it was written, so it lines up with chat.json or
// messages.json, and the TEXT comes along only where the rider is entitled to
// it: their own room-chat line, or any line of a DM thread they can already
// read whole. Someone else's room-chat line is their personal data — the rule
// chat.json has followed since #696.
func (q *Queries) ExportUserChatReactions(ctx context.Context, arg ExportUserChatReactionsParams) ([]ExportUserChatReactionsRow, error) {
	rows, err := q.db.Query(ctx, exportUserChatReactions, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportUserChatReactionsRow
	for rows.Next() {
		var i ExportUserChatReactionsRow
		if err := rows.Scan(
			&i.Emoji,
			&i.LineAt,
			&i.RoomName,
			&i.RoomSlug,
			&i.OnMyOwnLine,
			&i.Line,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportUserCrews = `-- name: ExportUserCrews :many
select c.name,
       c.icon,
       coalesce(c.code, '')::text                              as join_code,
       c.created_at,
       c.renamed_at,
       (c.owner_id = $1)                        as i_own_it,
       coalesce(c.founded_by = $1, false)::boolean as i_founded_it,
       coalesce(cr.role, case when c.owner_id = $1
                              then 'owner' else '' end)::text  as my_role,
       cr.joined_at,
       cr.set_at                                               as role_set_at
from crews c
left join crew_roles cr on cr.crew_id = c.id and cr.user_id = $1
where c.owner_id = $1 or cr.user_id is not null
order by c.created_at
limit $2::int
`

type ExportUserCrewsParams struct {
	UserID pgtype.UUID
	Lim    int32
}

type ExportUserCrewsRow struct {
	Name       string
	Icon       string
	JoinCode   string
	CreatedAt  pgtype.Timestamptz
	RenamedAt  pgtype.Timestamptz
	IOwnIt     bool
	IFoundedIt bool
	MyRole     string
	JoinedAt   pgtype.Timestamptz
	RoleSetAt  pgtype.Timestamptz
}

// The rider's standing in every crew, and the crews they own (#2089, ADR-0038).
// One file because they are one object seen from two sides: an owner holds no
// crew_roles row at all (the 2026-09-08 amendment), so the union is the only
// reading that misses neither.
//
// `banned` is a standing too, and it is the one a rider is most likely to ask
// about — so this query filters no role, unlike ListCrewsFor which feeds a
// sidebar. The join code is the crew's door and every member already reads it
// in the app; it is a live secret, which is what the privacy page now says
// about this zip.
func (q *Queries) ExportUserCrews(ctx context.Context, arg ExportUserCrewsParams) ([]ExportUserCrewsRow, error) {
	rows, err := q.db.Query(ctx, exportUserCrews, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportUserCrewsRow
	for rows.Next() {
		var i ExportUserCrewsRow
		if err := rows.Scan(
			&i.Name,
			&i.Icon,
			&i.JoinCode,
			&i.CreatedAt,
			&i.RenamedAt,
			&i.IOwnIt,
			&i.IFoundedIt,
			&i.MyRole,
			&i.JoinedAt,
			&i.RoleSetAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportUserDmReactions = `-- name: ExportUserDmReactions :many
select r.emoji,
       m.created_at as line_at,
       (case when m.sender_id = $1 then rp.display_name
             else sp.display_name end)::text     as peer_name,
       (m.sender_id = $1)::boolean as on_my_own_line,
       m.text                                    as line
from dm_reactions r
join dm_messages m on m.id = r.message_id
join users sp on sp.id = m.sender_id
join users rp on rp.id = m.recipient_id
where r.user_id = $1
order by m.created_at
limit $2::int
`

type ExportUserDmReactionsParams struct {
	UserID pgtype.UUID
	Lim    int32
}

type ExportUserDmReactionsRow struct {
	Emoji       string
	LineAt      pgtype.Timestamptz
	PeerName    string
	OnMyOwnLine bool
	Line        string
}

// The whole line comes along here: a DM thread is as much the rider's as the
// peer's and messages.json already carries every line of it.
func (q *Queries) ExportUserDmReactions(ctx context.Context, arg ExportUserDmReactionsParams) ([]ExportUserDmReactionsRow, error) {
	rows, err := q.db.Query(ctx, exportUserDmReactions, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportUserDmReactionsRow
	for rows.Next() {
		var i ExportUserDmReactionsRow
		if err := rows.Scan(
			&i.Emoji,
			&i.LineAt,
			&i.PeerName,
			&i.OnMyOwnLine,
			&i.Line,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportUserDms = `-- name: ExportUserDms :many
select m.text, m.created_at, m.edited_at, m.image_id, m.sender_id = $1 as sent_by_me,
       (case when m.sender_id = $1 then r.display_name else s.display_name end)::text as peer_name
from dm_messages m
join users s on s.id = m.sender_id
join users r on r.id = m.recipient_id
where m.sender_id = $1 or m.recipient_id = $1
order by m.created_at
`

type ExportUserDmsRow struct {
	Text      string
	CreatedAt pgtype.Timestamptz
	EditedAt  pgtype.Timestamptz
	ImageID   pgtype.UUID
	SentByMe  bool
	PeerName  string
}

// Whole threads, both sides: a DM is as much about the requester as about the
// peer, and they can already read every line of it in the app. The peer is
// named the way the app names them and by nothing else.
func (q *Queries) ExportUserDms(ctx context.Context, senderID pgtype.UUID) ([]ExportUserDmsRow, error) {
	rows, err := q.db.Query(ctx, exportUserDms, senderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportUserDmsRow
	for rows.Next() {
		var i ExportUserDmsRow
		if err := rows.Scan(
			&i.Text,
			&i.CreatedAt,
			&i.EditedAt,
			&i.ImageID,
			&i.SentByMe,
			&i.PeerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportUserFriends = `-- name: ExportUserFriends :many
select (case when f.requester_id = $1 then a.display_name else b.display_name end)::text as peer_name,
       f.requester_id = $1 as i_asked, f.status, f.created_at
from friendships f
join users b on b.id = f.requester_id
join users a on a.id = f.addressee_id
where f.requester_id = $1 or f.addressee_id = $1
order by f.created_at
`

type ExportUserFriendsRow struct {
	PeerName  string
	IAsked    bool
	Status    string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ExportUserFriends(ctx context.Context, requesterID pgtype.UUID) ([]ExportUserFriendsRow, error) {
	rows, err := q.db.Query(ctx, exportUserFriends, requesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportUserFriendsRow
	for rows.Next() {
		var i ExportUserFriendsRow
		if err := rows.Scan(
			&i.PeerName,
			&i.IAsked,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportUserIdentities = `-- name: ExportUserIdentities :many
select provider, provider_user_id, created_at
from identities
where user_id = $1
order by created_at
`

type ExportUserIdentitiesRow struct {
	Provider       string
	ProviderUserID string
	CreatedAt      pgtype.Timestamptz
}

// The credential set's provider half (#1826): which provider, the id it knows
// the rider by, and when it was connected — never a token, sealed or not.
func (q *Queries) ExportUserIdentities(ctx context.Context, userID pgtype.UUID) ([]ExportUserIdentitiesRow, error) {
	rows, err := q.db.Query(ctx, exportUserIdentities, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportUserIdentitiesRow
	for rows.Next() {
		var i ExportUserIdentitiesRow
		if err := rows.Scan(&i.Provider, &i.ProviderUserID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportUserMedals = `-- name: ExportUserMedals :many
select m.kind, m.awarded_at, rm.name as room_name, r.started_at as ride_started_at
from medals m
join rooms rm on rm.id = m.room_id
join rides r on r.id = m.ride_id
where m.user_id = $1
order by m.awarded_at
`

type ExportUserMedalsRow struct {
	Kind          string
	AwardedAt     pgtype.Timestamptz
	RoomName      string
	RideStartedAt pgtype.Timestamptz
}

// The rider's own medals (#1550): the room that awarded them, and the ride
// named by its start so a row lines up with rides.json.
func (q *Queries) ExportUserMedals(ctx context.Context, userID pgtype.UUID) ([]ExportUserMedalsRow, error) {
	rows, err := q.db.Query(ctx, exportUserMedals, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportUserMedalsRow
	for rows.Next() {
		var i ExportUserMedalsRow
		if err := rows.Scan(
			&i.Kind,
			&i.AwardedAt,
			&i.RoomName,
			&i.RideStartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportUserOwnedRooms = `-- name: ExportUserOwnedRooms :many
select r.name, r.slug, r.created_at, r.listed, r.crew_visible, r.board_enabled,
       r.sound_pack, r.icon, r.cheers, r.autoplay_enabled, r.autoplay_order,
       r.ics_token, c.name as crew_name
from rooms r
left join crews c on c.id = r.crew_id
where r.owner_id = $1
order by r.created_at
limit $2::int
`

type ExportUserOwnedRoomsParams struct {
	UserID pgtype.UUID
	Lim    int32
}

type ExportUserOwnedRoomsRow struct {
	Name            string
	Slug            string
	CreatedAt       pgtype.Timestamptz
	Listed          bool
	CrewVisible     bool
	BoardEnabled    bool
	SoundPack       string
	Icon            string
	Cheers          string
	AutoplayEnabled bool
	AutoplayOrder   string
	IcsToken        string
	CrewName        *string
}

// The room rows the rider owns (#2089). rooms.json says they are a member;
// this says what they configured, which is the whole of the room settings
// screen — including the calendar token, a live link into the room's schedule
// that no other file carries, and the sound pack, which is a room's setting
// and not (as #2089 supposed) a column on users.
func (q *Queries) ExportUserOwnedRooms(ctx context.Context, arg ExportUserOwnedRoomsParams) ([]ExportUserOwnedRoomsRow, error) {
	rows, err := q.db.Query(ctx, exportUserOwnedRooms, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportUserOwnedRoomsRow
	for rows.Next() {
		var i ExportUserOwnedRoomsRow
		if err := rows.Scan(
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.Listed,
			&i.CrewVisible,
			&i.BoardEnabled,
			&i.SoundPack,
			&i.Icon,
			&i.Cheers,
			&i.AutoplayEnabled,
			&i.AutoplayOrder,
			&i.IcsToken,
			&i.CrewName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportUserPasskeys = `-- name: ExportUserPasskeys :many
select name, created_at, last_used_at
from passkeys
where user_id = $1
order by created_at
`

type ExportUserPasskeysRow struct {
	Name       string
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
}

// The passkeys' public metadata (#1826): the rider's name for each, when it
// was added and last used — never the credential record itself.
func (q *Queries) ExportUserPasskeys(ctx context.Context, userID pgtype.UUID) ([]ExportUserPasskeysRow, error) {
	rows, err := q.db.Query(ctx, exportUserPasskeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportUserPasskeysRow
	for rows.Next() {
		var i ExportUserPasskeysRow
		if err := rows.Scan(&i.Name, &i.CreatedAt, &i.LastUsedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportUserPlaylists = `-- name: ExportUserPlaylists :many
select p.name, p.created_at, coalesce(
    (select json_agg(json_build_object(
        'source', case when t.track_id is not null then 'library'
                       when t.yt_playlist_id <> '' then 'youtubePlaylist'
                       else 'video' end,
        'title', t.title,
        'videoId', nullif(t.video_id, ''),
        'startSec', t.start_sec,
        'youtubePlaylistTitle', nullif(t.yt_playlist_title, ''),
        'videos', case when t.yt_playlist_id <> '' then t.tracks else null end
     ) order by t.position)
     from playlist_tracks t where t.playlist_id = p.id), '[]')::text as tracks
from playlists p
where p.user_id = $1
order by p.created_at
`

type ExportUserPlaylistsRow struct {
	Name      string
	CreatedAt pgtype.Timestamptz
	Tracks    string
}

// Personal playlists only. A room's playlist belongs to the room.
//
// An entry is what a JukeboxEntry is (ADR-0045): a video, a pasted YouTube
// playlist, or a track from the rider's own library. Exporting only
// `video_id` made the last two unreadable (#1089) — a library entry has no
// video id at all, so a playlist of the rider's own uploads exported as a
// list of blanks, and a pasted playlist lost its name and its resolved
// videos. `source` says which of the three an entry is, so nothing has to be
// inferred from an empty string; the track is named rather than pointed at,
// because a uuid means nothing outside this database.
func (q *Queries) ExportUserPlaylists(ctx context.Context, userID pgtype.UUID) ([]ExportUserPlaylistsRow, error) {
	rows, err := q.db.Query(ctx, exportUserPlaylists, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportUserPlaylistsRow
	for rows.Next() {
		var i ExportUserPlaylistsRow
		if err := rows.Scan(&i.Name, &i.CreatedAt, &i.Tracks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportUserRideDeliveries = `-- name: ExportUserRideDeliveries :many
select e.destination, e.state, e.attempts, e.last_error, e.remote_id,
       e.created_at, e.updated_at,
       r.started_at as ride_started_at, r.workout_name
from ride_exports e
join rides r on r.id = e.ride_id
where r.user_id = $1
order by r.started_at desc
limit $2::int
`

type ExportUserRideDeliveriesParams struct {
	UserID pgtype.UUID
	Lim    int32
}

type ExportUserRideDeliveriesRow struct {
	Destination   string
	State         string
	Attempts      int32
	LastError     *string
	RemoteID      *int64
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	RideStartedAt pgtype.Timestamptz
	WorkoutName   string
}

// Where each ride was sent and whether it arrived (#2089, #799): the ride
// page says "On Strava as …", or waiting, or failed, and none of it was in
// the archive. Owner-scoped through rides, because ride_exports keys on the
// ride and not on the rider.
//
// The ride is named by its start, the way medals.json names one, so a row
// lines up with rides.json without a uuid meaning anything outside this
// database.
func (q *Queries) ExportUserRideDeliveries(ctx context.Context, arg ExportUserRideDeliveriesParams) ([]ExportUserRideDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, exportUserRideDeliveries, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportUserRideDeliveriesRow
	for rows.Next() {
		var i ExportUserRideDeliveriesRow
		if err := rows.Scan(
			&i.Destination,
			&i.State,
			&i.Attempts,
			&i.LastError,
			&i.RemoteID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RideStartedAt,
			&i.WorkoutName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportUserRoomDoors = `-- name: ExportUserRoomDoors :many
select 'toMe'::text as direction, r.name as room_name, r.slug as room_slug,
       ''::text as rider, g.granted_at
from room_grants g
join rooms r on r.id = g.room_id
where g.user_id = $2
union all
select 'iOpened'::text, r.name, r.slug, u.display_name::text, g.granted_at
from room_grants g
join rooms r on r.id = g.room_id
join users u on u.id = g.user_id
where r.owner_id = $2 and g.user_id <> $2
order by granted_at
limit $1::int
`

type ExportUserRoomDoorsParams struct {
	Lim    int32
	UserID pgtype.UUID
}

type ExportUserRoomDoorsRow struct {
	Direction string
	RoomName  string
	RoomSlug  string
	Rider     string
	GrantedAt pgtype.Timestamptz
}

// Named exceptions into a private room (#2089, ADR-0038 #1224): a door, not a
// membership — the person still walks in themselves, and the grant is moot
// once they do.
//
// Both directions, because both are the rider's: the doors opened FOR them,
// and the doors THEY opened as a room's owner. The second names other people,
// so it names them the way the owner's own door list does and by nothing
// else — a display name, never an id or an address.
func (q *Queries) ExportUserRoomDoors(ctx context.Context, arg ExportUserRoomDoorsParams) ([]ExportUserRoomDoorsRow, error) {
	rows, err := q.db.Query(ctx, exportUserRoomDoors, arg.Lim, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportUserRoomDoorsRow
	for rows.Next() {
		var i ExportUserRoomDoorsRow
		if err := rows.Scan(
			&i.Direction,
			&i.RoomName,
			&i.RoomSlug,
			&i.Rider,
			&i.GrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportUserRooms = `-- name: ExportUserRooms :many
select r.name, r.slug, m.role, m.joined_at, m.notify, m.on_board
from memberships m
join rooms r on r.id = m.room_id
where m.user_id = $1
order by m.joined_at
`

type ExportUserRoomsRow struct {
	Name     string
	Slug     string
	Role     string
	JoinedAt pgtype.Timestamptz
	Notify   bool
	OnBoard  bool
}

// The rooms the rider belongs to, and the two choices they made in each
// (#2089): whether the room may mail them about a planned session, and
// whether they appear on its weekly board. Both are set on the room's own
// settings screen and neither was exported.
func (q *Queries) ExportUserRooms(ctx context.Context, userID pgtype.UUID) ([]ExportUserRoomsRow, error) {
	rows, err := q.db.Query(ctx, exportUserRooms, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportUserRoomsRow
	for rows.Next() {
		var i ExportUserRoomsRow
		if err := rows.Scan(
			&i.Name,
			&i.Slug,
			&i.Role,
			&i.JoinedAt,
			&i.Notify,
			&i.OnBoard,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportUserRsvps = `-- name: ExportUserRsvps :many
select s.workout_name, s.starts_at, r.name as room_name, v.created_at
from session_rsvps v
join scheduled_sessions s on s.id = v.session_id
join rooms r on r.id = s.room_id
where v.user_id = $1
order by s.starts_at
`

type ExportUserRsvpsRow struct {
	WorkoutName string
	StartsAt    pgtype.Timestamptz
	RoomName    string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ExportUserRsvps(ctx context.Context, userID pgtype.UUID) ([]ExportUserRsvpsRow, error) {
	rows, err := q.db.Query(ctx, exportUserRsvps, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportUserRsvpsRow
	for rows.Next() {
		var i ExportUserRsvpsRow
		if err := rows.Scan(
			&i.WorkoutName,
			&i.StartsAt,
			&i.RoomName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportUserScheduledSessions = `-- name: ExportUserScheduledSessions :many
select s.workout_name, s.workout_json, s.starts_at, s.created_at, s.started_at,
       r.name as room_name, r.slug as room_slug
from scheduled_sessions s
join rooms r on r.id = s.room_id
where s.created_by = $1
order by s.starts_at desc
limit $2::int
`

type ExportUserScheduledSessionsParams struct {
	UserID pgtype.UUID
	Lim    int32
}

type ExportUserScheduledSessionsRow struct {
	WorkoutName string
	WorkoutJson []byte
	StartsAt    pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	StartedAt   pgtype.Timestamptz
	RoomName    string
	RoomSlug    string
}

// The sessions the rider PUT ON the calendar (#2089), which is not the same
// set as planned-sessions.json: that one is their RSVPs, so a coach who
// schedules every week and never says yes to their own session exported
// nothing at all. The workout goes with it — they wrote it into the plan, and
// it is what the room was asked to ride.
func (q *Queries) ExportUserScheduledSessions(ctx context.Context, arg ExportUserScheduledSessionsParams) ([]ExportUserScheduledSessionsRow, error) {
	rows, err := q.db.Query(ctx, exportUserScheduledSessions, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportUserScheduledSessionsRow
	for rows.Next() {
		var i ExportUserScheduledSessionsRow
		if err := rows.Scan(
			&i.WorkoutName,
			&i.WorkoutJson,
			&i.StartsAt,
			&i.CreatedAt,
			&i.StartedAt,
			&i.RoomName,
			&i.RoomSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportUserTracks = `-- name: ExportUserTracks :many
select sha256, title, artist, album, tags, bpm, duration_ms, size_bytes, created_at
from tracks
where uploaded_by = $1
order by created_at desc
limit $2::int
`

type ExportUserTracksParams struct {
	UploadedBy pgtype.UUID
	Lim        int32
}

type ExportUserTracksRow struct {
	Sha256     string
	Title      string
	Artist     string
	Album      string
	Tags       []string
	Bpm        *int16
	DurationMs int32
	SizeBytes  int32
	CreatedAt  pgtype.Timestamptz
}

// The music the rider uploaded (#1089): their own shelf's rows, which since
// #1095 is exactly what they can see in the pool — every field they typed,
// plus what the file itself measured. The AUDIO is not here and must not be:
// ADR-0015's copyright fence has no public share links to audio files, and
// the ADR already settled the same question for backups ("metadata is; files
// are re-uploadable"). The content address is, so a row still names its file.
//
// Bounded, unlike the categories above: ADR-0015's quota is 2 GB per rider
// and nothing bounds how small an MP3 may be, so the row count is the one
// here that a rider can run up on purpose. The handler says what the bound
// is and the manifest says when it bit.
//
// Newest first under that bound, the order the shelf itself is browsed in —
// ascending with a limit would drop the tracks they just uploaded.
func (q *Queries) ExportUserTracks(ctx context.Context, arg ExportUserTracksParams) ([]ExportUserTracksRow, error) {
	rows, err := q.db.Query(ctx, exportUserTracks, arg.UploadedBy, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportUserTracksRow
	for rows.Next() {
		var i ExportUserTracksRow
		if err := rows.Scan(
			&i.Sha256,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.Tags,
			&i.Bpm,
			&i.DurationMs,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportUserWorkouts = `-- name: ExportUserWorkouts :many
select name, author, definition, created_at from workouts where owner_id = $1 order by created_at
`

type ExportUserWorkoutsRow struct {
	Name       string
	Author     string
	Definition []byte
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ExportUserWorkouts(ctx context.Context, ownerID pgtype.UUID) ([]ExportUserWorkoutsRow, error) {
	rows, err := q.db.Query(ctx, exportUserWorkouts, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportUserWorkoutsRow
	for rows.Next() {
		var i ExportUserWorkoutsRow
		if err := rows.Scan(
			&i.Name,
			&i.Author,
			&i.Definition,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportUserXp = `-- name: ExportUserXp :many
select amount, source, ref, at from xp_events where user_id = $1 order by at
`

type ExportUserXpRow struct {
	Amount int32
	Source string
	Ref    string
	At     pgtype.Timestamptz
}

func (q *Queries) ExportUserXp(ctx context.Context, userID pgtype.UUID) ([]ExportUserXpRow, error) {
	rows, err := q.db.Query(ctx, exportUserXp, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportUserXpRow
	for rows.Next() {
		var i ExportUserXpRow
		if err := rows.Scan(
			&i.Amount,
			&i.Source,
			&i.Ref,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
