// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ChatMessage struct {
	ID        pgtype.UUID
	RoomID    pgtype.UUID
	UserID    pgtype.UUID
	Text      string
	CreatedAt pgtype.Timestamptz
}

type ChatReaction struct {
	MessageID pgtype.UUID
	UserID    pgtype.UUID
	Emoji     string
}

type DmMessage struct {
	ID          pgtype.UUID
	SenderID    pgtype.UUID
	RecipientID pgtype.UUID
	Text        string
	CreatedAt   pgtype.Timestamptz
}

type Friendship struct {
	RequesterID pgtype.UUID
	AddresseeID pgtype.UUID
	Status      string
	CreatedAt   pgtype.Timestamptz
}

type Identity struct {
	Provider       string
	ProviderUserID string
	UserID         pgtype.UUID
	AccessToken    *string
	RefreshToken   *string
	TokenExpiresAt pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type Medal struct {
	ID        pgtype.UUID
	RoomID    pgtype.UUID
	UserID    pgtype.UUID
	RideID    pgtype.UUID
	Kind      string
	AwardedAt pgtype.Timestamptz
}

type Membership struct {
	RoomID   pgtype.UUID
	UserID   pgtype.UUID
	Role     string
	JoinedAt pgtype.Timestamptz
}

type Ride struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	RoomID      pgtype.UUID
	WorkoutName string
	StartedAt   pgtype.Timestamptz
	Seconds     int32
	AvgWatts    int16
	Kj          int32
	Execution   float32
	FtpWatts    int16
	Samples     []byte
	SharedAt    pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	Curve       []byte
	Xp          int32
}

type Room struct {
	ID        pgtype.UUID
	Code      string
	Slug      string
	Name      string
	OwnerID   pgtype.UUID
	Listed    bool
	CreatedAt pgtype.Timestamptz
	SoundPack string
	Icon      string
	Cheers    string
}

type ScheduledSession struct {
	ID          pgtype.UUID
	RoomID      pgtype.UUID
	WorkoutName string
	WorkoutJson []byte
	StartsAt    pgtype.Timestamptz
	CreatedBy   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
}

type Session struct {
	TokenHash []byte
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type User struct {
	ID            pgtype.UUID
	DisplayName   string
	AvatarUrl     *string
	FtpWatts      int16
	WeightKg      int16
	CreatedAt     pgtype.Timestamptz
	StravaUpload  bool
	Email         *string
	NotifyPlanned bool
	UnsubToken    pgtype.UUID
	FriendCode    string
	AvatarPreset  *string
}

type Workout struct {
	ID         pgtype.UUID
	OwnerID    pgtype.UUID
	Name       string
	Author     string
	Definition []byte
	CreatedAt  pgtype.Timestamptz
}
