// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: passkeys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUserCredentials = `-- name: CountUserCredentials :one
select (select count(*) from identities i where i.user_id = $1)
     + (select count(*) from passkeys p where p.user_id = $1) as total
`

// Providers and passkeys together: what a rider can never take to zero
// (ADR-0029). One query so the passkey and provider removal paths cannot
// disagree about what "last credential" means.
func (q *Queries) CountUserCredentials(ctx context.Context, userID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countUserCredentials, userID)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const createPasskey = `-- name: CreatePasskey :one
insert into passkeys (credential_id, user_id, credential, name)
values ($1, $2, $3, $4)
returning credential_id, user_id, credential, name, created_at, last_used_at
`

type CreatePasskeyParams struct {
	CredentialID []byte
	UserID       pgtype.UUID
	Credential   []byte
	Name         string
}

func (q *Queries) CreatePasskey(ctx context.Context, arg CreatePasskeyParams) (Passkey, error) {
	row := q.db.QueryRow(ctx, createPasskey,
		arg.CredentialID,
		arg.UserID,
		arg.Credential,
		arg.Name,
	)
	var i Passkey
	err := row.Scan(
		&i.CredentialID,
		&i.UserID,
		&i.Credential,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deletePasskey = `-- name: DeletePasskey :execrows
delete from passkeys where credential_id = $1 and user_id = $2
`

type DeletePasskeyParams struct {
	CredentialID []byte
	UserID       pgtype.UUID
}

func (q *Queries) DeletePasskey(ctx context.Context, arg DeletePasskeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePasskey, arg.CredentialID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPasskey = `-- name: GetPasskey :one
select credential_id, user_id, credential, name, created_at, last_used_at from passkeys where credential_id = $1
`

func (q *Queries) GetPasskey(ctx context.Context, credentialID []byte) (Passkey, error) {
	row := q.db.QueryRow(ctx, getPasskey, credentialID)
	var i Passkey
	err := row.Scan(
		&i.CredentialID,
		&i.UserID,
		&i.Credential,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listUserPasskeys = `-- name: ListUserPasskeys :many
select credential_id, user_id, credential, name, created_at, last_used_at from passkeys where user_id = $1 order by created_at
`

func (q *Queries) ListUserPasskeys(ctx context.Context, userID pgtype.UUID) ([]Passkey, error) {
	rows, err := q.db.Query(ctx, listUserPasskeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Passkey
	for rows.Next() {
		var i Passkey
		if err := rows.Scan(
			&i.CredentialID,
			&i.UserID,
			&i.Credential,
			&i.Name,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renamePasskey = `-- name: RenamePasskey :one
update passkeys set name = $3 where credential_id = $1 and user_id = $2
returning credential_id, user_id, credential, name, created_at, last_used_at
`

type RenamePasskeyParams struct {
	CredentialID []byte
	UserID       pgtype.UUID
	Name         string
}

func (q *Queries) RenamePasskey(ctx context.Context, arg RenamePasskeyParams) (Passkey, error) {
	row := q.db.QueryRow(ctx, renamePasskey, arg.CredentialID, arg.UserID, arg.Name)
	var i Passkey
	err := row.Scan(
		&i.CredentialID,
		&i.UserID,
		&i.Credential,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const touchPasskey = `-- name: TouchPasskey :exec
update passkeys
set credential = $2, last_used_at = now()
where credential_id = $1
`

type TouchPasskeyParams struct {
	CredentialID []byte
	Credential   []byte
}

// Every login rewrites the record: the signature counter inside it moves, and
// go-webauthn hands back the credential it validated with.
func (q *Queries) TouchPasskey(ctx context.Context, arg TouchPasskeyParams) error {
	_, err := q.db.Exec(ctx, touchPasskey, arg.CredentialID, arg.Credential)
	return err
}
