// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recaps.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const exportUserRecaps = `-- name: ExportUserRecaps :many
select s.workout, s.started_at, s.ended_at, r.name as room_name, r.slug as room_slug,
       (entry ->> 'from')::bigint as joined_at,
       (entry ->> 'to')::bigint as left_at,
       (entry ->> 'rode')::boolean as rode
from session_recaps s
join rooms r on r.id = s.room_id
cross join lateral jsonb_array_elements(s.riders) entry
where entry ->> 'id' = $1::text
order by s.ended_at
`

type ExportUserRecapsRow struct {
	Workout   string
	StartedAt pgtype.Timestamptz
	EndedAt   pgtype.Timestamptz
	RoomName  string
	RoomSlug  string
	JoinedAt  int64
	LeftAt    int64
	Rode      bool
}

// Export-all (#696, GDPR Art. 15 / revFADP Art. 25): the sessions this rider
// was present for, and their own interval in each. Other riders' intervals are
// their personal data, not the requester's, so the row is narrowed to theirs —
// the same rule ExportUserChat follows.
func (q *Queries) ExportUserRecaps(ctx context.Context, dollar_1 string) ([]ExportUserRecapsRow, error) {
	rows, err := q.db.Query(ctx, exportUserRecaps, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportUserRecapsRow
	for rows.Next() {
		var i ExportUserRecapsRow
		if err := rows.Scan(
			&i.Workout,
			&i.StartedAt,
			&i.EndedAt,
			&i.RoomName,
			&i.RoomSlug,
			&i.JoinedAt,
			&i.LeftAt,
			&i.Rode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomRecaps = `-- name: ListRoomRecaps :many
select r.id, r.workout, r.started_at, r.ended_at, r.riders,
       (select ride.id from rides ride
         where ride.user_id = $3
           and ride.room_id = $1
           and ride.started_at >= r.started_at - interval '1 minute'
           and ride.started_at <= r.ended_at
         order by ride.started_at
         limit 1) as my_ride_id
from (
    select id, room_id, workout, started_at, ended_at, riders, created_at from session_recaps
    where room_id = $1
    order by ended_at desc
    limit $2
) r
order by r.ended_at
`

type ListRoomRecapsParams struct {
	RoomID pgtype.UUID
	Limit  int32
	UserID pgtype.UUID
}

type ListRoomRecapsRow struct {
	ID        pgtype.UUID
	Workout   string
	StartedAt pgtype.Timestamptz
	EndedAt   pgtype.Timestamptz
	Riders    []byte
	MyRideID  pgtype.UUID
}

// The room's most recent, oldest-first for rendering — the same shape and the
// same reason as ListRoomChat, so the timeline merges two ordered lists rather
// than sorting one.
//
// my_ride_id is the VIEWER's own ride from that session, and only ever theirs
// (#1560): the card carries no numbers, so this is the door to the place the
// rider's own numbers already live. Computed per request from $3 and stored
// nowhere — ADR-0034's four settled points do not move.
//
// Matched on the window rather than an id, because nothing links the two: the
// saver dates a room ride `now - elapsed`, the same arithmetic the recap's
// start uses, and a late joiner's ride starts later still. So: any ride of
// mine in this room that began inside the session, with a minute of slack at
// the front for the two clocks.
func (q *Queries) ListRoomRecaps(ctx context.Context, arg ListRoomRecapsParams) ([]ListRoomRecapsRow, error) {
	rows, err := q.db.Query(ctx, listRoomRecaps, arg.RoomID, arg.Limit, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomRecapsRow
	for rows.Next() {
		var i ListRoomRecapsRow
		if err := rows.Scan(
			&i.ID,
			&i.Workout,
			&i.StartedAt,
			&i.EndedAt,
			&i.Riders,
			&i.MyRideID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneSessionRecaps = `-- name: PruneSessionRecaps :execrows
delete from session_recaps
 where ctid in (select ctid from session_recaps
                 where ended_at < now() - make_interval(days => $1::int)
                 limit 10000)
`

// The 90-day bound (docs/SPEC.md). A room is a crew, not an attendance
// register: this is what stops the table answering "where was this person in
// March".
//
// Run by internal/housekeeping, NOT on write. This used to be swept when a
// session ended, by analogy with PruneChat — and the analogy does not hold
// (#1153). PruneChat's bound is 500 messages, and only a write can exceed a
// count, so pruning on write is exactly sufficient there. This bound is time,
// which expires a row with no write involved, so a room that stopped holding
// sessions kept its recaps forever — the one case the bound exists for.
//
// Bounded (audit 2026-09-09): one unbounded delete in one transaction on the
// first sweep after a long gap is the shape every other durable path avoids;
// the caller loops while a batch comes back full.
func (q *Queries) PruneSessionRecaps(ctx context.Context, dollar_1 int32) (int64, error) {
	result, err := q.db.Exec(ctx, pruneSessionRecaps, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveSessionRecap = `-- name: SaveSessionRecap :one

insert into session_recaps (room_id, workout, started_at, ended_at, riders)
values ($1, $2, $3, $4, $5)
on conflict (room_id, started_at) do update
    set workout = excluded.workout, ended_at = excluded.ended_at, riders = excluded.riders
returning id, created_at
`

type SaveSessionRecapParams struct {
	RoomID    pgtype.UUID
	Workout   string
	StartedAt pgtype.Timestamptz
	EndedAt   pgtype.Timestamptz
	Riders    []byte
}

type SaveSessionRecapRow struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

// One row per finished session (ADR-0034): who was in the room, and for how
// long. Presence and time only — no watts, no kJ, no execution, no heart rate
// and no per-rider workout reach this table, which is what lets it be durable
// at all while WATTROOM.md's metrics rules stay untouched.
// Idempotent on (room, started_at): the keeper retries (audit 2026-09-09),
// and the second write of the same session updates rather than duplicates.
func (q *Queries) SaveSessionRecap(ctx context.Context, arg SaveSessionRecapParams) (SaveSessionRecapRow, error) {
	row := q.db.QueryRow(ctx, saveSessionRecap,
		arg.RoomID,
		arg.Workout,
		arg.StartedAt,
		arg.EndedAt,
		arg.Riders,
	)
	var i SaveSessionRecapRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
