// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rides.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const amendRide = `-- name: AmendRide :execrows
update rides
set seconds = $2, avg_watts = $3, kj = $4, execution = $5, execution_scored = $6,
    samples = $7, curve = $8, xp = $9, norm_watts = $10
where id = $1 and seconds < $2
`

type AmendRideParams struct {
	ID              pgtype.UUID
	Seconds         int32
	AvgWatts        int16
	Kj              int32
	Execution       float32
	ExecutionScored bool
	Samples         []byte
	Curve           []byte
	Xp              int32
	NormWatts       *int16
}

// A saved ride grown from a longer record (#1536): a socket that dropped
// before the close and replayed its buffer after it. Only ever longer —
// a replay of what was already saved changes nothing — and the medals
// stay as awarded; xp moves with the row, which user_total_xp sums live.
func (q *Queries) AmendRide(ctx context.Context, arg AmendRideParams) (int64, error) {
	result, err := q.db.Exec(ctx, amendRide,
		arg.ID,
		arg.Seconds,
		arg.AvgWatts,
		arg.Kj,
		arg.Execution,
		arg.ExecutionScored,
		arg.Samples,
		arg.Curve,
		arg.Xp,
		arg.NormWatts,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const best20mIn90Days = `-- name: Best20mIn90Days :one
select coalesce(max((curve->>'best20m')::int), 0)::int from rides
where user_id = $1 and started_at >= now() - interval '90 days'
`

// The FTP auto-detect input (docs/SPEC.md): rolling 90-day best 20-minute power.
func (q *Queries) Best20mIn90Days(ctx context.Context, userID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, best20mIn90Days, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const bestUserRideOfWorkout = `-- name: BestUserRideOfWorkout :one
select rides.id, workout_name, started_at, seconds, avg_watts, kj, execution, execution_scored, ftp_watts, xp, room_id, shared_at,
       e.state as export_state
from rides
left join ride_exports e on e.ride_id = rides.id and e.destination = $4::text
where user_id = $1 and workout_name = $2 and rides.id <> $3
order by avg_watts desc, started_at desc
limit 1
`

type BestUserRideOfWorkoutParams struct {
	UserID      pgtype.UUID
	WorkoutName string
	ID          pgtype.UUID
	Destination string
}

type BestUserRideOfWorkoutRow struct {
	ID              pgtype.UUID
	WorkoutName     string
	StartedAt       pgtype.Timestamptz
	Seconds         int32
	AvgWatts        int16
	Kj              int32
	Execution       float32
	ExecutionScored bool
	FtpWatts        int16
	Xp              int32
	RoomID          pgtype.UUID
	SharedAt        pgtype.Timestamptz
	ExportState     *string
}

// The ride page's "against your best" (#1687): the hardest ride of the same
// workout across the whole history, not the first page of the list. Same
// columns as ListUserRides so one JSON mapping serves both.
func (q *Queries) BestUserRideOfWorkout(ctx context.Context, arg BestUserRideOfWorkoutParams) (BestUserRideOfWorkoutRow, error) {
	row := q.db.QueryRow(ctx, bestUserRideOfWorkout,
		arg.UserID,
		arg.WorkoutName,
		arg.ID,
		arg.Destination,
	)
	var i BestUserRideOfWorkoutRow
	err := row.Scan(
		&i.ID,
		&i.WorkoutName,
		&i.StartedAt,
		&i.Seconds,
		&i.AvgWatts,
		&i.Kj,
		&i.Execution,
		&i.ExecutionScored,
		&i.FtpWatts,
		&i.Xp,
		&i.RoomID,
		&i.SharedAt,
		&i.ExportState,
	)
	return i, err
}

const countRoomMedalsByRider = `-- name: CountRoomMedalsByRider :many
select user_id, count(*)::int as medals
from medals
where room_id = $1
group by user_id
`

type CountRoomMedalsByRiderRow struct {
	UserID pgtype.UUID
	Medals int32
}

// Every medal this room ever awarded, per rider — the roster's count. The
// recent list above is capped and carries names; a count matched on those
// decayed as the room rode and merged two riders with one name (#1371).
func (q *Queries) CountRoomMedalsByRider(ctx context.Context, roomID pgtype.UUID) ([]CountRoomMedalsByRiderRow, error) {
	rows, err := q.db.Query(ctx, countRoomMedalsByRider, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountRoomMedalsByRiderRow
	for rows.Next() {
		var i CountRoomMedalsByRiderRow
		if err := rows.Scan(&i.UserID, &i.Medals); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createMedal = `-- name: CreateMedal :exec
insert into medals (room_id, user_id, ride_id, kind)
values ($1, $2, $3, $4)
`

type CreateMedalParams struct {
	RoomID pgtype.UUID
	UserID pgtype.UUID
	RideID pgtype.UUID
	Kind   string
}

func (q *Queries) CreateMedal(ctx context.Context, arg CreateMedalParams) error {
	_, err := q.db.Exec(ctx, createMedal,
		arg.RoomID,
		arg.UserID,
		arg.RideID,
		arg.Kind,
	)
	return err
}

const createRide = `-- name: CreateRide :one
insert into rides (
    user_id, room_id, workout_name, started_at,
    seconds, avg_watts, kj, execution, execution_scored,
    ftp_watts, samples, curve, xp, norm_watts
)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
returning id
`

type CreateRideParams struct {
	UserID          pgtype.UUID
	RoomID          pgtype.UUID
	WorkoutName     string
	StartedAt       pgtype.Timestamptz
	Seconds         int32
	AvgWatts        int16
	Kj              int32
	Execution       float32
	ExecutionScored bool
	FtpWatts        int16
	Samples         []byte
	Curve           []byte
	Xp              int32
	NormWatts       *int16
}

func (q *Queries) CreateRide(ctx context.Context, arg CreateRideParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createRide,
		arg.UserID,
		arg.RoomID,
		arg.WorkoutName,
		arg.StartedAt,
		arg.Seconds,
		arg.AvgWatts,
		arg.Kj,
		arg.Execution,
		arg.ExecutionScored,
		arg.FtpWatts,
		arg.Samples,
		arg.Curve,
		arg.Xp,
		arg.NormWatts,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const curveBests = `-- name: CurveBests :one
select
    coalesce(max((curve->>'best5s')::int)  filter (where started_at >= now() - interval '30 days'), 0)::int as d30_best5s,
    coalesce(max((curve->>'best1m')::int)  filter (where started_at >= now() - interval '30 days'), 0)::int as d30_best1m,
    coalesce(max((curve->>'best5m')::int)  filter (where started_at >= now() - interval '30 days'), 0)::int as d30_best5m,
    coalesce(max((curve->>'best20m')::int) filter (where started_at >= now() - interval '30 days'), 0)::int as d30_best20m,
    coalesce(max((curve->>'best5s')::int)  filter (where started_at >= now() - interval '90 days'), 0)::int as d90_best5s,
    coalesce(max((curve->>'best1m')::int)  filter (where started_at >= now() - interval '90 days'), 0)::int as d90_best1m,
    coalesce(max((curve->>'best5m')::int)  filter (where started_at >= now() - interval '90 days'), 0)::int as d90_best5m,
    coalesce(max((curve->>'best20m')::int) filter (where started_at >= now() - interval '90 days'), 0)::int as d90_best20m,
    coalesce(max((curve->>'best5s')::int),  0)::int as all_best5s,
    coalesce(max((curve->>'best1m')::int),  0)::int as all_best1m,
    coalesce(max((curve->>'best5m')::int),  0)::int as all_best5m,
    coalesce(max((curve->>'best20m')::int), 0)::int as all_best20m
from rides
where user_id = $1
`

type CurveBestsRow struct {
	D30Best5s  int32
	D30Best1m  int32
	D30Best5m  int32
	D30Best20m int32
	D90Best5s  int32
	D90Best1m  int32
	D90Best5m  int32
	D90Best20m int32
	AllBest5s  int32
	AllBest1m  int32
	AllBest5m  int32
	AllBest20m int32
}

// Progression overlay (#222): best per SPEC curve window over three ranges,
// summary columns only — the sample blob stays cold.
func (q *Queries) CurveBests(ctx context.Context, userID pgtype.UUID) (CurveBestsRow, error) {
	row := q.db.QueryRow(ctx, curveBests, userID)
	var i CurveBestsRow
	err := row.Scan(
		&i.D30Best5s,
		&i.D30Best1m,
		&i.D30Best5m,
		&i.D30Best20m,
		&i.D90Best5s,
		&i.D90Best1m,
		&i.D90Best5m,
		&i.D90Best20m,
		&i.AllBest5s,
		&i.AllBest1m,
		&i.AllBest5m,
		&i.AllBest20m,
	)
	return i, err
}

const deleteRide = `-- name: DeleteRide :execrows
with gone as (
    delete from rides where rides.id = $1 and rides.user_id = $2
    returning rides.id as ride_id, rides.user_id as rider, rides.xp as xp
)
insert into xp_events (user_id, source, amount, ref)
select gone.rider, 'ride_deleted', gone.xp, gone.ride_id::text from gone
`

type DeleteRideParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

// Owner-only by the where clause. The medals awarded for this ride go with
// it through medals.ride_id's on-delete-cascade — no cleanup pass to forget.
//
// The XP does NOT go with it (#1452, ADR-0047): the ride was ridden, and
// deleting the record is privacy, not un-riding. One statement, so the delete
// and its offsetting ledger row cannot come apart — the ride leaves
// `sum(rides.xp)` and the `ride_deleted` row puts the same amount back, which
// leaves `user_total_xp` (rides + ledger) exactly where it was and the level
// where docs/SPEC.md says it stays. `ref` is the ride's id, so the ledger's
// unique (user, source, ref) makes a replay impossible to double-count; no
// `on conflict do nothing` here on purpose, because swallowing a collision
// would report the delete as a 404 it did not get. `at` defaults to now(),
// the moment of the delete — carrying the ride's own `started_at` over would
// put "when this rider rode" back into a row the rider asked to be rid of.
func (q *Queries) DeleteRide(ctx context.Context, arg DeleteRideParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRide, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUser = `-- name: DeleteUser :exec
delete from users where id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const failRideExport = `-- name: FailRideExport :exec
update ride_exports
set attempts = attempts + 1,
    last_error = $3,
    state = case when attempts + 1 >= $4::int then 'failed' else 'pending' end,
    updated_at = now()
where ride_id = $1 and destination = $2
`

type FailRideExportParams struct {
	RideID      pgtype.UUID
	Destination string
	LastError   *string
	MaxAttempts int32
}

// One attempt spent. Past the ceiling the row stops being swept and the
// rider is told, rather than retried at forever.
func (q *Queries) FailRideExport(ctx context.Context, arg FailRideExportParams) error {
	_, err := q.db.Exec(ctx, failRideExport,
		arg.RideID,
		arg.Destination,
		arg.LastError,
		arg.MaxAttempts,
	)
	return err
}

const findRideAt = `-- name: FindRideAt :one
select id from rides where user_id = $1 and started_at = $2 limit 1
`

type FindRideAtParams struct {
	UserID    pgtype.UUID
	StartedAt pgtype.Timestamptz
}

// The ride a save would duplicate (audit 2026-09-09): a retry after a lost
// response — the recovery card, the room saver's second attempt — finds the
// row it already made instead of paying its XP twice. `unique (user_id,
// started_at)` stands behind it now (#2064): this read still spares the
// retry an error, but two saves racing each other no longer both insert.
func (q *Queries) FindRideAt(ctx context.Context, arg FindRideAtParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findRideAt, arg.UserID, arg.StartedAt)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const finishRideExport = `-- name: FinishRideExport :exec
update ride_exports
set state = 'delivered', remote_id = $3, last_error = null, updated_at = now()
where ride_id = $1 and destination = $2
`

type FinishRideExportParams struct {
	RideID      pgtype.UUID
	Destination string
	RemoteID    *int64
}

// The remote has it. remote_id is the activity it became.
func (q *Queries) FinishRideExport(ctx context.Context, arg FinishRideExportParams) error {
	_, err := q.db.Exec(ctx, finishRideExport, arg.RideID, arg.Destination, arg.RemoteID)
	return err
}

const firstRideAt = `-- name: FirstRideAt :one
select min(started_at)::timestamptz as first_ride from rides where user_id = $1
`

// The rider's first saved ride, for SPEC's 28-day cold start (#1689): the
// oldest row inside the year window was not it after a long break.
func (q *Queries) FirstRideAt(ctx context.Context, userID pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, firstRideAt, userID)
	var first_ride pgtype.Timestamptz
	err := row.Scan(&first_ride)
	return first_ride, err
}

const getRide = `-- name: GetRide :one
select r.id, r.user_id, r.room_id, r.workout_name, r.started_at, r.seconds, r.avg_watts, r.kj, r.execution, r.ftp_watts, r.samples, r.shared_at, r.created_at, r.curve, r.xp, r.norm_watts, r.execution_scored, r.ftp_after_watts,
       coalesce(rm.slug, '')::text as room_slug,
       coalesce(rm.name, '')::text as room_name
from rides r
left join rooms rm on rm.id = r.room_id
where r.id = $1 and r.user_id = $2
`

type GetRideParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type GetRideRow struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	RoomID          pgtype.UUID
	WorkoutName     string
	StartedAt       pgtype.Timestamptz
	Seconds         int32
	AvgWatts        int16
	Kj              int32
	Execution       float32
	FtpWatts        int16
	Samples         []byte
	SharedAt        pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	Curve           []byte
	Xp              int32
	NormWatts       *int16
	ExecutionScored bool
	FtpAfterWatts   *int16
	RoomSlug        string
	RoomName        string
}

// The one per-ride blob read ADR-0016 allows: a rider opening a single ride
// is exactly what the samples are kept for. Owner-scoped, so someone else's
// ride reads as absent rather than as forbidden. The room comes along because
// the detail page names it — empty strings for a solo ride.
func (q *Queries) GetRide(ctx context.Context, arg GetRideParams) (GetRideRow, error) {
	row := q.db.QueryRow(ctx, getRide, arg.ID, arg.UserID)
	var i GetRideRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoomID,
		&i.WorkoutName,
		&i.StartedAt,
		&i.Seconds,
		&i.AvgWatts,
		&i.Kj,
		&i.Execution,
		&i.FtpWatts,
		&i.Samples,
		&i.SharedAt,
		&i.CreatedAt,
		&i.Curve,
		&i.Xp,
		&i.NormWatts,
		&i.ExecutionScored,
		&i.FtpAfterWatts,
		&i.RoomSlug,
		&i.RoomName,
	)
	return i, err
}

const getRideExport = `-- name: GetRideExport :one
select state, attempts, last_error, remote_id
from ride_exports
where ride_id = $1 and destination = $2
`

type GetRideExportParams struct {
	RideID      pgtype.UUID
	Destination string
}

type GetRideExportRow struct {
	State     string
	Attempts  int32
	LastError *string
	RemoteID  *int64
}

func (q *Queries) GetRideExport(ctx context.Context, arg GetRideExportParams) (GetRideExportRow, error) {
	row := q.db.QueryRow(ctx, getRideExport, arg.RideID, arg.Destination)
	var i GetRideExportRow
	err := row.Scan(
		&i.State,
		&i.Attempts,
		&i.LastError,
		&i.RemoteID,
	)
	return i, err
}

const getRideForUpload = `-- name: GetRideForUpload :one
select r.id, r.user_id, r.workout_name, r.started_at, r.samples, u.strava_upload
from rides r join users u on u.id = r.user_id
where r.id = $1
`

type GetRideForUploadRow struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	WorkoutName  string
	StartedAt    pgtype.Timestamptz
	Samples      []byte
	StravaUpload bool
}

// The uploader's one read: the ride plus the owner's consent flag.
func (q *Queries) GetRideForUpload(ctx context.Context, id pgtype.UUID) (GetRideForUploadRow, error) {
	row := q.db.QueryRow(ctx, getRideForUpload, id)
	var i GetRideForUploadRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkoutName,
		&i.StartedAt,
		&i.Samples,
		&i.StravaUpload,
	)
	return i, err
}

const getRideSamples = `-- name: GetRideSamples :one
select samples from rides where id = $1 and user_id = $2
`

type GetRideSamplesParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

// One ride's blob, owner-scoped. The export streams these into the zip one
// after another, so peak memory is one blob however long the history is.
func (q *Queries) GetRideSamples(ctx context.Context, arg GetRideSamplesParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getRideSamples, arg.ID, arg.UserID)
	var samples []byte
	err := row.Scan(&samples)
	return samples, err
}

const listRideExportsDue = `-- name: ListRideExportsDue :many
select ride_id, destination, attempts, updated_at
from ride_exports
where state = 'pending' and updated_at < $1::timestamptz
order by updated_at
limit $2::int
`

type ListRideExportsDueParams struct {
	Before  pgtype.Timestamptz
	MaxRows int32
}

type ListRideExportsDueRow struct {
	RideID      pgtype.UUID
	Destination string
	Attempts    int32
	UpdatedAt   pgtype.Timestamptz
}

// The sweep: deliveries still owed a try, quiet for long enough that the last
// failure is not being repeated immediately. Bounded — a backlog drains over
// several sweeps rather than in one burst of uploads.
func (q *Queries) ListRideExportsDue(ctx context.Context, arg ListRideExportsDueParams) ([]ListRideExportsDueRow, error) {
	rows, err := q.db.Query(ctx, listRideExportsDue, arg.Before, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRideExportsDueRow
	for rows.Next() {
		var i ListRideExportsDueRow
		if err := rows.Scan(
			&i.RideID,
			&i.Destination,
			&i.Attempts,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRideMedals = `-- name: ListRideMedals :many
select m.kind, m.awarded_at, rm.name as room_name
from medals m
join rooms rm on rm.id = m.room_id
where m.ride_id = $1
order by m.kind
`

type ListRideMedalsRow struct {
	Kind      string
	AwardedAt pgtype.Timestamptz
	RoomName  string
}

// What one ride won. A medal is always a room's, so the room names itself
// here rather than being looked up a second time.
func (q *Queries) ListRideMedals(ctx context.Context, rideID pgtype.UUID) ([]ListRideMedalsRow, error) {
	rows, err := q.db.Query(ctx, listRideMedals, rideID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRideMedalsRow
	for rows.Next() {
		var i ListRideMedalsRow
		if err := rows.Scan(&i.Kind, &i.AwardedAt, &i.RoomName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRidesMissingNorm = `-- name: ListRidesMissingNorm :many
select id, samples from rides where norm_watts is null limit $1
`

type ListRidesMissingNormRow struct {
	ID      pgtype.UUID
	Samples []byte
}

// The ADR-0016 backfill's read: each blob is read exactly once, then goes
// cold again — the per-ride-read storage rule holds.
func (q *Queries) ListRidesMissingNorm(ctx context.Context, limit int32) ([]ListRidesMissingNormRow, error) {
	rows, err := q.db.Query(ctx, listRidesMissingNorm, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRidesMissingNormRow
	for rows.Next() {
		var i ListRidesMissingNormRow
		if err := rows.Scan(&i.ID, &i.Samples); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomMedals = `-- name: ListRoomMedals :many
select m.kind, m.awarded_at, m.user_id, u.display_name
from medals m
join users u on u.id = m.user_id
where m.room_id = $1
order by m.awarded_at desc
limit $2
`

type ListRoomMedalsParams struct {
	RoomID pgtype.UUID
	Limit  int32
}

type ListRoomMedalsRow struct {
	Kind        string
	AwardedAt   pgtype.Timestamptz
	UserID      pgtype.UUID
	DisplayName string
}

// The rider's id and the moment travel with it (#1411): the client matched
// its own medal by display name and a UTC date, which found nothing after
// local midnight and could name the wrong rider.
func (q *Queries) ListRoomMedals(ctx context.Context, arg ListRoomMedalsParams) ([]ListRoomMedalsRow, error) {
	rows, err := q.db.Query(ctx, listRoomMedals, arg.RoomID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomMedalsRow
	for rows.Next() {
		var i ListRoomMedalsRow
		if err := rows.Scan(
			&i.Kind,
			&i.AwardedAt,
			&i.UserID,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomRideWeeks = `-- name: ListRoomRideWeeks :many
select distinct date_trunc('week', started_at at time zone 'UTC')::date as week
from rides where room_id = $1
order by week desc
limit 60
`

// The ROOM streak — the one on screen, and the one that pays nothing.
// Still UTC, and not by omission: a room's riders are in several zones and a
// room has no zone of its own, so there is no rider's week to use here. The
// rider streak moved to the rider's zone in #2063; which zone a room's week
// belongs to is an open question in that issue.
func (q *Queries) ListRoomRideWeeks(ctx context.Context, roomID pgtype.UUID) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listRoomRideWeeks, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Date
	for rows.Next() {
		var week pgtype.Date
		if err := rows.Scan(&week); err != nil {
			return nil, err
		}
		items = append(items, week)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomSessionDays = `-- name: ListRoomSessionDays :many
select started_at::date as day,
       bool_or(user_id = $1) as attended
from rides
where room_id = $2
group by day
order by day desc
limit 12
`

type ListRoomSessionDaysParams struct {
	ViewerID pgtype.UUID
	RoomID   pgtype.UUID
}

type ListRoomSessionDaysRow struct {
	Day      pgtype.Date
	Attended bool
}

// The room's last sessions, newest first, and whether the caller was in each
// (#995). A day rather than a ride: one evening the crew rode together is one
// dot, however many of them were there. Describes the caller's own turnout and
// nobody else's — RESEARCH.md §14.8 forbids grading attendance.
func (q *Queries) ListRoomSessionDays(ctx context.Context, arg ListRoomSessionDaysParams) ([]ListRoomSessionDaysRow, error) {
	rows, err := q.db.Query(ctx, listRoomSessionDays, arg.ViewerID, arg.RoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomSessionDaysRow
	for rows.Next() {
		var i ListRoomSessionDaysRow
		if err := rows.Scan(&i.Day, &i.Attended); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserProgression = `-- name: ListUserProgression :many
select id, started_at, seconds, kj, execution, execution_scored, ftp_watts,
       -- The FTP this ride PRODUCED, null on all but a ramp whose number was
       -- accepted (#1572) — the trend marks it on the ramp's own ride.
       ftp_after_watts,
       coalesce((curve->>'best20m')::int, 0)::int as best20m,
       coalesce(norm_watts, avg_watts)::int as norm_watts
from rides
where user_id = $1 and started_at >= now() - interval '365 days'
order by started_at desc
limit 1000
`

type ListUserProgressionRow struct {
	ID              pgtype.UUID
	StartedAt       pgtype.Timestamptz
	Seconds         int32
	Kj              int32
	Execution       float32
	ExecutionScored bool
	FtpWatts        int16
	FtpAfterWatts   *int16
	Best20m         int32
	NormWatts       int32
}

// Per-ride trend rows, oldest first (#222): ftp_watts was captured at ride
// time, so FTP history is free; best20m feeds the Category/w-kg trend.
// norm_watts falls back to avg_watts for rides the backfill has not reached.
// Newest first under the bound (#1689): ascending with a limit dropped the
// newest rides for anyone past it. The caller reverses.
func (q *Queries) ListUserProgression(ctx context.Context, userID pgtype.UUID) ([]ListUserProgressionRow, error) {
	rows, err := q.db.Query(ctx, listUserProgression, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserProgressionRow
	for rows.Next() {
		var i ListUserProgressionRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.Seconds,
			&i.Kj,
			&i.Execution,
			&i.ExecutionScored,
			&i.FtpWatts,
			&i.FtpAfterWatts,
			&i.Best20m,
			&i.NormWatts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRideWeeks = `-- name: ListUserRideWeeks :many
select distinct date_trunc('week', started_at at time zone $1::text)::date as week
from rides where user_id = $2
order by week desc
limit 60
`

type ListUserRideWeeksParams struct {
	Tz     string
	UserID pgtype.UUID
}

// Distinct weeks with at least one ride, newest first — the input to the
// RIDER streak, the one docs/SPEC.md says pays.
// Truncated in the rider's own zone (#2063), because their week is the week
// they rode: a Monday 00:30 ride in Zurich is Sunday 23:30 in UTC, which
// bucketed it into the week before and broke a streak the rider had kept.
// The zone is named explicitly rather than left to the session, which is how
// date_trunc on a timestamptz and stats.WeekStreak came to disagree at all
// (audit 2026-09-09); stats.ZoneName is the one place that picks it, so the
// SQL and the Go always agree, and it falls back to UTC for a rider whose
// browser never told us.
func (q *Queries) ListUserRideWeeks(ctx context.Context, arg ListUserRideWeeksParams) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listUserRideWeeks, arg.Tz, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Date
	for rows.Next() {
		var week pgtype.Date
		if err := rows.Scan(&week); err != nil {
			return nil, err
		}
		items = append(items, week)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRides = `-- name: ListUserRides :many
select rides.id, workout_name, started_at, seconds, avg_watts, kj, execution, execution_scored, ftp_watts, xp, room_id, shared_at,
       e.state as export_state
from rides
left join ride_exports e on e.ride_id = rides.id and e.destination = $3::text
where user_id = $1
  and ($4::timestamptz is null
       or (started_at, rides.id) < ($4::timestamptz, $5::uuid))
order by started_at desc, rides.id desc
limit $2
`

type ListUserRidesParams struct {
	UserID      pgtype.UUID
	Limit       int32
	Destination string
	Before      pgtype.Timestamptz
	BeforeID    pgtype.UUID
}

type ListUserRidesRow struct {
	ID              pgtype.UUID
	WorkoutName     string
	StartedAt       pgtype.Timestamptz
	Seconds         int32
	AvgWatts        int16
	Kj              int32
	Execution       float32
	ExecutionScored bool
	FtpWatts        int16
	Xp              int32
	RoomID          pgtype.UUID
	SharedAt        pgtype.Timestamptz
	ExportState     *string
}

// Summary only: the blob stays on disk unless a single ride is opened.
// Paged by start (#1549): `before` is the oldest row the caller has, or
// null for the first page. The delivery state rides along (#1553): a failed
// Strava upload used to be visible only by opening every ride.
//
// The cursor carries the id too, and the order breaks the tie on it (#2064).
// On the timestamp alone the boundary was `started_at < before` against a
// cursor the client had rounded down to the second, so every ride inside that
// second went unread — including ones the client had not been given yet. The
// row comparison is exact, which is the same shape ListUserWorkouts uses.
func (q *Queries) ListUserRides(ctx context.Context, arg ListUserRidesParams) ([]ListUserRidesRow, error) {
	rows, err := q.db.Query(ctx, listUserRides,
		arg.UserID,
		arg.Limit,
		arg.Destination,
		arg.Before,
		arg.BeforeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserRidesRow
	for rows.Next() {
		var i ListUserRidesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutName,
			&i.StartedAt,
			&i.Seconds,
			&i.AvgWatts,
			&i.Kj,
			&i.Execution,
			&i.ExecutionScored,
			&i.FtpWatts,
			&i.Xp,
			&i.RoomID,
			&i.SharedAt,
			&i.ExportState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRidesFull = `-- name: ListUserRidesFull :many
select id, workout_name, started_at, seconds, avg_watts, kj, execution,
       execution_scored, norm_watts, ftp_watts, ftp_after_watts, xp, curve,
       room_id, shared_at
from rides where user_id = $1 order by started_at
`

type ListUserRidesFullRow struct {
	ID              pgtype.UUID
	WorkoutName     string
	StartedAt       pgtype.Timestamptz
	Seconds         int32
	AvgWatts        int16
	Kj              int32
	Execution       float32
	ExecutionScored bool
	NormWatts       *int16
	FtpWatts        int16
	FtpAfterWatts   *int16
	Xp              int32
	Curve           []byte
	RoomID          pgtype.UUID
	SharedAt        pgtype.Timestamptz
}

// Export-all (#35): every ride the rider has, summary columns only. The
// blobs are read one at a time by GetRideSamples below — holding all of them
// at once grows with how long someone has used WattRoom, which is the one
// kind of growth an alpha cannot outrun (#894).
//
// ftp_after_watts comes too (#2089): the ride page shows the number a ramp
// test produced (ADR-0049) and the export did not, so the one ride that
// changed the rider's FTP exported as if it had not.
func (q *Queries) ListUserRidesFull(ctx context.Context, userID pgtype.UUID) ([]ListUserRidesFullRow, error) {
	rows, err := q.db.Query(ctx, listUserRidesFull, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserRidesFullRow
	for rows.Next() {
		var i ListUserRidesFullRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutName,
			&i.StartedAt,
			&i.Seconds,
			&i.AvgWatts,
			&i.Kj,
			&i.Execution,
			&i.ExecutionScored,
			&i.NormWatts,
			&i.FtpWatts,
			&i.FtpAfterWatts,
			&i.Xp,
			&i.Curve,
			&i.RoomID,
			&i.SharedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueRideExport = `-- name: RequeueRideExport :execrows
update ride_exports
set state = 'pending', attempts = 0, last_error = null, updated_at = now()
where ride_id = $1 and destination = $2 and state = 'failed'
`

type RequeueRideExportParams struct {
	RideID      pgtype.UUID
	Destination string
}

// The rider pressing "try again" on a delivery that ran out of attempts
// (#1158). Back to pending with the counter cleared, so the ordinary sweep
// picks it up on its next pass and no second code path exists.
//
// `state = 'failed'` is the guard, not decoration: a delivery still pending
// is already going to be tried, and one that succeeded must not be re-sent —
// pressing a stale button twice would put the ride on Strava twice.
func (q *Queries) RequeueRideExport(ctx context.Context, arg RequeueRideExportParams) (int64, error) {
	result, err := q.db.Exec(ctx, requeueRideExport, arg.RideID, arg.Destination)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const roomCrewTotals = `-- name: RoomCrewTotals :one
select coalesce(sum(seconds), 0)::bigint as seconds,
       count(distinct started_at::date) filter (
         where started_at >= date_trunc('month', now())
       )::bigint as sessions_this_month,
       count(distinct started_at::date) filter (
         where started_at >= date_trunc('month', now()) - interval '1 month'
           and started_at < date_trunc('month', now())
       )::bigint as sessions_last_month
from rides
where room_id = $1
`

type RoomCrewTotalsRow struct {
	Seconds           int64
	SessionsThisMonth int64
	SessionsLastMonth int64
}

// What the crew did together (#995, RESEARCH.md §14.7). Cooperative by
// construction: every figure is a sum or a count over the whole room, so
// nobody is ranked inside any of it. Sessions are counted as distinct days
// rather than rides, because six riders in one session is one session.
func (q *Queries) RoomCrewTotals(ctx context.Context, roomID pgtype.UUID) (RoomCrewTotalsRow, error) {
	row := q.db.QueryRow(ctx, roomCrewTotals, roomID)
	var i RoomCrewTotalsRow
	err := row.Scan(&i.Seconds, &i.SessionsThisMonth, &i.SessionsLastMonth)
	return i, err
}

const roomMonthKj = `-- name: RoomMonthKj :one
select coalesce(sum(kj), 0)::bigint from rides
where room_id = $1 and started_at >= date_trunc('month', now())
`

// The collective challenge number: this month's kJ, together.
func (q *Queries) RoomMonthKj(ctx context.Context, roomID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, roomMonthKj, roomID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const roomWeekBoard = `-- name: RoomWeekBoard :many
select r.user_id,
       u.display_name,
       u.ftp_watts,
       u.weight_kg,
       coalesce(sum(r.kj), 0)::bigint as kj,
       coalesce(sum(r.seconds), 0)::bigint as seconds
from rides r
join users u on u.id = r.user_id
join memberships m on m.room_id = r.room_id and m.user_id = r.user_id
where r.room_id = $1
  and r.started_at >= (date_trunc('week', now() at time zone 'UTC') at time zone 'UTC')
  and m.role <> 'banned'
  -- A rider's own opt-out (#1100, amending ADR-0036). The room-level switch
  -- answers "joining a room must not put you on a board"; this answers the
  -- same trap one level up, where the owner turns the board on and everybody
  -- already inside is enrolled by existence.
  and m.on_board
group by r.user_id, u.display_name, u.ftp_watts, u.weight_kg
order by kj desc, u.display_name asc
`

type RoomWeekBoardRow struct {
	UserID      pgtype.UUID
	DisplayName string
	FtpWatts    int16
	WeightKg    int16
	Kj          int64
	Seconds     int64
}

// The room's ordered board (#995, ADR-0036) — opt-in, and THIS WEEK ONLY.
// The week is the streak's week (Monday-start, date_trunc('week')), so a bad
// week is never permanent: RESEARCH.md §14.3 names the stable ordering a
// standing crew cannot re-randomise as the failure mode every cited product
// avoids by resetting. Members only; the handler proves the room, this proves
// the rider is still in it.
func (q *Queries) RoomWeekBoard(ctx context.Context, roomID pgtype.UUID) ([]RoomWeekBoardRow, error) {
	rows, err := q.db.Query(ctx, roomWeekBoard, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoomWeekBoardRow
	for rows.Next() {
		var i RoomWeekBoardRow
		if err := rows.Scan(
			&i.UserID,
			&i.DisplayName,
			&i.FtpWatts,
			&i.WeightKg,
			&i.Kj,
			&i.Seconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRideFtpAfter = `-- name: SetRideFtpAfter :execrows
update rides set ftp_after_watts = $1::smallint
where id = $2 and user_id = $3
`

type SetRideFtpAfterParams struct {
	FtpAfterWatts int16
	ID            pgtype.UUID
	UserID        pgtype.UUID
}

// The number a ramp test produced, on the ramp's own ride (#1572). Owner-only
// by the where clause, so someone else's ride reads as absent rather than as
// forbidden. Last write wins: re-testing the same ride is not a thing, and a
// retried stamp must land on the row it already wrote.
func (q *Queries) SetRideFtpAfter(ctx context.Context, arg SetRideFtpAfterParams) (int64, error) {
	result, err := q.db.Exec(ctx, setRideFtpAfter, arg.FtpAfterWatts, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setRideNormWatts = `-- name: SetRideNormWatts :exec
update rides set norm_watts = $2 where id = $1
`

type SetRideNormWattsParams struct {
	ID        pgtype.UUID
	NormWatts *int16
}

func (q *Queries) SetRideNormWatts(ctx context.Context, arg SetRideNormWattsParams) error {
	_, err := q.db.Exec(ctx, setRideNormWatts, arg.ID, arg.NormWatts)
	return err
}

const setRideShared = `-- name: SetRideShared :execrows
update rides
set shared_at = case when $1::boolean then coalesce(shared_at, now()) else null end
where id = $2 and user_id = $3
`

type SetRideSharedParams struct {
	Shared bool
	ID     pgtype.UUID
	UserID pgtype.UUID
}

// Per-ride opt-in (WATTROOM.md privacy): the owner flips it, the timestamp
// remembers when; unsharing clears it. Owner-only by the where clause.
func (q *Queries) SetRideShared(ctx context.Context, arg SetRideSharedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setRideShared, arg.Shared, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const startRideExport = `-- name: StartRideExport :exec
insert into ride_exports (ride_id, destination, state, attempts, updated_at)
values ($1, $2, 'pending', 0, now())
on conflict (ride_id, destination) do update
    set state = 'pending', updated_at = now()
    where ride_exports.state <> 'delivered'
`

type StartRideExportParams struct {
	RideID      pgtype.UUID
	Destination string
}

// Opens (or re-opens) the delivery record for one ride and destination. A
// retry lands on the same row: one delivery per pair, ever (#799).
func (q *Queries) StartRideExport(ctx context.Context, arg StartRideExportParams) error {
	_, err := q.db.Exec(ctx, startRideExport, arg.RideID, arg.Destination)
	return err
}

const userTotalXp = `-- name: UserTotalXp :one
select user_total_xp($1)::bigint
`

// #253: lifetime XP → level (docs/SPEC.md thresholds, computed client-side).
// Rides plus the off-bike ledger (#467) — user_total_xp is the one definition.
func (q *Queries) UserTotalXp(ctx context.Context, uid pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, userTotalXp, uid)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
