// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rides.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const best20mIn90Days = `-- name: Best20mIn90Days :one
select coalesce(max((curve->>'best20m')::int), 0)::int from rides
where user_id = $1 and started_at >= now() - interval '90 days'
`

// The FTP auto-detect input (docs/SPEC.md): rolling 90-day best 20-minute power.
func (q *Queries) Best20mIn90Days(ctx context.Context, userID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, best20mIn90Days, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createMedal = `-- name: CreateMedal :exec
insert into medals (room_id, user_id, ride_id, kind)
values ($1, $2, $3, $4)
`

type CreateMedalParams struct {
	RoomID pgtype.UUID
	UserID pgtype.UUID
	RideID pgtype.UUID
	Kind   string
}

func (q *Queries) CreateMedal(ctx context.Context, arg CreateMedalParams) error {
	_, err := q.db.Exec(ctx, createMedal,
		arg.RoomID,
		arg.UserID,
		arg.RideID,
		arg.Kind,
	)
	return err
}

const createRide = `-- name: CreateRide :one
insert into rides (
    user_id, room_id, workout_name, started_at,
    seconds, avg_watts, kj, execution, ftp_watts, samples, curve, xp, norm_watts
)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
returning id
`

type CreateRideParams struct {
	UserID      pgtype.UUID
	RoomID      pgtype.UUID
	WorkoutName string
	StartedAt   pgtype.Timestamptz
	Seconds     int32
	AvgWatts    int16
	Kj          int32
	Execution   float32
	FtpWatts    int16
	Samples     []byte
	Curve       []byte
	Xp          int32
	NormWatts   *int16
}

func (q *Queries) CreateRide(ctx context.Context, arg CreateRideParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createRide,
		arg.UserID,
		arg.RoomID,
		arg.WorkoutName,
		arg.StartedAt,
		arg.Seconds,
		arg.AvgWatts,
		arg.Kj,
		arg.Execution,
		arg.FtpWatts,
		arg.Samples,
		arg.Curve,
		arg.Xp,
		arg.NormWatts,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const curveBests = `-- name: CurveBests :one
select
    coalesce(max((curve->>'best5s')::int)  filter (where started_at >= now() - interval '30 days'), 0)::int as d30_best5s,
    coalesce(max((curve->>'best1m')::int)  filter (where started_at >= now() - interval '30 days'), 0)::int as d30_best1m,
    coalesce(max((curve->>'best5m')::int)  filter (where started_at >= now() - interval '30 days'), 0)::int as d30_best5m,
    coalesce(max((curve->>'best20m')::int) filter (where started_at >= now() - interval '30 days'), 0)::int as d30_best20m,
    coalesce(max((curve->>'best5s')::int)  filter (where started_at >= now() - interval '90 days'), 0)::int as d90_best5s,
    coalesce(max((curve->>'best1m')::int)  filter (where started_at >= now() - interval '90 days'), 0)::int as d90_best1m,
    coalesce(max((curve->>'best5m')::int)  filter (where started_at >= now() - interval '90 days'), 0)::int as d90_best5m,
    coalesce(max((curve->>'best20m')::int) filter (where started_at >= now() - interval '90 days'), 0)::int as d90_best20m,
    coalesce(max((curve->>'best5s')::int),  0)::int as all_best5s,
    coalesce(max((curve->>'best1m')::int),  0)::int as all_best1m,
    coalesce(max((curve->>'best5m')::int),  0)::int as all_best5m,
    coalesce(max((curve->>'best20m')::int), 0)::int as all_best20m
from rides
where user_id = $1
`

type CurveBestsRow struct {
	D30Best5s  int32
	D30Best1m  int32
	D30Best5m  int32
	D30Best20m int32
	D90Best5s  int32
	D90Best1m  int32
	D90Best5m  int32
	D90Best20m int32
	AllBest5s  int32
	AllBest1m  int32
	AllBest5m  int32
	AllBest20m int32
}

// Progression overlay (#222): best per SPEC curve window over three ranges,
// summary columns only — the sample blob stays cold.
func (q *Queries) CurveBests(ctx context.Context, userID pgtype.UUID) (CurveBestsRow, error) {
	row := q.db.QueryRow(ctx, curveBests, userID)
	var i CurveBestsRow
	err := row.Scan(
		&i.D30Best5s,
		&i.D30Best1m,
		&i.D30Best5m,
		&i.D30Best20m,
		&i.D90Best5s,
		&i.D90Best1m,
		&i.D90Best5m,
		&i.D90Best20m,
		&i.AllBest5s,
		&i.AllBest1m,
		&i.AllBest5m,
		&i.AllBest20m,
	)
	return i, err
}

const deleteRide = `-- name: DeleteRide :execrows
delete from rides where id = $1 and user_id = $2
`

type DeleteRideParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

// Owner-only by the where clause. The medals awarded for this ride go with
// it through medals.ride_id's on-delete-cascade — no cleanup pass to forget.
func (q *Queries) DeleteRide(ctx context.Context, arg DeleteRideParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRide, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUser = `-- name: DeleteUser :exec
delete from users where id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const failRideExport = `-- name: FailRideExport :exec
update ride_exports
set attempts = attempts + 1,
    last_error = $3,
    state = case when attempts + 1 >= $4::int then 'failed' else 'pending' end,
    updated_at = now()
where ride_id = $1 and destination = $2
`

type FailRideExportParams struct {
	RideID      pgtype.UUID
	Destination string
	LastError   *string
	MaxAttempts int32
}

// One attempt spent. Past the ceiling the row stops being swept and the
// rider is told, rather than retried at forever.
func (q *Queries) FailRideExport(ctx context.Context, arg FailRideExportParams) error {
	_, err := q.db.Exec(ctx, failRideExport,
		arg.RideID,
		arg.Destination,
		arg.LastError,
		arg.MaxAttempts,
	)
	return err
}

const finishRideExport = `-- name: FinishRideExport :exec
update ride_exports
set state = 'delivered', remote_id = $3, last_error = null, updated_at = now()
where ride_id = $1 and destination = $2
`

type FinishRideExportParams struct {
	RideID      pgtype.UUID
	Destination string
	RemoteID    *int64
}

// The remote has it. remote_id is the activity it became.
func (q *Queries) FinishRideExport(ctx context.Context, arg FinishRideExportParams) error {
	_, err := q.db.Exec(ctx, finishRideExport, arg.RideID, arg.Destination, arg.RemoteID)
	return err
}

const getRide = `-- name: GetRide :one
select r.id, r.user_id, r.room_id, r.workout_name, r.started_at, r.seconds, r.avg_watts, r.kj, r.execution, r.ftp_watts, r.samples, r.shared_at, r.created_at, r.curve, r.xp, r.norm_watts,
       coalesce(rm.slug, '')::text as room_slug,
       coalesce(rm.name, '')::text as room_name
from rides r
left join rooms rm on rm.id = r.room_id
where r.id = $1 and r.user_id = $2
`

type GetRideParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type GetRideRow struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	RoomID      pgtype.UUID
	WorkoutName string
	StartedAt   pgtype.Timestamptz
	Seconds     int32
	AvgWatts    int16
	Kj          int32
	Execution   float32
	FtpWatts    int16
	Samples     []byte
	SharedAt    pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	Curve       []byte
	Xp          int32
	NormWatts   *int16
	RoomSlug    string
	RoomName    string
}

// The one per-ride blob read ADR-0016 allows: a rider opening a single ride
// is exactly what the samples are kept for. Owner-scoped, so someone else's
// ride reads as absent rather than as forbidden. The room comes along because
// the detail page names it — empty strings for a solo ride.
func (q *Queries) GetRide(ctx context.Context, arg GetRideParams) (GetRideRow, error) {
	row := q.db.QueryRow(ctx, getRide, arg.ID, arg.UserID)
	var i GetRideRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoomID,
		&i.WorkoutName,
		&i.StartedAt,
		&i.Seconds,
		&i.AvgWatts,
		&i.Kj,
		&i.Execution,
		&i.FtpWatts,
		&i.Samples,
		&i.SharedAt,
		&i.CreatedAt,
		&i.Curve,
		&i.Xp,
		&i.NormWatts,
		&i.RoomSlug,
		&i.RoomName,
	)
	return i, err
}

const getRideExport = `-- name: GetRideExport :one
select state, attempts, last_error, remote_id
from ride_exports
where ride_id = $1 and destination = $2
`

type GetRideExportParams struct {
	RideID      pgtype.UUID
	Destination string
}

type GetRideExportRow struct {
	State     string
	Attempts  int32
	LastError *string
	RemoteID  *int64
}

func (q *Queries) GetRideExport(ctx context.Context, arg GetRideExportParams) (GetRideExportRow, error) {
	row := q.db.QueryRow(ctx, getRideExport, arg.RideID, arg.Destination)
	var i GetRideExportRow
	err := row.Scan(
		&i.State,
		&i.Attempts,
		&i.LastError,
		&i.RemoteID,
	)
	return i, err
}

const getRideForUpload = `-- name: GetRideForUpload :one
select r.id, r.user_id, r.workout_name, r.started_at, r.samples, u.strava_upload
from rides r join users u on u.id = r.user_id
where r.id = $1
`

type GetRideForUploadRow struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	WorkoutName  string
	StartedAt    pgtype.Timestamptz
	Samples      []byte
	StravaUpload bool
}

// The uploader's one read: the ride plus the owner's consent flag.
func (q *Queries) GetRideForUpload(ctx context.Context, id pgtype.UUID) (GetRideForUploadRow, error) {
	row := q.db.QueryRow(ctx, getRideForUpload, id)
	var i GetRideForUploadRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkoutName,
		&i.StartedAt,
		&i.Samples,
		&i.StravaUpload,
	)
	return i, err
}

const getRideSamples = `-- name: GetRideSamples :one
select samples from rides where id = $1 and user_id = $2
`

type GetRideSamplesParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

// One ride's blob, owner-scoped. The export streams these into the zip one
// after another, so peak memory is one blob however long the history is.
func (q *Queries) GetRideSamples(ctx context.Context, arg GetRideSamplesParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getRideSamples, arg.ID, arg.UserID)
	var samples []byte
	err := row.Scan(&samples)
	return samples, err
}

const listRideExportsDue = `-- name: ListRideExportsDue :many
select ride_id, destination, attempts, updated_at
from ride_exports
where state = 'pending' and updated_at < $1::timestamptz
order by updated_at
limit $2::int
`

type ListRideExportsDueParams struct {
	Before  pgtype.Timestamptz
	MaxRows int32
}

type ListRideExportsDueRow struct {
	RideID      pgtype.UUID
	Destination string
	Attempts    int32
	UpdatedAt   pgtype.Timestamptz
}

// The sweep: deliveries still owed a try, quiet for long enough that the last
// failure is not being repeated immediately. Bounded — a backlog drains over
// several sweeps rather than in one burst of uploads.
func (q *Queries) ListRideExportsDue(ctx context.Context, arg ListRideExportsDueParams) ([]ListRideExportsDueRow, error) {
	rows, err := q.db.Query(ctx, listRideExportsDue, arg.Before, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRideExportsDueRow
	for rows.Next() {
		var i ListRideExportsDueRow
		if err := rows.Scan(
			&i.RideID,
			&i.Destination,
			&i.Attempts,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRideMedals = `-- name: ListRideMedals :many
select m.kind, m.awarded_at, rm.name as room_name
from medals m
join rooms rm on rm.id = m.room_id
where m.ride_id = $1
order by m.kind
`

type ListRideMedalsRow struct {
	Kind      string
	AwardedAt pgtype.Timestamptz
	RoomName  string
}

// What one ride won. A medal is always a room's, so the room names itself
// here rather than being looked up a second time.
func (q *Queries) ListRideMedals(ctx context.Context, rideID pgtype.UUID) ([]ListRideMedalsRow, error) {
	rows, err := q.db.Query(ctx, listRideMedals, rideID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRideMedalsRow
	for rows.Next() {
		var i ListRideMedalsRow
		if err := rows.Scan(&i.Kind, &i.AwardedAt, &i.RoomName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRidesMissingNorm = `-- name: ListRidesMissingNorm :many
select id, samples from rides where norm_watts is null limit $1
`

type ListRidesMissingNormRow struct {
	ID      pgtype.UUID
	Samples []byte
}

// The ADR-0016 backfill's read: each blob is read exactly once, then goes
// cold again — the per-ride-read storage rule holds.
func (q *Queries) ListRidesMissingNorm(ctx context.Context, limit int32) ([]ListRidesMissingNormRow, error) {
	rows, err := q.db.Query(ctx, listRidesMissingNorm, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRidesMissingNormRow
	for rows.Next() {
		var i ListRidesMissingNormRow
		if err := rows.Scan(&i.ID, &i.Samples); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomMedals = `-- name: ListRoomMedals :many
select m.kind, m.awarded_at, u.display_name
from medals m
join users u on u.id = m.user_id
where m.room_id = $1
order by m.awarded_at desc
limit $2
`

type ListRoomMedalsParams struct {
	RoomID pgtype.UUID
	Limit  int32
}

type ListRoomMedalsRow struct {
	Kind        string
	AwardedAt   pgtype.Timestamptz
	DisplayName string
}

func (q *Queries) ListRoomMedals(ctx context.Context, arg ListRoomMedalsParams) ([]ListRoomMedalsRow, error) {
	rows, err := q.db.Query(ctx, listRoomMedals, arg.RoomID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomMedalsRow
	for rows.Next() {
		var i ListRoomMedalsRow
		if err := rows.Scan(&i.Kind, &i.AwardedAt, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomRideWeeks = `-- name: ListRoomRideWeeks :many
select distinct date_trunc('week', started_at)::date as week
from rides where room_id = $1
order by week desc
limit 60
`

func (q *Queries) ListRoomRideWeeks(ctx context.Context, roomID pgtype.UUID) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listRoomRideWeeks, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Date
	for rows.Next() {
		var week pgtype.Date
		if err := rows.Scan(&week); err != nil {
			return nil, err
		}
		items = append(items, week)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomSessionDays = `-- name: ListRoomSessionDays :many
select started_at::date as day,
       bool_or(user_id = $1) as attended
from rides
where room_id = $2
group by day
order by day desc
limit 12
`

type ListRoomSessionDaysParams struct {
	ViewerID pgtype.UUID
	RoomID   pgtype.UUID
}

type ListRoomSessionDaysRow struct {
	Day      pgtype.Date
	Attended bool
}

// The room's last sessions, newest first, and whether the caller was in each
// (#995). A day rather than a ride: one evening the crew rode together is one
// dot, however many of them were there. Describes the caller's own turnout and
// nobody else's — RESEARCH.md §14.8 forbids grading attendance.
func (q *Queries) ListRoomSessionDays(ctx context.Context, arg ListRoomSessionDaysParams) ([]ListRoomSessionDaysRow, error) {
	rows, err := q.db.Query(ctx, listRoomSessionDays, arg.ViewerID, arg.RoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomSessionDaysRow
	for rows.Next() {
		var i ListRoomSessionDaysRow
		if err := rows.Scan(&i.Day, &i.Attended); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserProgression = `-- name: ListUserProgression :many
select id, started_at, seconds, kj, execution, ftp_watts,
       coalesce((curve->>'best20m')::int, 0)::int as best20m,
       coalesce(norm_watts, avg_watts)::int as norm_watts
from rides
where user_id = $1 and started_at >= now() - interval '365 days'
order by started_at
limit 1000
`

type ListUserProgressionRow struct {
	ID        pgtype.UUID
	StartedAt pgtype.Timestamptz
	Seconds   int32
	Kj        int32
	Execution float32
	FtpWatts  int16
	Best20m   int32
	NormWatts int32
}

// Per-ride trend rows, oldest first (#222): ftp_watts was captured at ride
// time, so FTP history is free; best20m feeds the Category/w-kg trend.
// norm_watts falls back to avg_watts for rides the backfill has not reached.
func (q *Queries) ListUserProgression(ctx context.Context, userID pgtype.UUID) ([]ListUserProgressionRow, error) {
	rows, err := q.db.Query(ctx, listUserProgression, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserProgressionRow
	for rows.Next() {
		var i ListUserProgressionRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.Seconds,
			&i.Kj,
			&i.Execution,
			&i.FtpWatts,
			&i.Best20m,
			&i.NormWatts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRideWeeks = `-- name: ListUserRideWeeks :many
select distinct date_trunc('week', started_at)::date as week
from rides where user_id = $1
order by week desc
limit 60
`

// Distinct ISO weeks with at least one ride, newest first — the streak input.
func (q *Queries) ListUserRideWeeks(ctx context.Context, userID pgtype.UUID) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listUserRideWeeks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Date
	for rows.Next() {
		var week pgtype.Date
		if err := rows.Scan(&week); err != nil {
			return nil, err
		}
		items = append(items, week)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRides = `-- name: ListUserRides :many
select id, workout_name, started_at, seconds, avg_watts, kj, execution, ftp_watts, xp, room_id, shared_at
from rides
where user_id = $1
order by started_at desc
limit $2
`

type ListUserRidesParams struct {
	UserID pgtype.UUID
	Limit  int32
}

type ListUserRidesRow struct {
	ID          pgtype.UUID
	WorkoutName string
	StartedAt   pgtype.Timestamptz
	Seconds     int32
	AvgWatts    int16
	Kj          int32
	Execution   float32
	FtpWatts    int16
	Xp          int32
	RoomID      pgtype.UUID
	SharedAt    pgtype.Timestamptz
}

// Summary only: the blob stays on disk unless a single ride is opened.
func (q *Queries) ListUserRides(ctx context.Context, arg ListUserRidesParams) ([]ListUserRidesRow, error) {
	rows, err := q.db.Query(ctx, listUserRides, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserRidesRow
	for rows.Next() {
		var i ListUserRidesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutName,
			&i.StartedAt,
			&i.Seconds,
			&i.AvgWatts,
			&i.Kj,
			&i.Execution,
			&i.FtpWatts,
			&i.Xp,
			&i.RoomID,
			&i.SharedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRidesFull = `-- name: ListUserRidesFull :many
select id, workout_name, started_at, seconds, avg_watts, kj, execution,
       ftp_watts, xp, curve
from rides where user_id = $1 order by started_at
`

type ListUserRidesFullRow struct {
	ID          pgtype.UUID
	WorkoutName string
	StartedAt   pgtype.Timestamptz
	Seconds     int32
	AvgWatts    int16
	Kj          int32
	Execution   float32
	FtpWatts    int16
	Xp          int32
	Curve       []byte
}

// Export-all (#35): every ride the rider has, summary columns only. The
// blobs are read one at a time by GetRideSamples below — holding all of them
// at once grows with how long someone has used WattRoom, which is the one
// kind of growth an alpha cannot outrun (#894).
func (q *Queries) ListUserRidesFull(ctx context.Context, userID pgtype.UUID) ([]ListUserRidesFullRow, error) {
	rows, err := q.db.Query(ctx, listUserRidesFull, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserRidesFullRow
	for rows.Next() {
		var i ListUserRidesFullRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutName,
			&i.StartedAt,
			&i.Seconds,
			&i.AvgWatts,
			&i.Kj,
			&i.Execution,
			&i.FtpWatts,
			&i.Xp,
			&i.Curve,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roomCrewTotals = `-- name: RoomCrewTotals :one
select coalesce(sum(seconds), 0)::bigint as seconds,
       count(distinct started_at::date) filter (
         where started_at >= date_trunc('month', now())
       )::bigint as sessions_this_month,
       count(distinct started_at::date) filter (
         where started_at >= date_trunc('month', now()) - interval '1 month'
           and started_at < date_trunc('month', now())
       )::bigint as sessions_last_month
from rides
where room_id = $1
`

type RoomCrewTotalsRow struct {
	Seconds           int64
	SessionsThisMonth int64
	SessionsLastMonth int64
}

// What the crew did together (#995, RESEARCH.md §14.7). Cooperative by
// construction: every figure is a sum or a count over the whole room, so
// nobody is ranked inside any of it. Sessions are counted as distinct days
// rather than rides, because six riders in one session is one session.
func (q *Queries) RoomCrewTotals(ctx context.Context, roomID pgtype.UUID) (RoomCrewTotalsRow, error) {
	row := q.db.QueryRow(ctx, roomCrewTotals, roomID)
	var i RoomCrewTotalsRow
	err := row.Scan(&i.Seconds, &i.SessionsThisMonth, &i.SessionsLastMonth)
	return i, err
}

const roomMonthKj = `-- name: RoomMonthKj :one
select coalesce(sum(kj), 0)::bigint from rides
where room_id = $1 and started_at >= date_trunc('month', now())
`

// The collective challenge number: this month's kJ, together.
func (q *Queries) RoomMonthKj(ctx context.Context, roomID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, roomMonthKj, roomID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const roomWeekBoard = `-- name: RoomWeekBoard :many
select r.user_id,
       u.display_name,
       u.ftp_watts,
       u.weight_kg,
       coalesce(sum(r.kj), 0)::bigint as kj,
       coalesce(sum(r.seconds), 0)::bigint as seconds
from rides r
join users u on u.id = r.user_id
join memberships m on m.room_id = r.room_id and m.user_id = r.user_id
where r.room_id = $1
  and r.started_at >= date_trunc('week', now())
  and m.role <> 'banned'
group by r.user_id, u.display_name, u.ftp_watts, u.weight_kg
order by kj desc, u.display_name asc
`

type RoomWeekBoardRow struct {
	UserID      pgtype.UUID
	DisplayName string
	FtpWatts    int16
	WeightKg    int16
	Kj          int64
	Seconds     int64
}

// The room's ordered board (#995, ADR-0036) — opt-in, and THIS WEEK ONLY.
// The week is the streak's week (Monday-start, date_trunc('week')), so a bad
// week is never permanent: RESEARCH.md §14.3 names the stable ordering a
// standing crew cannot re-randomise as the failure mode every cited product
// avoids by resetting. Members only; the handler proves the room, this proves
// the rider is still in it.
func (q *Queries) RoomWeekBoard(ctx context.Context, roomID pgtype.UUID) ([]RoomWeekBoardRow, error) {
	rows, err := q.db.Query(ctx, roomWeekBoard, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoomWeekBoardRow
	for rows.Next() {
		var i RoomWeekBoardRow
		if err := rows.Scan(
			&i.UserID,
			&i.DisplayName,
			&i.FtpWatts,
			&i.WeightKg,
			&i.Kj,
			&i.Seconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRideNormWatts = `-- name: SetRideNormWatts :exec
update rides set norm_watts = $2 where id = $1
`

type SetRideNormWattsParams struct {
	ID        pgtype.UUID
	NormWatts *int16
}

func (q *Queries) SetRideNormWatts(ctx context.Context, arg SetRideNormWattsParams) error {
	_, err := q.db.Exec(ctx, setRideNormWatts, arg.ID, arg.NormWatts)
	return err
}

const setRideShared = `-- name: SetRideShared :execrows
update rides
set shared_at = case when $1::boolean then coalesce(shared_at, now()) else null end
where id = $2 and user_id = $3
`

type SetRideSharedParams struct {
	Shared bool
	ID     pgtype.UUID
	UserID pgtype.UUID
}

// Per-ride opt-in (WATTROOM.md privacy): the owner flips it, the timestamp
// remembers when; unsharing clears it. Owner-only by the where clause.
func (q *Queries) SetRideShared(ctx context.Context, arg SetRideSharedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setRideShared, arg.Shared, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const startRideExport = `-- name: StartRideExport :exec
insert into ride_exports (ride_id, destination, state, attempts, updated_at)
values ($1, $2, 'pending', 0, now())
on conflict (ride_id, destination) do update
    set state = 'pending', updated_at = now()
    where ride_exports.state <> 'delivered'
`

type StartRideExportParams struct {
	RideID      pgtype.UUID
	Destination string
}

// Opens (or re-opens) the delivery record for one ride and destination. A
// retry lands on the same row: one delivery per pair, ever (#799).
func (q *Queries) StartRideExport(ctx context.Context, arg StartRideExportParams) error {
	_, err := q.db.Exec(ctx, startRideExport, arg.RideID, arg.Destination)
	return err
}

const userTotalXp = `-- name: UserTotalXp :one
select user_total_xp($1)::bigint
`

// #253: lifetime XP → level (docs/SPEC.md thresholds, computed client-side).
// Rides plus the off-bike ledger (#467) — user_total_xp is the one definition.
func (q *Queries) UserTotalXp(ctx context.Context, uid pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, userTotalXp, uid)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
