// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rides.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const best20mIn90Days = `-- name: Best20mIn90Days :one
select coalesce(max((curve->>'best20m')::int), 0)::int from rides
where user_id = $1 and started_at >= now() - interval '90 days'
`

// The FTP auto-detect input (docs/SPEC.md): rolling 90-day best 20-minute power.
func (q *Queries) Best20mIn90Days(ctx context.Context, userID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, best20mIn90Days, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createMedal = `-- name: CreateMedal :exec
insert into medals (room_id, user_id, ride_id, kind)
values ($1, $2, $3, $4)
`

type CreateMedalParams struct {
	RoomID pgtype.UUID
	UserID pgtype.UUID
	RideID pgtype.UUID
	Kind   string
}

func (q *Queries) CreateMedal(ctx context.Context, arg CreateMedalParams) error {
	_, err := q.db.Exec(ctx, createMedal,
		arg.RoomID,
		arg.UserID,
		arg.RideID,
		arg.Kind,
	)
	return err
}

const createRide = `-- name: CreateRide :one
insert into rides (
    user_id, room_id, workout_name, started_at,
    seconds, avg_watts, kj, execution, ftp_watts, samples, curve, xp, norm_watts
)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
returning id
`

type CreateRideParams struct {
	UserID      pgtype.UUID
	RoomID      pgtype.UUID
	WorkoutName string
	StartedAt   pgtype.Timestamptz
	Seconds     int32
	AvgWatts    int16
	Kj          int32
	Execution   float32
	FtpWatts    int16
	Samples     []byte
	Curve       []byte
	Xp          int32
	NormWatts   *int16
}

func (q *Queries) CreateRide(ctx context.Context, arg CreateRideParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createRide,
		arg.UserID,
		arg.RoomID,
		arg.WorkoutName,
		arg.StartedAt,
		arg.Seconds,
		arg.AvgWatts,
		arg.Kj,
		arg.Execution,
		arg.FtpWatts,
		arg.Samples,
		arg.Curve,
		arg.Xp,
		arg.NormWatts,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const curveBests = `-- name: CurveBests :one
select
    coalesce(max((curve->>'best5s')::int)  filter (where started_at >= now() - interval '30 days'), 0)::int as d30_best5s,
    coalesce(max((curve->>'best1m')::int)  filter (where started_at >= now() - interval '30 days'), 0)::int as d30_best1m,
    coalesce(max((curve->>'best5m')::int)  filter (where started_at >= now() - interval '30 days'), 0)::int as d30_best5m,
    coalesce(max((curve->>'best20m')::int) filter (where started_at >= now() - interval '30 days'), 0)::int as d30_best20m,
    coalesce(max((curve->>'best5s')::int)  filter (where started_at >= now() - interval '90 days'), 0)::int as d90_best5s,
    coalesce(max((curve->>'best1m')::int)  filter (where started_at >= now() - interval '90 days'), 0)::int as d90_best1m,
    coalesce(max((curve->>'best5m')::int)  filter (where started_at >= now() - interval '90 days'), 0)::int as d90_best5m,
    coalesce(max((curve->>'best20m')::int) filter (where started_at >= now() - interval '90 days'), 0)::int as d90_best20m,
    coalesce(max((curve->>'best5s')::int),  0)::int as all_best5s,
    coalesce(max((curve->>'best1m')::int),  0)::int as all_best1m,
    coalesce(max((curve->>'best5m')::int),  0)::int as all_best5m,
    coalesce(max((curve->>'best20m')::int), 0)::int as all_best20m
from rides
where user_id = $1
`

type CurveBestsRow struct {
	D30Best5s  int32
	D30Best1m  int32
	D30Best5m  int32
	D30Best20m int32
	D90Best5s  int32
	D90Best1m  int32
	D90Best5m  int32
	D90Best20m int32
	AllBest5s  int32
	AllBest1m  int32
	AllBest5m  int32
	AllBest20m int32
}

// Progression overlay (#222): best per SPEC curve window over three ranges,
// summary columns only — the sample blob stays cold.
func (q *Queries) CurveBests(ctx context.Context, userID pgtype.UUID) (CurveBestsRow, error) {
	row := q.db.QueryRow(ctx, curveBests, userID)
	var i CurveBestsRow
	err := row.Scan(
		&i.D30Best5s,
		&i.D30Best1m,
		&i.D30Best5m,
		&i.D30Best20m,
		&i.D90Best5s,
		&i.D90Best1m,
		&i.D90Best5m,
		&i.D90Best20m,
		&i.AllBest5s,
		&i.AllBest1m,
		&i.AllBest5m,
		&i.AllBest20m,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
delete from users where id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getRide = `-- name: GetRide :one
select id, user_id, room_id, workout_name, started_at, seconds, avg_watts, kj, execution, ftp_watts, samples, shared_at, created_at, curve, xp, norm_watts from rides where id = $1 and user_id = $2
`

type GetRideParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetRide(ctx context.Context, arg GetRideParams) (Ride, error) {
	row := q.db.QueryRow(ctx, getRide, arg.ID, arg.UserID)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoomID,
		&i.WorkoutName,
		&i.StartedAt,
		&i.Seconds,
		&i.AvgWatts,
		&i.Kj,
		&i.Execution,
		&i.FtpWatts,
		&i.Samples,
		&i.SharedAt,
		&i.CreatedAt,
		&i.Curve,
		&i.Xp,
		&i.NormWatts,
	)
	return i, err
}

const getRideForUpload = `-- name: GetRideForUpload :one
select r.id, r.user_id, r.workout_name, r.started_at, r.samples, u.strava_upload
from rides r join users u on u.id = r.user_id
where r.id = $1
`

type GetRideForUploadRow struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	WorkoutName  string
	StartedAt    pgtype.Timestamptz
	Samples      []byte
	StravaUpload bool
}

// The uploader's one read: the ride plus the owner's consent flag.
func (q *Queries) GetRideForUpload(ctx context.Context, id pgtype.UUID) (GetRideForUploadRow, error) {
	row := q.db.QueryRow(ctx, getRideForUpload, id)
	var i GetRideForUploadRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkoutName,
		&i.StartedAt,
		&i.Samples,
		&i.StravaUpload,
	)
	return i, err
}

const listRidesMissingNorm = `-- name: ListRidesMissingNorm :many
select id, samples from rides where norm_watts is null limit $1
`

type ListRidesMissingNormRow struct {
	ID      pgtype.UUID
	Samples []byte
}

// The ADR-0016 backfill's read: each blob is read exactly once, then goes
// cold again — the per-ride-read storage rule holds.
func (q *Queries) ListRidesMissingNorm(ctx context.Context, limit int32) ([]ListRidesMissingNormRow, error) {
	rows, err := q.db.Query(ctx, listRidesMissingNorm, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRidesMissingNormRow
	for rows.Next() {
		var i ListRidesMissingNormRow
		if err := rows.Scan(&i.ID, &i.Samples); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomMedals = `-- name: ListRoomMedals :many
select m.kind, m.awarded_at, u.display_name
from medals m
join users u on u.id = m.user_id
where m.room_id = $1
order by m.awarded_at desc
limit $2
`

type ListRoomMedalsParams struct {
	RoomID pgtype.UUID
	Limit  int32
}

type ListRoomMedalsRow struct {
	Kind        string
	AwardedAt   pgtype.Timestamptz
	DisplayName string
}

func (q *Queries) ListRoomMedals(ctx context.Context, arg ListRoomMedalsParams) ([]ListRoomMedalsRow, error) {
	rows, err := q.db.Query(ctx, listRoomMedals, arg.RoomID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomMedalsRow
	for rows.Next() {
		var i ListRoomMedalsRow
		if err := rows.Scan(&i.Kind, &i.AwardedAt, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomRideWeeks = `-- name: ListRoomRideWeeks :many
select distinct date_trunc('week', started_at)::date as week
from rides where room_id = $1
order by week desc
limit 60
`

func (q *Queries) ListRoomRideWeeks(ctx context.Context, roomID pgtype.UUID) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listRoomRideWeeks, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Date
	for rows.Next() {
		var week pgtype.Date
		if err := rows.Scan(&week); err != nil {
			return nil, err
		}
		items = append(items, week)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserProgression = `-- name: ListUserProgression :many
select id, started_at, seconds, kj, execution, ftp_watts,
       coalesce((curve->>'best20m')::int, 0)::int as best20m,
       coalesce(norm_watts, avg_watts)::int as norm_watts
from rides
where user_id = $1 and started_at >= now() - interval '365 days'
order by started_at
limit 1000
`

type ListUserProgressionRow struct {
	ID        pgtype.UUID
	StartedAt pgtype.Timestamptz
	Seconds   int32
	Kj        int32
	Execution float32
	FtpWatts  int16
	Best20m   int32
	NormWatts int32
}

// Per-ride trend rows, oldest first (#222): ftp_watts was captured at ride
// time, so FTP history is free; best20m feeds the Category/w-kg trend.
// norm_watts falls back to avg_watts for rides the backfill has not reached.
func (q *Queries) ListUserProgression(ctx context.Context, userID pgtype.UUID) ([]ListUserProgressionRow, error) {
	rows, err := q.db.Query(ctx, listUserProgression, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserProgressionRow
	for rows.Next() {
		var i ListUserProgressionRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.Seconds,
			&i.Kj,
			&i.Execution,
			&i.FtpWatts,
			&i.Best20m,
			&i.NormWatts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRideWeeks = `-- name: ListUserRideWeeks :many
select distinct date_trunc('week', started_at)::date as week
from rides where user_id = $1
order by week desc
limit 60
`

// Distinct ISO weeks with at least one ride, newest first — the streak input.
func (q *Queries) ListUserRideWeeks(ctx context.Context, userID pgtype.UUID) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listUserRideWeeks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Date
	for rows.Next() {
		var week pgtype.Date
		if err := rows.Scan(&week); err != nil {
			return nil, err
		}
		items = append(items, week)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRides = `-- name: ListUserRides :many
select id, workout_name, started_at, seconds, avg_watts, kj, execution, ftp_watts, xp, room_id, shared_at
from rides
where user_id = $1
order by started_at desc
limit $2
`

type ListUserRidesParams struct {
	UserID pgtype.UUID
	Limit  int32
}

type ListUserRidesRow struct {
	ID          pgtype.UUID
	WorkoutName string
	StartedAt   pgtype.Timestamptz
	Seconds     int32
	AvgWatts    int16
	Kj          int32
	Execution   float32
	FtpWatts    int16
	Xp          int32
	RoomID      pgtype.UUID
	SharedAt    pgtype.Timestamptz
}

// Summary only: the blob stays on disk unless a single ride is opened.
func (q *Queries) ListUserRides(ctx context.Context, arg ListUserRidesParams) ([]ListUserRidesRow, error) {
	rows, err := q.db.Query(ctx, listUserRides, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserRidesRow
	for rows.Next() {
		var i ListUserRidesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutName,
			&i.StartedAt,
			&i.Seconds,
			&i.AvgWatts,
			&i.Kj,
			&i.Execution,
			&i.FtpWatts,
			&i.Xp,
			&i.RoomID,
			&i.SharedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRidesFull = `-- name: ListUserRidesFull :many
select id, user_id, room_id, workout_name, started_at, seconds, avg_watts, kj, execution, ftp_watts, samples, shared_at, created_at, curve, xp, norm_watts from rides where user_id = $1 order by started_at
`

// Export-all (#35): everything, blobs included — this is the one query
// allowed to read every blob, because the rider is taking their data home.
func (q *Queries) ListUserRidesFull(ctx context.Context, userID pgtype.UUID) ([]Ride, error) {
	rows, err := q.db.Query(ctx, listUserRidesFull, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ride
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RoomID,
			&i.WorkoutName,
			&i.StartedAt,
			&i.Seconds,
			&i.AvgWatts,
			&i.Kj,
			&i.Execution,
			&i.FtpWatts,
			&i.Samples,
			&i.SharedAt,
			&i.CreatedAt,
			&i.Curve,
			&i.Xp,
			&i.NormWatts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roomMonthKj = `-- name: RoomMonthKj :one
select coalesce(sum(kj), 0)::bigint from rides
where room_id = $1 and started_at >= date_trunc('month', now())
`

// The collective challenge number: this month's kJ, together.
func (q *Queries) RoomMonthKj(ctx context.Context, roomID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, roomMonthKj, roomID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const setRideNormWatts = `-- name: SetRideNormWatts :exec
update rides set norm_watts = $2 where id = $1
`

type SetRideNormWattsParams struct {
	ID        pgtype.UUID
	NormWatts *int16
}

func (q *Queries) SetRideNormWatts(ctx context.Context, arg SetRideNormWattsParams) error {
	_, err := q.db.Exec(ctx, setRideNormWatts, arg.ID, arg.NormWatts)
	return err
}

const setRideShared = `-- name: SetRideShared :execrows
update rides
set shared_at = case when $1::boolean then coalesce(shared_at, now()) else null end
where id = $2 and user_id = $3
`

type SetRideSharedParams struct {
	Shared bool
	ID     pgtype.UUID
	UserID pgtype.UUID
}

// Per-ride opt-in (WATTROOM.md privacy): the owner flips it, the timestamp
// remembers when; unsharing clears it. Owner-only by the where clause.
func (q *Queries) SetRideShared(ctx context.Context, arg SetRideSharedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setRideShared, arg.Shared, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const userTotalXp = `-- name: UserTotalXp :one
select coalesce(sum(xp), 0)::bigint from rides where user_id = $1
`

// #253: lifetime XP → level (docs/SPEC.md thresholds, computed client-side).
func (q *Queries) UserTotalXp(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, userTotalXp, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
