// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: riders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRiderMedalsInCommon = `-- name: CountRiderMedalsInCommon :many
select m.kind, count(*)::bigint as count
from medals m
join memberships a on a.room_id = m.room_id and a.user_id = $1 and a.role != 'banned'
join memberships b on b.room_id = m.room_id and b.user_id = $2 and b.role != 'banned'
where m.user_id = $1
group by m.kind
order by m.kind
`

type CountRiderMedalsInCommonParams struct {
	Rider  pgtype.UUID
	Viewer pgtype.UUID
}

type CountRiderMedalsInCommonRow struct {
	Kind  string
	Count int64
}

// Medals the rider earned in rooms the viewer shares with them, by kind.
// Rooms they have since left are not "rooms you share" any more.
func (q *Queries) CountRiderMedalsInCommon(ctx context.Context, arg CountRiderMedalsInCommonParams) ([]CountRiderMedalsInCommonRow, error) {
	rows, err := q.db.Query(ctx, countRiderMedalsInCommon, arg.Rider, arg.Viewer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountRiderMedalsInCommonRow
	for rows.Next() {
		var i CountRiderMedalsInCommonRow
		if err := rows.Scan(&i.Kind, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomsInCommon = `-- name: ListRoomsInCommon :many

select r.id, r.slug, r.name
from rooms r
join memberships a on a.room_id = r.id and a.user_id = $1 and a.role != 'banned'
join memberships b on b.room_id = r.id and b.user_id = $2 and b.role != 'banned'
order by r.name
`

type ListRoomsInCommonParams struct {
	Rider  pgtype.UUID
	Viewer pgtype.UUID
}

type ListRoomsInCommonRow struct {
	ID   pgtype.UUID
	Slug string
	Name string
}

// A rider's page (ADR-0024): what rooms already see, plus what the rider
// chose to share. Every query here takes the viewer as well as the rider,
// because the room boundary decides what comes back.
// Rooms where both hold a live (non-banned) membership — the gate for the
// whole page, and the scope of the medals shown on it.
func (q *Queries) ListRoomsInCommon(ctx context.Context, arg ListRoomsInCommonParams) ([]ListRoomsInCommonRow, error) {
	rows, err := q.db.Query(ctx, listRoomsInCommon, arg.Rider, arg.Viewer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomsInCommonRow
	for rows.Next() {
		var i ListRoomsInCommonRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedRides = `-- name: ListSharedRides :many
select r.id, r.workout_name, r.started_at, r.seconds, r.kj, r.execution,
       (r.room_id is not null)::boolean as in_room,
       coalesce(case when v.user_id is not null then rm.name end, '')::text as room_name,
       coalesce((select string_agg(m.kind, ' ' order by m.kind) from medals m where m.ride_id = r.id), '')::text as medal_kinds
from rides r
left join rooms rm on rm.id = r.room_id
left join memberships v on v.room_id = r.room_id and v.user_id = $1 and v.role != 'banned'
where r.user_id = $2 and r.shared_at is not null
order by r.started_at desc
limit $3
`

type ListSharedRidesParams struct {
	Viewer pgtype.UUID
	Rider  pgtype.UUID
	Max    int32
}

type ListSharedRidesRow struct {
	ID          pgtype.UUID
	WorkoutName string
	StartedAt   pgtype.Timestamptz
	Seconds     int32
	Kj          int32
	Execution   float32
	InRoom      bool
	RoomName    string
	MedalKinds  string
}

// The rides the rider marked shared, newest first — friends only. The room
// is named only when the viewer is a member of it (ADR-0012: friendship
// never pierces the room boundary); otherwise the ride just "was in a room".
func (q *Queries) ListSharedRides(ctx context.Context, arg ListSharedRidesParams) ([]ListSharedRidesRow, error) {
	rows, err := q.db.Query(ctx, listSharedRides, arg.Viewer, arg.Rider, arg.Max)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSharedRidesRow
	for rows.Next() {
		var i ListSharedRidesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutName,
			&i.StartedAt,
			&i.Seconds,
			&i.Kj,
			&i.Execution,
			&i.InRoom,
			&i.RoomName,
			&i.MedalKinds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const riderMonth = `-- name: RiderMonth :one
select count(*)::bigint as rides,
       coalesce(sum(seconds), 0)::bigint as seconds,
       coalesce(sum(kj), 0)::bigint as kj
from rides
where user_id = $1 and started_at >= date_trunc('month', now())
`

type RiderMonthRow struct {
	Rides   int64
	Seconds int64
	Kj      int64
}

// This month's totals — friends only (ADR-0024).
func (q *Queries) RiderMonth(ctx context.Context, userID pgtype.UUID) (RiderMonthRow, error) {
	row := q.db.QueryRow(ctx, riderMonth, userID)
	var i RiderMonthRow
	err := row.Scan(&i.Rides, &i.Seconds, &i.Kj)
	return i, err
}

const riderTotals = `-- name: RiderTotals :one
select count(*)::bigint as rides,
       coalesce(sum(kj), 0)::bigint as total_kj,
       coalesce(sum(xp), 0)::bigint as total_xp
from rides where user_id = $1
`

type RiderTotalsRow struct {
	Rides   int64
	TotalKj int64
	TotalXp int64
}

// Lifetime: XP (level), energy (kJ) and the ride count. Sums only — no
// watts, no heart rate, nothing per ride.
func (q *Queries) RiderTotals(ctx context.Context, userID pgtype.UUID) (RiderTotalsRow, error) {
	row := q.db.QueryRow(ctx, riderTotals, userID)
	var i RiderTotalsRow
	err := row.Scan(&i.Rides, &i.TotalKj, &i.TotalXp)
	return i, err
}
