// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOwnedRooms = `-- name: CountOwnedRooms :one
select count(*) from rooms where owner_id = $1
`

func (q *Queries) CountOwnedRooms(ctx context.Context, ownerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOwnedRooms, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRoomMembers = `-- name: CountRoomMembers :one
select count(*) from memberships where room_id = $1 and role != 'banned'
`

func (q *Queries) CountRoomMembers(ctx context.Context, roomID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRoomMembers, roomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMembership = `-- name: CreateMembership :exec
insert into memberships (room_id, user_id, role)
values ($1, $2, $3)
on conflict (room_id, user_id) do nothing
`

type CreateMembershipParams struct {
	RoomID pgtype.UUID
	UserID pgtype.UUID
	Role   string
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) error {
	_, err := q.db.Exec(ctx, createMembership, arg.RoomID, arg.UserID, arg.Role)
	return err
}

const createRoom = `-- name: CreateRoom :one
insert into rooms (code, slug, name, owner_id)
values ($1, $2, $3, $4)
returning id, code, slug, name, owner_id, listed, created_at, sound_pack, icon, cheers, ics_token
`

type CreateRoomParams struct {
	Code    string
	Slug    string
	Name    string
	OwnerID pgtype.UUID
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.Code,
		arg.Slug,
		arg.Name,
		arg.OwnerID,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Slug,
		&i.Name,
		&i.OwnerID,
		&i.Listed,
		&i.CreatedAt,
		&i.SoundPack,
		&i.Icon,
		&i.Cheers,
		&i.IcsToken,
	)
	return i, err
}

const createScheduledSession = `-- name: CreateScheduledSession :one
insert into scheduled_sessions (room_id, workout_name, workout_json, starts_at, created_by)
values ($1, $2, $3, $4, $5) returning id, room_id, workout_name, workout_json, starts_at, created_by, created_at
`

type CreateScheduledSessionParams struct {
	RoomID      pgtype.UUID
	WorkoutName string
	WorkoutJson []byte
	StartsAt    pgtype.Timestamptz
	CreatedBy   pgtype.UUID
}

func (q *Queries) CreateScheduledSession(ctx context.Context, arg CreateScheduledSessionParams) (ScheduledSession, error) {
	row := q.db.QueryRow(ctx, createScheduledSession,
		arg.RoomID,
		arg.WorkoutName,
		arg.WorkoutJson,
		arg.StartsAt,
		arg.CreatedBy,
	)
	var i ScheduledSession
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.WorkoutName,
		&i.WorkoutJson,
		&i.StartsAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMembership = `-- name: DeleteMembership :exec
delete from memberships where room_id = $1 and user_id = $2
`

type DeleteMembershipParams struct {
	RoomID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteMembership, arg.RoomID, arg.UserID)
	return err
}

const deleteRoom = `-- name: DeleteRoom :exec
delete from rooms where id = $1
`

// Memberships and medals cascade; rides keep their history (room_id set null).
func (q *Queries) DeleteRoom(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoom, id)
	return err
}

const deleteScheduledSession = `-- name: DeleteScheduledSession :one
delete from scheduled_sessions where id = $1 and room_id = $2
returning workout_name
`

type DeleteScheduledSessionParams struct {
	ID     pgtype.UUID
	RoomID pgtype.UUID
}

// Returns the name so the room's timeline can say which plan went (#359).
func (q *Queries) DeleteScheduledSession(ctx context.Context, arg DeleteScheduledSessionParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteScheduledSession, arg.ID, arg.RoomID)
	var workout_name string
	err := row.Scan(&workout_name)
	return workout_name, err
}

const getMembership = `-- name: GetMembership :one
select room_id, user_id, role, joined_at from memberships where room_id = $1 and user_id = $2
`

type GetMembershipParams struct {
	RoomID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.RoomID, arg.UserID)
	var i Membership
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getRoomByCode = `-- name: GetRoomByCode :one
select id, code, slug, name, owner_id, listed, created_at, sound_pack, icon, cheers, ics_token from rooms where code = $1
`

func (q *Queries) GetRoomByCode(ctx context.Context, code string) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByCode, code)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Slug,
		&i.Name,
		&i.OwnerID,
		&i.Listed,
		&i.CreatedAt,
		&i.SoundPack,
		&i.Icon,
		&i.Cheers,
		&i.IcsToken,
	)
	return i, err
}

const getRoomBySlug = `-- name: GetRoomBySlug :one
select id, code, slug, name, owner_id, listed, created_at, sound_pack, icon, cheers, ics_token from rooms where slug = $1
`

func (q *Queries) GetRoomBySlug(ctx context.Context, slug string) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomBySlug, slug)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Slug,
		&i.Name,
		&i.OwnerID,
		&i.Listed,
		&i.CreatedAt,
		&i.SoundPack,
		&i.Icon,
		&i.Cheers,
		&i.IcsToken,
	)
	return i, err
}

const listRoomCalendar = `-- name: ListRoomCalendar :many
select s.id, s.workout_name, s.workout_json, s.starts_at, s.created_at,
       u.display_name as created_by
from scheduled_sessions s
join users u on u.id = s.created_by
where s.room_id = $1 and s.starts_at > now() - interval '30 days'
order by s.starts_at
`

type ListRoomCalendarRow struct {
	ID          pgtype.UUID
	WorkoutName string
	WorkoutJson []byte
	StartsAt    pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	CreatedBy   string
}

// The iCal feed (#245): unlike the in-room list, it keeps a month of history
// and has no cap — a calendar that self-erases reads as broken.
func (q *Queries) ListRoomCalendar(ctx context.Context, roomID pgtype.UUID) ([]ListRoomCalendarRow, error) {
	rows, err := q.db.Query(ctx, listRoomCalendar, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomCalendarRow
	for rows.Next() {
		var i ListRoomCalendarRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutName,
			&i.WorkoutJson,
			&i.StartsAt,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomMembers = `-- name: ListRoomMembers :many
select u.id, u.display_name, u.avatar_url, u.ftp_watts, u.weight_kg, u.created_at, u.strava_upload, u.email, u.notify_planned, u.unsub_token, u.friend_code, u.avatar_preset, u.ics_token, u.accent_palette, u.color_scheme, m.role, m.joined_at,
    user_total_xp(u.id)::bigint as total_xp
from memberships m
join users u on u.id = m.user_id
where m.room_id = $1
order by m.joined_at
`

type ListRoomMembersRow struct {
	ID            pgtype.UUID
	DisplayName   string
	AvatarUrl     *string
	FtpWatts      int16
	WeightKg      int16
	CreatedAt     pgtype.Timestamptz
	StravaUpload  bool
	Email         *string
	NotifyPlanned bool
	UnsubToken    pgtype.UUID
	FriendCode    string
	AvatarPreset  *string
	IcsToken      string
	AccentPalette *string
	ColorScheme   *string
	Role          string
	JoinedAt      pgtype.Timestamptz
	TotalXp       int64
}

func (q *Queries) ListRoomMembers(ctx context.Context, roomID pgtype.UUID) ([]ListRoomMembersRow, error) {
	rows, err := q.db.Query(ctx, listRoomMembers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomMembersRow
	for rows.Next() {
		var i ListRoomMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.FtpWatts,
			&i.WeightKg,
			&i.CreatedAt,
			&i.StravaUpload,
			&i.Email,
			&i.NotifyPlanned,
			&i.UnsubToken,
			&i.FriendCode,
			&i.AvatarPreset,
			&i.IcsToken,
			&i.AccentPalette,
			&i.ColorScheme,
			&i.Role,
			&i.JoinedAt,
			&i.TotalXp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomUpcoming = `-- name: ListRoomUpcoming :many
select s.id, s.workout_name, s.workout_json, s.starts_at, u.display_name as created_by
from scheduled_sessions s
join users u on u.id = s.created_by
where s.room_id = $1 and s.starts_at > now() - interval '30 minutes'
order by s.starts_at
limit 10
`

type ListRoomUpcomingRow struct {
	ID          pgtype.UUID
	WorkoutName string
	WorkoutJson []byte
	StartsAt    pgtype.Timestamptz
	CreatedBy   string
}

// Grace of 30 min: a plan stays visible (and startable) a little past its
// time, then falls off — no cron, the read is the cleanup.
func (q *Queries) ListRoomUpcoming(ctx context.Context, roomID pgtype.UUID) ([]ListRoomUpcomingRow, error) {
	rows, err := q.db.Query(ctx, listRoomUpcoming, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomUpcomingRow
	for rows.Next() {
		var i ListRoomUpcomingRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutName,
			&i.WorkoutJson,
			&i.StartsAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserCalendar = `-- name: ListUserCalendar :many
select s.id, s.workout_name, s.workout_json, s.starts_at, s.created_at,
       u.display_name as created_by, r.name as room_name, r.slug as room_slug,
       m.role as your_role
from scheduled_sessions s
join rooms r on r.id = s.room_id
join memberships m on m.room_id = s.room_id and m.user_id = $1 and m.role <> 'banned'
join users u on u.id = s.created_by
where s.starts_at > $2
order by s.starts_at
`

type ListUserCalendarParams struct {
	UserID   pgtype.UUID
	StartsAt pgtype.Timestamptz
}

type ListUserCalendarRow struct {
	ID          pgtype.UUID
	WorkoutName string
	WorkoutJson []byte
	StartsAt    pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	CreatedBy   string
	RoomName    string
	RoomSlug    string
	YourRole    string
}

// Every room the rider is in, one list (#325). $2 is the horizon and is the
// only difference between the two callers: the iCal feed keeps a month of
// history, the sessions page starts at the same 30-minute grace the in-room
// list uses. Uncapped — a calendar that self-erases reads as broken.
func (q *Queries) ListUserCalendar(ctx context.Context, arg ListUserCalendarParams) ([]ListUserCalendarRow, error) {
	rows, err := q.db.Query(ctx, listUserCalendar, arg.UserID, arg.StartsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserCalendarRow
	for rows.Next() {
		var i ListUserCalendarRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutName,
			&i.WorkoutJson,
			&i.StartsAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.RoomName,
			&i.RoomSlug,
			&i.YourRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRooms = `-- name: ListUserRooms :many
select r.id, r.code, r.slug, r.name, r.owner_id, r.listed, r.created_at, r.sound_pack, r.icon, r.cheers, r.ics_token, m.role
from memberships m
join rooms r on r.id = m.room_id
where m.user_id = $1 and m.role != 'banned'
order by m.joined_at desc
`

type ListUserRoomsRow struct {
	ID        pgtype.UUID
	Code      string
	Slug      string
	Name      string
	OwnerID   pgtype.UUID
	Listed    bool
	CreatedAt pgtype.Timestamptz
	SoundPack string
	Icon      string
	Cheers    string
	IcsToken  string
	Role      string
}

// Banned members keep their row (the ban IS the row) but the room vanishes
// from their nav.
func (q *Queries) ListUserRooms(ctx context.Context, userID pgtype.UUID) ([]ListUserRoomsRow, error) {
	rows, err := q.db.Query(ctx, listUserRooms, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserRoomsRow
	for rows.Next() {
		var i ListUserRoomsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Slug,
			&i.Name,
			&i.OwnerID,
			&i.Listed,
			&i.CreatedAt,
			&i.SoundPack,
			&i.Icon,
			&i.Cheers,
			&i.IcsToken,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextRoomSession = `-- name: NextRoomSession :one
select workout_name, starts_at from scheduled_sessions
where room_id = $1 and starts_at > now() - interval '30 minutes'
order by starts_at limit 1
`

type NextRoomSessionRow struct {
	WorkoutName string
	StartsAt    pgtype.Timestamptz
}

func (q *Queries) NextRoomSession(ctx context.Context, roomID pgtype.UUID) (NextRoomSessionRow, error) {
	row := q.db.QueryRow(ctx, nextRoomSession, roomID)
	var i NextRoomSessionRow
	err := row.Scan(&i.WorkoutName, &i.StartsAt)
	return i, err
}

const rescheduleSession = `-- name: RescheduleSession :one
update scheduled_sessions set starts_at = $3
where id = $1 and room_id = $2 returning id, room_id, workout_name, workout_json, starts_at, created_by, created_at
`

type RescheduleSessionParams struct {
	ID       pgtype.UUID
	RoomID   pgtype.UUID
	StartsAt pgtype.Timestamptz
}

func (q *Queries) RescheduleSession(ctx context.Context, arg RescheduleSessionParams) (ScheduledSession, error) {
	row := q.db.QueryRow(ctx, rescheduleSession, arg.ID, arg.RoomID, arg.StartsAt)
	var i ScheduledSession
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.WorkoutName,
		&i.WorkoutJson,
		&i.StartsAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const rotateRoomIcsToken = `-- name: RotateRoomIcsToken :one
update rooms set ics_token = replace(gen_random_uuid()::text, '-', '')
where id = $1 returning ics_token
`

func (q *Queries) RotateRoomIcsToken(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, rotateRoomIcsToken, id)
	var ics_token string
	err := row.Scan(&ics_token)
	return ics_token, err
}

const updateMembershipRole = `-- name: UpdateMembershipRole :exec
update memberships set role = $3 where room_id = $1 and user_id = $2
`

type UpdateMembershipRoleParams struct {
	RoomID pgtype.UUID
	UserID pgtype.UUID
	Role   string
}

func (q *Queries) UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) error {
	_, err := q.db.Exec(ctx, updateMembershipRole, arg.RoomID, arg.UserID, arg.Role)
	return err
}

const updateRoom = `-- name: UpdateRoom :one
update rooms set name = $2, listed = $3, sound_pack = $4, icon = $5, cheers = $6
where id = $1 returning id, code, slug, name, owner_id, listed, created_at, sound_pack, icon, cheers, ics_token
`

type UpdateRoomParams struct {
	ID        pgtype.UUID
	Name      string
	Listed    bool
	SoundPack string
	Icon      string
	Cheers    string
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoom,
		arg.ID,
		arg.Name,
		arg.Listed,
		arg.SoundPack,
		arg.Icon,
		arg.Cheers,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Slug,
		&i.Name,
		&i.OwnerID,
		&i.Listed,
		&i.CreatedAt,
		&i.SoundPack,
		&i.Icon,
		&i.Cheers,
		&i.IcsToken,
	)
	return i, err
}
