// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimSessionsToRemind = `-- name: ClaimSessionsToRemind :many
update scheduled_sessions
set reminded_at = now()
where reminded_at is null
  and starts_at > now()
  and starts_at <= now() + interval '1 hour'
returning id, room_id, workout_name, starts_at
`

type ClaimSessionsToRemindRow struct {
	ID          pgtype.UUID
	RoomID      pgtype.UUID
	WorkoutName string
	StartsAt    pgtype.Timestamptz
}

// The claim IS the update (#841): a row leaves this query already marked, so a
// tick that fires twice, a restart mid-send or a second instance cannot mail
// the same session again. Callers do not mark anything afterwards, which is
// the point — there is no window between reading and claiming to lose a
// process in.
//
// A session whose start slipped past while the server was down falls outside
// the window and is simply never reminded. That is deliberate: a burst of
// "starts in an hour" for sessions that began three hours ago is worse than
// silence.
func (q *Queries) ClaimSessionsToRemind(ctx context.Context) ([]ClaimSessionsToRemindRow, error) {
	rows, err := q.db.Query(ctx, claimSessionsToRemind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimSessionsToRemindRow
	for rows.Next() {
		var i ClaimSessionsToRemindRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.WorkoutName,
			&i.StartsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearRsvp = `-- name: ClearRsvp :exec
delete from session_rsvps where session_id = $1 and user_id = $2
`

type ClearRsvpParams struct {
	SessionID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) ClearRsvp(ctx context.Context, arg ClearRsvpParams) error {
	_, err := q.db.Exec(ctx, clearRsvp, arg.SessionID, arg.UserID)
	return err
}

const countOwnedRooms = `-- name: CountOwnedRooms :one
select count(*) from rooms where owner_id = $1
`

func (q *Queries) CountOwnedRooms(ctx context.Context, ownerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOwnedRooms, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMembership = `-- name: CreateMembership :exec
insert into memberships (room_id, user_id, role)
values ($1, $2, $3)
on conflict (room_id, user_id) do nothing
`

type CreateMembershipParams struct {
	RoomID pgtype.UUID
	UserID pgtype.UUID
	Role   string
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) error {
	_, err := q.db.Exec(ctx, createMembership, arg.RoomID, arg.UserID, arg.Role)
	return err
}

const createRoom = `-- name: CreateRoom :one
insert into rooms (slug, name, owner_id)
values ($1, $2, $3)
returning id, slug, name, owner_id, listed, created_at, sound_pack, icon, cheers, ics_token, autoplay_enabled, autoplay_order, autoplay_playlist_id, autoplay_fixed_video_id, autoplay_fixed_video_title, board_enabled, crew_id, crew_visible
`

type CreateRoomParams struct {
	Slug    string
	Name    string
	OwnerID pgtype.UUID
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom, arg.Slug, arg.Name, arg.OwnerID)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.OwnerID,
		&i.Listed,
		&i.CreatedAt,
		&i.SoundPack,
		&i.Icon,
		&i.Cheers,
		&i.IcsToken,
		&i.AutoplayEnabled,
		&i.AutoplayOrder,
		&i.AutoplayPlaylistID,
		&i.AutoplayFixedVideoID,
		&i.AutoplayFixedVideoTitle,
		&i.BoardEnabled,
		&i.CrewID,
		&i.CrewVisible,
	)
	return i, err
}

const createScheduledSession = `-- name: CreateScheduledSession :one
insert into scheduled_sessions (room_id, workout_name, workout_json, starts_at, created_by)
values ($1, $2, $3, $4, $5) returning id, room_id, workout_name, workout_json, starts_at, created_by, created_at, reminded_at
`

type CreateScheduledSessionParams struct {
	RoomID      pgtype.UUID
	WorkoutName string
	WorkoutJson []byte
	StartsAt    pgtype.Timestamptz
	CreatedBy   pgtype.UUID
}

func (q *Queries) CreateScheduledSession(ctx context.Context, arg CreateScheduledSessionParams) (ScheduledSession, error) {
	row := q.db.QueryRow(ctx, createScheduledSession,
		arg.RoomID,
		arg.WorkoutName,
		arg.WorkoutJson,
		arg.StartsAt,
		arg.CreatedBy,
	)
	var i ScheduledSession
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.WorkoutName,
		&i.WorkoutJson,
		&i.StartsAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RemindedAt,
	)
	return i, err
}

const deleteMembership = `-- name: DeleteMembership :exec
delete from memberships where room_id = $1 and user_id = $2 and role != 'banned'
`

type DeleteMembershipParams struct {
	RoomID pgtype.UUID
	UserID pgtype.UUID
}

// A banned row is the ban (#637): leaving must never delete it, whoever asks.
func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteMembership, arg.RoomID, arg.UserID)
	return err
}

const deleteRoom = `-- name: DeleteRoom :exec
delete from rooms where id = $1
`

// Memberships and medals cascade; rides keep their history (room_id set null).
func (q *Queries) DeleteRoom(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoom, id)
	return err
}

const deleteScheduledSession = `-- name: DeleteScheduledSession :one
delete from scheduled_sessions where id = $1 and room_id = $2
returning workout_name, starts_at
`

type DeleteScheduledSessionParams struct {
	ID     pgtype.UUID
	RoomID pgtype.UUID
}

type DeleteScheduledSessionRow struct {
	WorkoutName string
	StartsAt    pgtype.Timestamptz
}

// Returns the name so the room's timeline can say which plan went (#359), and
// the time so the cancellation mail can say which session it was and skip one
// that has already been and gone (#839).
func (q *Queries) DeleteScheduledSession(ctx context.Context, arg DeleteScheduledSessionParams) (DeleteScheduledSessionRow, error) {
	row := q.db.QueryRow(ctx, deleteScheduledSession, arg.ID, arg.RoomID)
	var i DeleteScheduledSessionRow
	err := row.Scan(&i.WorkoutName, &i.StartsAt)
	return i, err
}

const getMembership = `-- name: GetMembership :one
select room_id, user_id, role, joined_at, notify, on_board from memberships where room_id = $1 and user_id = $2
`

type GetMembershipParams struct {
	RoomID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.RoomID, arg.UserID)
	var i Membership
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.Notify,
		&i.OnBoard,
	)
	return i, err
}

const getRoomByID = `-- name: GetRoomByID :one
select id, slug, name, owner_id, listed, created_at, sound_pack, icon, cheers, ics_token, autoplay_enabled, autoplay_order, autoplay_playlist_id, autoplay_fixed_video_id, autoplay_fixed_video_title, board_enabled, crew_id, crew_visible from rooms where id = $1
`

func (q *Queries) GetRoomByID(ctx context.Context, id pgtype.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.OwnerID,
		&i.Listed,
		&i.CreatedAt,
		&i.SoundPack,
		&i.Icon,
		&i.Cheers,
		&i.IcsToken,
		&i.AutoplayEnabled,
		&i.AutoplayOrder,
		&i.AutoplayPlaylistID,
		&i.AutoplayFixedVideoID,
		&i.AutoplayFixedVideoTitle,
		&i.BoardEnabled,
		&i.CrewID,
		&i.CrewVisible,
	)
	return i, err
}

const getRoomBySlug = `-- name: GetRoomBySlug :one
select id, slug, name, owner_id, listed, created_at, sound_pack, icon, cheers, ics_token, autoplay_enabled, autoplay_order, autoplay_playlist_id, autoplay_fixed_video_id, autoplay_fixed_video_title, board_enabled, crew_id, crew_visible from rooms where slug = $1
`

func (q *Queries) GetRoomBySlug(ctx context.Context, slug string) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomBySlug, slug)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.OwnerID,
		&i.Listed,
		&i.CreatedAt,
		&i.SoundPack,
		&i.Icon,
		&i.Cheers,
		&i.IcsToken,
		&i.AutoplayEnabled,
		&i.AutoplayOrder,
		&i.AutoplayPlaylistID,
		&i.AutoplayFixedVideoID,
		&i.AutoplayFixedVideoTitle,
		&i.BoardEnabled,
		&i.CrewID,
		&i.CrewVisible,
	)
	return i, err
}

const getRoomsBySlugs = `-- name: GetRoomsBySlugs :many
select id, slug, name, owner_id, listed, created_at, sound_pack, icon, cheers, ics_token, autoplay_enabled, autoplay_order, autoplay_playlist_id, autoplay_fixed_video_id, autoplay_fixed_video_title, board_enabled, crew_id, crew_visible from rooms where slug = any($1::text[])
`

// Batched sibling of GetRoomBySlug (#687): the friends panel resolves every
// online friend's room in one query instead of one per friend.
func (q *Queries) GetRoomsBySlugs(ctx context.Context, slugs []string) ([]Room, error) {
	rows, err := q.db.Query(ctx, getRoomsBySlugs, slugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.OwnerID,
			&i.Listed,
			&i.CreatedAt,
			&i.SoundPack,
			&i.Icon,
			&i.Cheers,
			&i.IcsToken,
			&i.AutoplayEnabled,
			&i.AutoplayOrder,
			&i.AutoplayPlaylistID,
			&i.AutoplayFixedVideoID,
			&i.AutoplayFixedVideoTitle,
			&i.BoardEnabled,
			&i.CrewID,
			&i.CrewVisible,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listListedRooms = `-- name: ListListedRooms :many
select r.slug, r.name, r.icon
from rooms r
where r.listed
order by r.name asc, r.slug asc
limit $2 offset $1
`

type ListListedRoomsParams struct {
	Off int32
	Lim int32
}

type ListListedRoomsRow struct {
	Slug string
	Name string
	Icon string
}

// The opt-in public directory (#1118, ADR-0039). Every room whose owner has
// chosen to be findable, and NOTHING ELSE ABOUT THEM.
//
// The columns are the whole disclosure decision, so they are the thing to
// read twice: name, icon, slug. No member count, no activity, no owner, no
// last-ridden. A directory entry is a way to find the door, not a window —
// and #1025 is still open on whether a room-MATE may see the counts behind a
// badge, which settles it for a stranger who has not joined at all.
//
// Adding a column here later widens what strangers see and is a decision.
// Removing one narrows it and breaks a promise already made. The narrow
// version is the one that can still move.
//
// Ordered by name because there is no other honest order: "most active" and
// "biggest" are the disclosures this deliberately does not make.
func (q *Queries) ListListedRooms(ctx context.Context, arg ListListedRoomsParams) ([]ListListedRoomsRow, error) {
	rows, err := q.db.Query(ctx, listListedRooms, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListListedRoomsRow
	for rows.Next() {
		var i ListListedRoomsRow
		if err := rows.Scan(&i.Slug, &i.Name, &i.Icon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsForUser = `-- name: ListMembershipsForUser :many
select room_id, user_id, role, joined_at, notify, on_board from memberships where user_id = $1 and room_id = any($2::uuid[])
`

type ListMembershipsForUserParams struct {
	UserID  pgtype.UUID
	RoomIds []pgtype.UUID
}

// Batched sibling of GetMembership (#687): one query for every room a
// viewer's online friends are in, instead of one membership check per friend.
func (q *Queries) ListMembershipsForUser(ctx context.Context, arg ListMembershipsForUserParams) ([]Membership, error) {
	rows, err := q.db.Query(ctx, listMembershipsForUser, arg.UserID, arg.RoomIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Membership
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Notify,
			&i.OnBoard,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomCalendar = `-- name: ListRoomCalendar :many
select s.id, s.workout_name, s.workout_json, s.starts_at, s.created_at,
       u.display_name as created_by
from scheduled_sessions s
join users u on u.id = s.created_by
where s.room_id = $1 and s.starts_at > now() - interval '30 days'
order by s.starts_at
`

type ListRoomCalendarRow struct {
	ID          pgtype.UUID
	WorkoutName string
	WorkoutJson []byte
	StartsAt    pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	CreatedBy   string
}

// The iCal feed (#245): unlike the in-room list, it keeps a month of history
// and has no cap — a calendar that self-erases reads as broken.
func (q *Queries) ListRoomCalendar(ctx context.Context, roomID pgtype.UUID) ([]ListRoomCalendarRow, error) {
	rows, err := q.db.Query(ctx, listRoomCalendar, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomCalendarRow
	for rows.Next() {
		var i ListRoomCalendarRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutName,
			&i.WorkoutJson,
			&i.StartsAt,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomMembers = `-- name: ListRoomMembers :many
select u.id, u.display_name, u.avatar_url, u.ftp_watts, u.weight_kg, u.created_at, u.strava_upload, u.email, u.notify_planned, u.unsub_token, u.friend_code, u.avatar_preset, u.ics_token, u.accent_palette, u.color_scheme, u.email_verified_at, u.email_pending, u.email_verify_hash, u.email_verify_expires, u.email_required, u.timezone, m.role, m.joined_at,
    user_total_xp(u.id)::bigint as total_xp,
    coalesce((select array_agg(a.key order by a.earned_at)
              from achievements a where a.user_id = u.id), '{}')::text[] as badges
from memberships m
join users u on u.id = m.user_id
where m.room_id = $1
order by m.joined_at
`

type ListRoomMembersRow struct {
	ID                 pgtype.UUID
	DisplayName        string
	AvatarUrl          *string
	FtpWatts           int16
	WeightKg           int16
	CreatedAt          pgtype.Timestamptz
	StravaUpload       bool
	Email              *string
	NotifyPlanned      bool
	UnsubToken         pgtype.UUID
	FriendCode         string
	AvatarPreset       *string
	IcsToken           string
	AccentPalette      *string
	ColorScheme        *string
	EmailVerifiedAt    pgtype.Timestamptz
	EmailPending       *string
	EmailVerifyHash    []byte
	EmailVerifyExpires pgtype.Timestamptz
	EmailRequired      bool
	Timezone           *string
	Role               string
	JoinedAt           pgtype.Timestamptz
	TotalXp            int64
	Badges             []string
}

// Badges ride along (#703): the room's own page is where a crew compares
// itself, which is the only comparison WATTROOM.md allows. Earned keys
// only — the achievements table holds nothing else, so there is no
// progress here to leak (ADR-0027).
func (q *Queries) ListRoomMembers(ctx context.Context, roomID pgtype.UUID) ([]ListRoomMembersRow, error) {
	rows, err := q.db.Query(ctx, listRoomMembers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomMembersRow
	for rows.Next() {
		var i ListRoomMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.FtpWatts,
			&i.WeightKg,
			&i.CreatedAt,
			&i.StravaUpload,
			&i.Email,
			&i.NotifyPlanned,
			&i.UnsubToken,
			&i.FriendCode,
			&i.AvatarPreset,
			&i.IcsToken,
			&i.AccentPalette,
			&i.ColorScheme,
			&i.EmailVerifiedAt,
			&i.EmailPending,
			&i.EmailVerifyHash,
			&i.EmailVerifyExpires,
			&i.EmailRequired,
			&i.Timezone,
			&i.Role,
			&i.JoinedAt,
			&i.TotalXp,
			&i.Badges,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomRsvps = `-- name: ListRoomRsvps :many
select r.session_id, r.user_id, u.display_name
from session_rsvps r
join users u on u.id = r.user_id
join scheduled_sessions s on s.id = r.session_id
where s.room_id = $1 and s.starts_at > now() - interval '30 minutes'
order by r.created_at
`

type ListRoomRsvpsRow struct {
	SessionID   pgtype.UUID
	UserID      pgtype.UUID
	DisplayName string
}

// Who is in, for everything ListRoomUpcoming returns. Ordered by when they
// said yes, so the first names in the line are the ones who committed first.
func (q *Queries) ListRoomRsvps(ctx context.Context, roomID pgtype.UUID) ([]ListRoomRsvpsRow, error) {
	rows, err := q.db.Query(ctx, listRoomRsvps, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomRsvpsRow
	for rows.Next() {
		var i ListRoomRsvpsRow
		if err := rows.Scan(&i.SessionID, &i.UserID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomUpcoming = `-- name: ListRoomUpcoming :many
select s.id, s.workout_name, s.workout_json, s.starts_at, u.display_name as created_by
from scheduled_sessions s
join users u on u.id = s.created_by
where s.room_id = $1 and s.starts_at > now() - interval '30 minutes'
order by s.starts_at
limit 10
`

type ListRoomUpcomingRow struct {
	ID          pgtype.UUID
	WorkoutName string
	WorkoutJson []byte
	StartsAt    pgtype.Timestamptz
	CreatedBy   string
}

// Grace of 30 min: a plan stays visible (and startable) a little past its
// time, then falls off — no cron, the read is the cleanup.
func (q *Queries) ListRoomUpcoming(ctx context.Context, roomID pgtype.UUID) ([]ListRoomUpcomingRow, error) {
	rows, err := q.db.Query(ctx, listRoomUpcoming, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomUpcomingRow
	for rows.Next() {
		var i ListRoomUpcomingRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutName,
			&i.WorkoutJson,
			&i.StartsAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserCalendar = `-- name: ListUserCalendar :many
select s.id, s.workout_name, s.workout_json, s.starts_at, s.created_at,
       u.display_name as created_by, r.name as room_name, r.slug as room_slug,
       m.role as your_role
from scheduled_sessions s
join rooms r on r.id = s.room_id
join memberships m on m.room_id = s.room_id and m.user_id = $1 and m.role <> 'banned'
join users u on u.id = s.created_by
where s.starts_at > $2
order by s.starts_at
`

type ListUserCalendarParams struct {
	UserID   pgtype.UUID
	StartsAt pgtype.Timestamptz
}

type ListUserCalendarRow struct {
	ID          pgtype.UUID
	WorkoutName string
	WorkoutJson []byte
	StartsAt    pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	CreatedBy   string
	RoomName    string
	RoomSlug    string
	YourRole    string
}

// Every room the rider is in, one list (#325). $2 is the horizon and is the
// only difference between the two callers: the iCal feed keeps a month of
// history, the sessions page starts at the same 30-minute grace the in-room
// list uses. Uncapped — a calendar that self-erases reads as broken.
func (q *Queries) ListUserCalendar(ctx context.Context, arg ListUserCalendarParams) ([]ListUserCalendarRow, error) {
	rows, err := q.db.Query(ctx, listUserCalendar, arg.UserID, arg.StartsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserCalendarRow
	for rows.Next() {
		var i ListUserCalendarRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutName,
			&i.WorkoutJson,
			&i.StartsAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.RoomName,
			&i.RoomSlug,
			&i.YourRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRooms = `-- name: ListUserRooms :many
select r.id, r.slug, r.name, r.owner_id, r.listed, r.created_at, r.sound_pack, r.icon, r.cheers, r.ics_token, r.autoplay_enabled, r.autoplay_order, r.autoplay_playlist_id, r.autoplay_fixed_video_id, r.autoplay_fixed_video_title, r.board_enabled, r.crew_id, r.crew_visible, m.role,
       (select count(*) from memberships mm
         where mm.room_id = r.id and mm.role != 'banned')::bigint as member_count,
       (select count(*)
          from chat_messages cm
          left join room_reads rr on rr.room_id = cm.room_id and rr.user_id = $1
         where cm.room_id = r.id
           and cm.user_id != $1
           and (rr.read_at is null or cm.created_at > rr.read_at))::bigint as unread,
       -- coalesced because the lateral is a LEFT join: sqlc reads the column
       -- as non-null from the schema and would scan a room with nothing
       -- planned into a *string, which fails. next_starts_at carries the
       -- "is there one" answer instead — pgtype handles its NULL.
       coalesce(upcoming.workout_name, '')::text as next_workout_name,
       upcoming.starts_at as next_starts_at,
       -- LastRoomChat's row, per room: the one-line preview that makes a room
       -- sortable next to a DM by recency (#468). last_at carries whether
       -- there is one, so the texts coalesce like the workout name above.
       coalesce(last.text, '')::text as last_chat_text,
       coalesce(last.display_name, '')::text as last_chat_from,
       last.image_id as last_chat_image_id,
       last.created_at as last_chat_at,
       -- The crew this room belongs to (ADR-0038), joined rather than fetched
       -- per room: this query's own comment is about the 1+4N it replaced, and
       -- the sidebar's switcher would have reintroduced exactly that. LEFT,
       -- because crew_id is nullable for one release (ADR-0038's fourth
       -- amendment) and a room without one must still list.
       -- Not c.id: r.* already carries crew_id, and selecting both makes sqlc
       -- name the second one CrewID_2.
       coalesce(c.name, '')::text as crew_name,
       coalesce(c.icon, '')::text as crew_icon,
       (c.image_set_at is not null)::boolean as crew_has_image,
       -- The crew's code rides the rail (#1257): every member may share it.
       coalesce(c.code, '')::text as crew_code,
       -- What the caller is to the crew, for the switcher's owner mark and
       -- the crew page's door (#1147). Two booleans, not a role word: the
       -- LEFT join makes a CASE nullable and sqlc would hand back *string.
       coalesce(c.owner_id = $1, false)::boolean as crew_owned,
       exists (select 1 from crew_roles cr
               where cr.crew_id = r.crew_id and cr.user_id = $1
                 and cr.role = 'admin')::boolean as crew_admin
from memberships m
join rooms r on r.id = m.room_id
left join crews c on c.id = r.crew_id
left join lateral (
    select s.workout_name, s.starts_at
    from scheduled_sessions s
    where s.room_id = r.id and s.starts_at > now() - interval '30 minutes'
    order by s.starts_at
    limit 1
) upcoming on true
left join lateral (
    select cm.text, cm.image_id, cm.created_at, u.display_name
    from chat_messages cm
    join users u on u.id = cm.user_id
    where cm.room_id = r.id
    order by cm.created_at desc
    limit 1
) last on true
where m.user_id = $1 and m.role != 'banned'
  -- The room ban is the membership row; the CREW ban is not, and this list
  -- was the door that still opened after one (#1178). Asked through
  -- visible_rooms rather than by writing the crew-ban predicate out here:
  -- ADR-0038's third amendment makes that view the only place allowed to
  -- answer "is this person excluded here", precisely so a join like this one
  -- cannot quietly disagree with the other five.
  --
  -- Still membership-scoped, deliberately: this is your nav, not everything
  -- you may enter. Crew rooms you have not joined are the switcher's to show.
  and exists (
      select 1 from visible_rooms v
      where v.room_id = r.id and v.user_id = m.user_id
  )
order by m.joined_at desc
`

type ListUserRoomsRow struct {
	ID                      pgtype.UUID
	Slug                    string
	Name                    string
	OwnerID                 pgtype.UUID
	Listed                  bool
	CreatedAt               pgtype.Timestamptz
	SoundPack               string
	Icon                    string
	Cheers                  string
	IcsToken                string
	AutoplayEnabled         bool
	AutoplayOrder           string
	AutoplayPlaylistID      pgtype.UUID
	AutoplayFixedVideoID    string
	AutoplayFixedVideoTitle string
	BoardEnabled            bool
	CrewID                  pgtype.UUID
	CrewVisible             bool
	Role                    string
	MemberCount             int64
	Unread                  int64
	NextWorkoutName         string
	NextStartsAt            pgtype.Timestamptz
	LastChatText            string
	LastChatFrom            string
	LastChatImageID         pgtype.UUID
	LastChatAt              pgtype.Timestamptz
	CrewName                string
	CrewIcon                string
	CrewHasImage            bool
	CrewCode                string
	CrewOwned               bool
	CrewAdmin               bool
}

// Banned members keep their row (the ban IS the row) but the room vanishes
// from their nav.
//
// Everything the rail draws per room comes along here rather than in a loop
// of its own (#890): every presence ping makes every online rider re-run
// this, so it was 1+4N round trips multiplied by the whole fleet. The unread
// predicate is CountRoomUnread's, unchanged — the rail and a single room must
// not be able to disagree about what "new" means.
// NextRoomSession's row, per room. Same 30-minute grace: a plan stays visible
// a little past its time, and the read is the cleanup.
func (q *Queries) ListUserRooms(ctx context.Context, userID pgtype.UUID) ([]ListUserRoomsRow, error) {
	rows, err := q.db.Query(ctx, listUserRooms, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserRoomsRow
	for rows.Next() {
		var i ListUserRoomsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.OwnerID,
			&i.Listed,
			&i.CreatedAt,
			&i.SoundPack,
			&i.Icon,
			&i.Cheers,
			&i.IcsToken,
			&i.AutoplayEnabled,
			&i.AutoplayOrder,
			&i.AutoplayPlaylistID,
			&i.AutoplayFixedVideoID,
			&i.AutoplayFixedVideoTitle,
			&i.BoardEnabled,
			&i.CrewID,
			&i.CrewVisible,
			&i.Role,
			&i.MemberCount,
			&i.Unread,
			&i.NextWorkoutName,
			&i.NextStartsAt,
			&i.LastChatText,
			&i.LastChatFrom,
			&i.LastChatImageID,
			&i.LastChatAt,
			&i.CrewName,
			&i.CrewIcon,
			&i.CrewHasImage,
			&i.CrewCode,
			&i.CrewOwned,
			&i.CrewAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rescheduleSession = `-- name: RescheduleSession :one
update scheduled_sessions set starts_at = $3
where id = $1 and room_id = $2 returning id, room_id, workout_name, workout_json, starts_at, created_by, created_at, reminded_at
`

type RescheduleSessionParams struct {
	ID       pgtype.UUID
	RoomID   pgtype.UUID
	StartsAt pgtype.Timestamptz
}

func (q *Queries) RescheduleSession(ctx context.Context, arg RescheduleSessionParams) (ScheduledSession, error) {
	row := q.db.QueryRow(ctx, rescheduleSession, arg.ID, arg.RoomID, arg.StartsAt)
	var i ScheduledSession
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.WorkoutName,
		&i.WorkoutJson,
		&i.StartsAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RemindedAt,
	)
	return i, err
}

const rotateRoomIcsToken = `-- name: RotateRoomIcsToken :one
update rooms set ics_token = replace(gen_random_uuid()::text, '-', '')
where id = $1 returning ics_token
`

func (q *Queries) RotateRoomIcsToken(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, rotateRoomIcsToken, id)
	var ics_token string
	err := row.Scan(&ics_token)
	return ics_token, err
}

const sessionInRoom = `-- name: SessionInRoom :one
select id from scheduled_sessions where id = $1 and room_id = $2
`

type SessionInRoomParams struct {
	ID     pgtype.UUID
	RoomID pgtype.UUID
}

// A plan belongs to the room in its URL — an RSVP cannot reach across rooms.
func (q *Queries) SessionInRoom(ctx context.Context, arg SessionInRoomParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, sessionInRoom, arg.ID, arg.RoomID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const setMembershipPrefs = `-- name: SetMembershipPrefs :one
update memberships set notify = $3, on_board = $4
where room_id = $1 and user_id = $2
returning notify, on_board
`

type SetMembershipPrefsParams struct {
	RoomID  pgtype.UUID
	UserID  pgtype.UUID
	Notify  bool
	OnBoard bool
}

type SetMembershipPrefsRow struct {
	Notify  bool
	OnBoard bool
}

// A rider's own settings for one room (#1100). Keyed on (room, user), so the
// WHERE clause is the authorization: there is no way to spell another
// rider's preferences, however the caller addresses the request.
func (q *Queries) SetMembershipPrefs(ctx context.Context, arg SetMembershipPrefsParams) (SetMembershipPrefsRow, error) {
	row := q.db.QueryRow(ctx, setMembershipPrefs,
		arg.RoomID,
		arg.UserID,
		arg.Notify,
		arg.OnBoard,
	)
	var i SetMembershipPrefsRow
	err := row.Scan(&i.Notify, &i.OnBoard)
	return i, err
}

const setRsvp = `-- name: SetRsvp :exec
insert into session_rsvps (session_id, user_id) values ($1, $2)
on conflict do nothing
`

type SetRsvpParams struct {
	SessionID pgtype.UUID
	UserID    pgtype.UUID
}

// Room events (#450). Saying yes twice is saying yes.
func (q *Queries) SetRsvp(ctx context.Context, arg SetRsvpParams) error {
	_, err := q.db.Exec(ctx, setRsvp, arg.SessionID, arg.UserID)
	return err
}

const transferRoom = `-- name: TransferRoom :exec
update rooms set owner_id = $2 where id = $1
`

type TransferRoomParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

// The room changes hands (#1227). Always with both membership rows
// rewritten in the same transaction: the owner column and the 'owner'
// role are two answers to one question and must not disagree.
func (q *Queries) TransferRoom(ctx context.Context, arg TransferRoomParams) error {
	_, err := q.db.Exec(ctx, transferRoom, arg.ID, arg.OwnerID)
	return err
}

const updateMembershipRole = `-- name: UpdateMembershipRole :exec
update memberships set role = $3 where room_id = $1 and user_id = $2
`

type UpdateMembershipRoleParams struct {
	RoomID pgtype.UUID
	UserID pgtype.UUID
	Role   string
}

func (q *Queries) UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) error {
	_, err := q.db.Exec(ctx, updateMembershipRole, arg.RoomID, arg.UserID, arg.Role)
	return err
}

const updateRoom = `-- name: UpdateRoom :one
update rooms set name = $2, listed = $3, sound_pack = $4, icon = $5, cheers = $6,
                 board_enabled = $7, crew_visible = $8
where id = $1 returning id, slug, name, owner_id, listed, created_at, sound_pack, icon, cheers, ics_token, autoplay_enabled, autoplay_order, autoplay_playlist_id, autoplay_fixed_video_id, autoplay_fixed_video_title, board_enabled, crew_id, crew_visible
`

type UpdateRoomParams struct {
	ID           pgtype.UUID
	Name         string
	Listed       bool
	SoundPack    string
	Icon         string
	Cheers       string
	BoardEnabled bool
	CrewVisible  bool
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoom,
		arg.ID,
		arg.Name,
		arg.Listed,
		arg.SoundPack,
		arg.Icon,
		arg.Cheers,
		arg.BoardEnabled,
		arg.CrewVisible,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.OwnerID,
		&i.Listed,
		&i.CreatedAt,
		&i.SoundPack,
		&i.Icon,
		&i.Cheers,
		&i.IcsToken,
		&i.AutoplayEnabled,
		&i.AutoplayOrder,
		&i.AutoplayPlaylistID,
		&i.AutoplayFixedVideoID,
		&i.AutoplayFixedVideoTitle,
		&i.BoardEnabled,
		&i.CrewID,
		&i.CrewVisible,
	)
	return i, err
}
