// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRoomMembers = `-- name: CountRoomMembers :one
select count(*) from memberships where room_id = $1
`

func (q *Queries) CountRoomMembers(ctx context.Context, roomID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRoomMembers, roomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMembership = `-- name: CreateMembership :exec
insert into memberships (room_id, user_id, role)
values ($1, $2, $3)
on conflict (room_id, user_id) do nothing
`

type CreateMembershipParams struct {
	RoomID pgtype.UUID
	UserID pgtype.UUID
	Role   string
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) error {
	_, err := q.db.Exec(ctx, createMembership, arg.RoomID, arg.UserID, arg.Role)
	return err
}

const createRoom = `-- name: CreateRoom :one
insert into rooms (code, slug, name, owner_id)
values ($1, $2, $3, $4)
returning id, code, slug, name, owner_id, listed, created_at, sound_pack
`

type CreateRoomParams struct {
	Code    string
	Slug    string
	Name    string
	OwnerID pgtype.UUID
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.Code,
		arg.Slug,
		arg.Name,
		arg.OwnerID,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Slug,
		&i.Name,
		&i.OwnerID,
		&i.Listed,
		&i.CreatedAt,
		&i.SoundPack,
	)
	return i, err
}

const createScheduledSession = `-- name: CreateScheduledSession :one
insert into scheduled_sessions (room_id, workout_name, workout_json, starts_at, created_by)
values ($1, $2, $3, $4, $5) returning id, room_id, workout_name, workout_json, starts_at, created_by, created_at
`

type CreateScheduledSessionParams struct {
	RoomID      pgtype.UUID
	WorkoutName string
	WorkoutJson []byte
	StartsAt    pgtype.Timestamptz
	CreatedBy   pgtype.UUID
}

func (q *Queries) CreateScheduledSession(ctx context.Context, arg CreateScheduledSessionParams) (ScheduledSession, error) {
	row := q.db.QueryRow(ctx, createScheduledSession,
		arg.RoomID,
		arg.WorkoutName,
		arg.WorkoutJson,
		arg.StartsAt,
		arg.CreatedBy,
	)
	var i ScheduledSession
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.WorkoutName,
		&i.WorkoutJson,
		&i.StartsAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMembership = `-- name: DeleteMembership :exec
delete from memberships where room_id = $1 and user_id = $2
`

type DeleteMembershipParams struct {
	RoomID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteMembership, arg.RoomID, arg.UserID)
	return err
}

const deleteRoom = `-- name: DeleteRoom :exec
delete from rooms where id = $1
`

// Memberships and medals cascade; rides keep their history (room_id set null).
func (q *Queries) DeleteRoom(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoom, id)
	return err
}

const deleteScheduledSession = `-- name: DeleteScheduledSession :execrows
delete from scheduled_sessions where id = $1 and room_id = $2
`

type DeleteScheduledSessionParams struct {
	ID     pgtype.UUID
	RoomID pgtype.UUID
}

func (q *Queries) DeleteScheduledSession(ctx context.Context, arg DeleteScheduledSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteScheduledSession, arg.ID, arg.RoomID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMembership = `-- name: GetMembership :one
select room_id, user_id, role, joined_at from memberships where room_id = $1 and user_id = $2
`

type GetMembershipParams struct {
	RoomID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.RoomID, arg.UserID)
	var i Membership
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getRoomByCode = `-- name: GetRoomByCode :one
select id, code, slug, name, owner_id, listed, created_at, sound_pack from rooms where code = $1
`

func (q *Queries) GetRoomByCode(ctx context.Context, code string) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByCode, code)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Slug,
		&i.Name,
		&i.OwnerID,
		&i.Listed,
		&i.CreatedAt,
		&i.SoundPack,
	)
	return i, err
}

const getRoomBySlug = `-- name: GetRoomBySlug :one
select id, code, slug, name, owner_id, listed, created_at, sound_pack from rooms where slug = $1
`

func (q *Queries) GetRoomBySlug(ctx context.Context, slug string) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomBySlug, slug)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Slug,
		&i.Name,
		&i.OwnerID,
		&i.Listed,
		&i.CreatedAt,
		&i.SoundPack,
	)
	return i, err
}

const listRoomMembers = `-- name: ListRoomMembers :many
select u.id, u.display_name, u.avatar_url, u.ftp_watts, u.weight_kg, u.created_at, m.role
from memberships m
join users u on u.id = m.user_id
where m.room_id = $1
order by m.joined_at
`

type ListRoomMembersRow struct {
	ID          pgtype.UUID
	DisplayName string
	AvatarUrl   *string
	FtpWatts    int16
	WeightKg    int16
	CreatedAt   pgtype.Timestamptz
	Role        string
}

func (q *Queries) ListRoomMembers(ctx context.Context, roomID pgtype.UUID) ([]ListRoomMembersRow, error) {
	rows, err := q.db.Query(ctx, listRoomMembers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomMembersRow
	for rows.Next() {
		var i ListRoomMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.FtpWatts,
			&i.WeightKg,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomUpcoming = `-- name: ListRoomUpcoming :many
select s.id, s.workout_name, s.workout_json, s.starts_at, u.display_name as created_by
from scheduled_sessions s
join users u on u.id = s.created_by
where s.room_id = $1 and s.starts_at > now() - interval '30 minutes'
order by s.starts_at
limit 10
`

type ListRoomUpcomingRow struct {
	ID          pgtype.UUID
	WorkoutName string
	WorkoutJson []byte
	StartsAt    pgtype.Timestamptz
	CreatedBy   string
}

// Grace of 30 min: a plan stays visible (and startable) a little past its
// time, then falls off — no cron, the read is the cleanup.
func (q *Queries) ListRoomUpcoming(ctx context.Context, roomID pgtype.UUID) ([]ListRoomUpcomingRow, error) {
	rows, err := q.db.Query(ctx, listRoomUpcoming, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomUpcomingRow
	for rows.Next() {
		var i ListRoomUpcomingRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutName,
			&i.WorkoutJson,
			&i.StartsAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRooms = `-- name: ListUserRooms :many
select r.id, r.code, r.slug, r.name, r.owner_id, r.listed, r.created_at, r.sound_pack
from memberships m
join rooms r on r.id = m.room_id
where m.user_id = $1
order by m.joined_at desc
`

func (q *Queries) ListUserRooms(ctx context.Context, userID pgtype.UUID) ([]Room, error) {
	rows, err := q.db.Query(ctx, listUserRooms, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Slug,
			&i.Name,
			&i.OwnerID,
			&i.Listed,
			&i.CreatedAt,
			&i.SoundPack,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextRoomSession = `-- name: NextRoomSession :one
select workout_name, starts_at from scheduled_sessions
where room_id = $1 and starts_at > now() - interval '30 minutes'
order by starts_at limit 1
`

type NextRoomSessionRow struct {
	WorkoutName string
	StartsAt    pgtype.Timestamptz
}

func (q *Queries) NextRoomSession(ctx context.Context, roomID pgtype.UUID) (NextRoomSessionRow, error) {
	row := q.db.QueryRow(ctx, nextRoomSession, roomID)
	var i NextRoomSessionRow
	err := row.Scan(&i.WorkoutName, &i.StartsAt)
	return i, err
}

const updateMembershipRole = `-- name: UpdateMembershipRole :exec
update memberships set role = $3 where room_id = $1 and user_id = $2
`

type UpdateMembershipRoleParams struct {
	RoomID pgtype.UUID
	UserID pgtype.UUID
	Role   string
}

func (q *Queries) UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) error {
	_, err := q.db.Exec(ctx, updateMembershipRole, arg.RoomID, arg.UserID, arg.Role)
	return err
}

const updateRoom = `-- name: UpdateRoom :one
update rooms set name = $2, listed = $3, sound_pack = $4 where id = $1 returning id, code, slug, name, owner_id, listed, created_at, sound_pack
`

type UpdateRoomParams struct {
	ID        pgtype.UUID
	Name      string
	Listed    bool
	SoundPack string
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoom,
		arg.ID,
		arg.Name,
		arg.Listed,
		arg.SoundPack,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Slug,
		&i.Name,
		&i.OwnerID,
		&i.Listed,
		&i.CreatedAt,
		&i.SoundPack,
	)
	return i, err
}
