// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: routes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRoute = `-- name: CreateRoute :one
insert into routes (
    owner_id, src, name, gen_name, road, road_hash, length_m, gain_m,
    climbs, ele_source, geom_sealed, key_version, road_sealed
)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
returning id, created_at
`

type CreateRouteParams struct {
	OwnerID    pgtype.UUID
	Src        string
	Name       string
	GenName    string
	Road       []byte
	RoadHash   string
	LengthM    int32
	GainM      int32
	Climbs     []byte
	EleSource  string
	GeomSealed []byte
	KeyVersion *int32
	RoadSealed []byte
}

type CreateRouteRow struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) (CreateRouteRow, error) {
	row := q.db.QueryRow(ctx, createRoute,
		arg.OwnerID,
		arg.Src,
		arg.Name,
		arg.GenName,
		arg.Road,
		arg.RoadHash,
		arg.LengthM,
		arg.GainM,
		arg.Climbs,
		arg.EleSource,
		arg.GeomSealed,
		arg.KeyVersion,
		arg.RoadSealed,
	)
	var i CreateRouteRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const deleteRoute = `-- name: DeleteRoute :execrows
delete from routes where id = $1 and owner_id = $2
`

type DeleteRouteParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) DeleteRoute(ctx context.Context, arg DeleteRouteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRoute, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const exportUserRoutes = `-- name: ExportUserRoutes :many
select id, src, name, gen_name, road, length_m, gain_m, climbs, ele_source,
       geom_sealed, key_version, created_at, road_sealed
from routes
where owner_id = $1
order by created_at
limit $2
`

type ExportUserRoutesParams struct {
	UserID pgtype.UUID
	Lim    int32
}

type ExportUserRoutesRow struct {
	ID         pgtype.UUID
	Src        string
	Name       string
	GenName    string
	Road       []byte
	LengthM    int32
	GainM      int32
	Climbs     []byte
	EleSource  string
	GeomSealed []byte
	KeyVersion *int32
	CreatedAt  pgtype.Timestamptz
	RoadSealed []byte
}

// Every route the rider stored, for the export (ADR-0053): the road and the
// sealed place with it, since the GPX is built from both. Bounded like every
// category a rider runs up a row at a time.
func (q *Queries) ExportUserRoutes(ctx context.Context, arg ExportUserRoutesParams) ([]ExportUserRoutesRow, error) {
	rows, err := q.db.Query(ctx, exportUserRoutes, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportUserRoutesRow
	for rows.Next() {
		var i ExportUserRoutesRow
		if err := rows.Scan(
			&i.ID,
			&i.Src,
			&i.Name,
			&i.GenName,
			&i.Road,
			&i.LengthM,
			&i.GainM,
			&i.Climbs,
			&i.EleSource,
			&i.GeomSealed,
			&i.KeyVersion,
			&i.CreatedAt,
			&i.RoadSealed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOwnerRoute = `-- name: GetOwnerRoute :one
select id, src, name, gen_name, road, road_hash, length_m, gain_m, climbs,
       ele_source, (geom_sealed is not null)::boolean as has_place, created_at,
       road_sealed, key_version
from routes
where id = $1 and owner_id = $2
`

type GetOwnerRouteParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

type GetOwnerRouteRow struct {
	ID         pgtype.UUID
	Src        string
	Name       string
	GenName    string
	Road       []byte
	RoadHash   string
	LengthM    int32
	GainM      int32
	Climbs     []byte
	EleSource  string
	HasPlace   bool
	CreatedAt  pgtype.Timestamptz
	RoadSealed []byte
	KeyVersion *int32
}

// One route, the owner's only: someone else's reads as absent.
func (q *Queries) GetOwnerRoute(ctx context.Context, arg GetOwnerRouteParams) (GetOwnerRouteRow, error) {
	row := q.db.QueryRow(ctx, getOwnerRoute, arg.ID, arg.OwnerID)
	var i GetOwnerRouteRow
	err := row.Scan(
		&i.ID,
		&i.Src,
		&i.Name,
		&i.GenName,
		&i.Road,
		&i.RoadHash,
		&i.LengthM,
		&i.GainM,
		&i.Climbs,
		&i.EleSource,
		&i.HasPlace,
		&i.CreatedAt,
		&i.RoadSealed,
		&i.KeyVersion,
	)
	return i, err
}

const getOwnerRoutePlace = `-- name: GetOwnerRoutePlace :one
select geom_sealed, key_version from routes where id = $1 and owner_id = $2
`

type GetOwnerRoutePlaceParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

type GetOwnerRoutePlaceRow struct {
	GeomSealed []byte
	KeyVersion *int32
}

// The sealed place, for its owner alone (ADR-0063) — and for nobody else,
// which the where clause says rather than a caller remembering to.
func (q *Queries) GetOwnerRoutePlace(ctx context.Context, arg GetOwnerRoutePlaceParams) (GetOwnerRoutePlaceRow, error) {
	row := q.db.QueryRow(ctx, getOwnerRoutePlace, arg.ID, arg.OwnerID)
	var i GetOwnerRoutePlaceRow
	err := row.Scan(&i.GeomSealed, &i.KeyVersion)
	return i, err
}

const getRouteGenName = `-- name: GetRouteGenName :one
select gen_name from routes where id = $1
`

// The name a route goes out under beyond its owner (#3055, ADR-0063): the
// generated one, never the owner's rename.
func (q *Queries) GetRouteGenName(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getRouteGenName, id)
	var gen_name string
	err := row.Scan(&gen_name)
	return gen_name, err
}

const getRouteRoad = `-- name: GetRouteRoad :one
select owner_id, src, road, road_sealed, key_version from routes where id = $1
`

type GetRouteRoadRow struct {
	OwnerID    pgtype.UUID
	Src        string
	Road       []byte
	RoadSealed []byte
	KeyVersion *int32
}

// A route's road, its source and whose it is (#3051): what a workout read
// cuts to its reader. Deliberately not owner-scoped — the cut is the
// audience rule, and routes.Attacher is the one place that applies it.
func (q *Queries) GetRouteRoad(ctx context.Context, id pgtype.UUID) (GetRouteRoadRow, error) {
	row := q.db.QueryRow(ctx, getRouteRoad, id)
	var i GetRouteRoadRow
	err := row.Scan(
		&i.OwnerID,
		&i.Src,
		&i.Road,
		&i.RoadSealed,
		&i.KeyVersion,
	)
	return i, err
}

const listOwnerRoutes = `-- name: ListOwnerRoutes :many
select id, src, name, gen_name, length_m, gain_m, climbs,
       (geom_sealed is not null)::boolean as has_place, created_at
from routes
where owner_id = $1
order by created_at desc, id desc
`

type ListOwnerRoutesRow struct {
	ID        pgtype.UUID
	Src       string
	Name      string
	GenName   string
	LengthM   int32
	GainM     int32
	Climbs    []byte
	HasPlace  bool
	CreatedAt pgtype.Timestamptz
}

// The owner's list (#3024): summary columns only — the road and the sealed
// place stay cold until one route is opened.
func (q *Queries) ListOwnerRoutes(ctx context.Context, ownerID pgtype.UUID) ([]ListOwnerRoutesRow, error) {
	rows, err := q.db.Query(ctx, listOwnerRoutes, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOwnerRoutesRow
	for rows.Next() {
		var i ListOwnerRoutesRow
		if err := rows.Scan(
			&i.ID,
			&i.Src,
			&i.Name,
			&i.GenName,
			&i.LengthM,
			&i.GainM,
			&i.Climbs,
			&i.HasPlace,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutesSealedUnder = `-- name: ListRoutesSealedUnder :many
select id, geom_sealed, road_sealed from routes
where key_version = $1
order by id
limit $2
`

type ListRoutesSealedUnderParams struct {
	KeyVersion *int32
	Limit      int32
}

type ListRoutesSealedUnderRow struct {
	ID         pgtype.UUID
	GeomSealed []byte
	RoadSealed []byte
}

// The re-seal's read: a batch of rows sealed under one key version.
func (q *Queries) ListRoutesSealedUnder(ctx context.Context, arg ListRoutesSealedUnderParams) ([]ListRoutesSealedUnderRow, error) {
	rows, err := q.db.Query(ctx, listRoutesSealedUnder, arg.KeyVersion, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoutesSealedUnderRow
	for rows.Next() {
		var i ListRoutesSealedUnderRow
		if err := rows.Scan(&i.ID, &i.GeomSealed, &i.RoadSealed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutesWithRoadInTheClear = `-- name: ListRoutesWithRoadInTheClear :many
select id, road, key_version from routes
where road_sealed is null and id > $1::uuid
order by id
limit $2
`

type ListRoutesWithRoadInTheClearParams struct {
	After pgtype.UUID
	Lim   int32
}

type ListRoutesWithRoadInTheClearRow struct {
	ID         pgtype.UUID
	Road       []byte
	KeyVersion *int32
}

// The boot's sealing of roads stored before #3511, a page at a time by id:
// every row with nothing sealed yet. ponytail: a keyless server's rows never
// leave this list, so each boot reads them again and finds them already
// bare; a marker column is the upgrade once that read shows at boot.
func (q *Queries) ListRoutesWithRoadInTheClear(ctx context.Context, arg ListRoutesWithRoadInTheClearParams) ([]ListRoutesWithRoadInTheClearRow, error) {
	rows, err := q.db.Query(ctx, listRoutesWithRoadInTheClear, arg.After, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoutesWithRoadInTheClearRow
	for rows.Next() {
		var i ListRoutesWithRoadInTheClearRow
		if err := rows.Scan(&i.ID, &i.Road, &i.KeyVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameRoute = `-- name: RenameRoute :execrows
update routes set name = $3 where id = $1 and owner_id = $2
`

type RenameRouteParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
	Name    string
}

func (q *Queries) RenameRoute(ctx context.Context, arg RenameRouteParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameRoute, arg.ID, arg.OwnerID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resealRoute = `-- name: ResealRoute :execrows
update routes set geom_sealed = $1, road_sealed = $2,
       key_version = $3
where id = $4 and key_version = $5
`

type ResealRouteParams struct {
	GeomSealed []byte
	RoadSealed []byte
	NewVersion *int32
	ID         pgtype.UUID
	OldVersion *int32
}

// Only while the row still carries the version it was read under, so a
// concurrent re-seal cannot overwrite a newer seal with an older one.
func (q *Queries) ResealRoute(ctx context.Context, arg ResealRouteParams) (int64, error) {
	result, err := q.db.Exec(ctx, resealRoute,
		arg.GeomSealed,
		arg.RoadSealed,
		arg.NewVersion,
		arg.ID,
		arg.OldVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sealRouteRoad = `-- name: SealRouteRoad :execrows
update routes set road = $1, road_sealed = $2
where id = $3 and road_sealed is null
  and key_version is not distinct from $4
`

type SealRouteRoadParams struct {
	Road       []byte
	RoadSealed []byte
	ID         pgtype.UUID
	KeyVersion *int32
}

// One row's road sealed and stripped, only while it is still as it was read:
// nothing sealed yet, under the same key version.
func (q *Queries) SealRouteRoad(ctx context.Context, arg SealRouteRoadParams) (int64, error) {
	result, err := q.db.Exec(ctx, sealRouteRoad,
		arg.Road,
		arg.RoadSealed,
		arg.ID,
		arg.KeyVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
