// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: status.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearUserStatus = `-- name: ClearUserStatus :exec
update users
set status_emoji = null, status_emoji_id = null, status_text = null, status_expires_at = null
where id = $1
`

func (q *Queries) ClearUserStatus(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearUserStatus, id)
	return err
}

const setUserStatus = `-- name: SetUserStatus :exec

update users
set status_emoji = $1,
    status_emoji_id = $2,
    status_text = $3,
    status_expires_at = $4
where id = $5
`

type SetUserStatusParams struct {
	Emoji     *string
	EmojiID   pgtype.UUID
	Text      *string
	ExpiresAt pgtype.Timestamptz
	ID        pgtype.UUID
}

// A rider's status (ADR-0060, #2694). What the status reads as is decided in
// Go (status.Of): a cleared time in the past is no status, so no statement
// here needs to know the clock.
func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) error {
	_, err := q.db.Exec(ctx, setUserStatus,
		arg.Emoji,
		arg.EmojiID,
		arg.Text,
		arg.ExpiresAt,
		arg.ID,
	)
	return err
}

const statusLinesOf = `-- name: StatusLinesOf :many
select id, status_emoji, status_emoji_id, status_text, status_expires_at
from users
where id = any($1::uuid[])
`

type StatusLinesOfRow struct {
	ID              pgtype.UUID
	StatusEmoji     *string
	StatusEmojiID   pgtype.UUID
	StatusText      *string
	StatusExpiresAt pgtype.Timestamptz
}

// These riders' statuses in one read (#2745): the sidebar's people in a
// crew's voice channels, where the name goes and so the status goes.
func (q *Queries) StatusLinesOf(ctx context.Context, ids []pgtype.UUID) ([]StatusLinesOfRow, error) {
	rows, err := q.db.Query(ctx, statusLinesOf, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatusLinesOfRow
	for rows.Next() {
		var i StatusLinesOfRow
		if err := rows.Scan(
			&i.ID,
			&i.StatusEmoji,
			&i.StatusEmojiID,
			&i.StatusText,
			&i.StatusExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wearableCrewEmoji = `-- name: WearableCrewEmoji :one
select e.name
from crew_emoji e
join crews c on c.id = e.crew_id
where e.id = $1
  and (c.owner_id = $2
       or exists (select 1 from crew_roles cr
                  where cr.crew_id = e.crew_id and cr.user_id = $2
                    and cr.role <> 'banned'))
`

type WearableCrewEmojiParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

// A crew emoji's name, if the rider may wear it: one from a crew they belong
// to (its owner, or a member or admin — never banned). Anything else is no
// row, which the handler answers as a validation error rather than telling a
// rider which crews hold which emoji.
func (q *Queries) WearableCrewEmoji(ctx context.Context, arg WearableCrewEmojiParams) (string, error) {
	row := q.db.QueryRow(ctx, wearableCrewEmoji, arg.ID, arg.UserID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const wornCrewEmojiImage = `-- name: WornCrewEmojiImage :one
select e.mime, e.bytes
from crew_emoji e
where e.id = $1
  and exists (select 1 from users u
              where u.status_emoji_id = e.id
                and (u.status_expires_at is null or u.status_expires_at > now()))
`

type WornCrewEmojiImageRow struct {
	Mime  string
	Bytes []byte
}

// The picture of a crew emoji somebody wears in a status that has not
// cleared (ADR-0060): readable outside its crew for exactly that long.
func (q *Queries) WornCrewEmojiImage(ctx context.Context, id pgtype.UUID) (WornCrewEmojiImageRow, error) {
	row := q.db.QueryRow(ctx, wornCrewEmojiImage, id)
	var i WornCrewEmojiImageRow
	err := row.Scan(&i.Mime, &i.Bytes)
	return i, err
}
