// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tracks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTrack = `-- name: CreateTrack :one
insert into tracks (sha256, uploaded_by, title, artist, album, duration_ms, size_bytes, bpm)
values ($1, $2, $3, $4, $5, $6, $7, $8)
returning id, sha256, uploaded_by, title, artist, album, duration_ms, size_bytes, bpm, created_at
`

type CreateTrackParams struct {
	Sha256     string
	UploadedBy pgtype.UUID
	Title      string
	Artist     string
	Album      string
	DurationMs int32
	SizeBytes  int32
	Bpm        *int16
}

// Content-addressed: a second upload of the same bytes hits the unique index
// on sha256, and the caller reads the existing row instead of storing a copy.
func (q *Queries) CreateTrack(ctx context.Context, arg CreateTrackParams) (Track, error) {
	row := q.db.QueryRow(ctx, createTrack,
		arg.Sha256,
		arg.UploadedBy,
		arg.Title,
		arg.Artist,
		arg.Album,
		arg.DurationMs,
		arg.SizeBytes,
		arg.Bpm,
	)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.UploadedBy,
		&i.Title,
		&i.Artist,
		&i.Album,
		&i.DurationMs,
		&i.SizeBytes,
		&i.Bpm,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTrack = `-- name: DeleteTrack :one
delete from tracks where id = $1 and uploaded_by = $2 returning sha256
`

type DeleteTrackParams struct {
	ID         pgtype.UUID
	UploadedBy pgtype.UUID
}

// Returns the sha so the caller can remove the file it addressed. Uploader
// only; a row that is not yours simply does not match.
func (q *Queries) DeleteTrack(ctx context.Context, arg DeleteTrackParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteTrack, arg.ID, arg.UploadedBy)
	var sha256 string
	err := row.Scan(&sha256)
	return sha256, err
}

const getTrack = `-- name: GetTrack :one
select id, sha256, uploaded_by, title, artist, album, duration_ms, size_bytes, bpm, created_at from tracks where id = $1
`

func (q *Queries) GetTrack(ctx context.Context, id pgtype.UUID) (Track, error) {
	row := q.db.QueryRow(ctx, getTrack, id)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.UploadedBy,
		&i.Title,
		&i.Artist,
		&i.Album,
		&i.DurationMs,
		&i.SizeBytes,
		&i.Bpm,
		&i.CreatedAt,
	)
	return i, err
}

const listTracks = `-- name: ListTracks :many
select t.id, t.sha256, t.uploaded_by, t.title, t.artist, t.album, t.duration_ms, t.size_bytes, t.bpm, t.created_at, u.display_name as uploaded_by_name
from tracks t
join users u on u.id = t.uploaded_by
order by t.created_at desc
limit $1 offset $2
`

type ListTracksParams struct {
	Limit  int32
	Offset int32
}

type ListTracksRow struct {
	ID             pgtype.UUID
	Sha256         string
	UploadedBy     pgtype.UUID
	Title          string
	Artist         string
	Album          string
	DurationMs     int32
	SizeBytes      int32
	Bpm            *int16
	CreatedAt      pgtype.Timestamptz
	UploadedByName string
}

// The pool: one global library every signed-in rider browses (ADR-0015),
// newest first. Carries the uploader's name so a track has a face.
func (q *Queries) ListTracks(ctx context.Context, arg ListTracksParams) ([]ListTracksRow, error) {
	rows, err := q.db.Query(ctx, listTracks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTracksRow
	for rows.Next() {
		var i ListTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Sha256,
			&i.UploadedBy,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.DurationMs,
			&i.SizeBytes,
			&i.Bpm,
			&i.CreatedAt,
			&i.UploadedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trackBySha = `-- name: TrackBySha :one
select id, sha256, uploaded_by, title, artist, album, duration_ms, size_bytes, bpm, created_at from tracks where sha256 = $1
`

func (q *Queries) TrackBySha(ctx context.Context, sha256 string) (Track, error) {
	row := q.db.QueryRow(ctx, trackBySha, sha256)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.UploadedBy,
		&i.Title,
		&i.Artist,
		&i.Album,
		&i.DurationMs,
		&i.SizeBytes,
		&i.Bpm,
		&i.CreatedAt,
	)
	return i, err
}

const trackQuotaUsed = `-- name: TrackQuotaUsed :one
select coalesce(sum(size_bytes), 0)::bigint from tracks where uploaded_by = $1
`

// What this rider's uploads take up. Summed over their own rows, which is
// exact because a deduped upload never created one.
func (q *Queries) TrackQuotaUsed(ctx context.Context, uploadedBy pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, trackQuotaUsed, uploadedBy)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateTrack = `-- name: UpdateTrack :one
update tracks set title = $3, artist = $4, album = $5, bpm = $6
where id = $1 and uploaded_by = $2
returning id, sha256, uploaded_by, title, artist, album, duration_ms, size_bytes, bpm, created_at
`

type UpdateTrackParams struct {
	ID         pgtype.UUID
	UploadedBy pgtype.UUID
	Title      string
	Artist     string
	Album      string
	Bpm        *int16
}

// Every field editable in place: real-world tags are garbage and
// edit-beats-cleanup (ADR-0015). Uploader only — the where clause is the check.
func (q *Queries) UpdateTrack(ctx context.Context, arg UpdateTrackParams) (Track, error) {
	row := q.db.QueryRow(ctx, updateTrack,
		arg.ID,
		arg.UploadedBy,
		arg.Title,
		arg.Artist,
		arg.Album,
		arg.Bpm,
	)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.UploadedBy,
		&i.Title,
		&i.Artist,
		&i.Album,
		&i.DurationMs,
		&i.SizeBytes,
		&i.Bpm,
		&i.CreatedAt,
	)
	return i, err
}
