// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tracks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTrack = `-- name: CreateTrack :one
insert into tracks (sha256, uploaded_by, title, artist, album, duration_ms, size_bytes, bpm, tags)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
returning id, sha256, uploaded_by, title, artist, album, duration_ms, size_bytes, bpm, created_at, search, tags
`

type CreateTrackParams struct {
	Sha256     string
	UploadedBy pgtype.UUID
	Title      string
	Artist     string
	Album      string
	DurationMs int32
	SizeBytes  int32
	Bpm        *int16
	Tags       []string
}

// Content-addressed: a second upload of the same bytes hits the unique index
// on sha256, and the caller reads the existing row instead of storing a copy.
func (q *Queries) CreateTrack(ctx context.Context, arg CreateTrackParams) (Track, error) {
	row := q.db.QueryRow(ctx, createTrack,
		arg.Sha256,
		arg.UploadedBy,
		arg.Title,
		arg.Artist,
		arg.Album,
		arg.DurationMs,
		arg.SizeBytes,
		arg.Bpm,
		arg.Tags,
	)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.UploadedBy,
		&i.Title,
		&i.Artist,
		&i.Album,
		&i.DurationMs,
		&i.SizeBytes,
		&i.Bpm,
		&i.CreatedAt,
		&i.Search,
		&i.Tags,
	)
	return i, err
}

const deleteTrack = `-- name: DeleteTrack :one
delete from tracks where id = $1 and uploaded_by = $2 returning sha256
`

type DeleteTrackParams struct {
	ID         pgtype.UUID
	UploadedBy pgtype.UUID
}

// Returns the sha so the caller can remove the file it addressed. Uploader
// only; a row that is not yours simply does not match.
func (q *Queries) DeleteTrack(ctx context.Context, arg DeleteTrackParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteTrack, arg.ID, arg.UploadedBy)
	var sha256 string
	err := row.Scan(&sha256)
	return sha256, err
}

const getTrack = `-- name: GetTrack :one
select id, sha256, uploaded_by, title, artist, album, duration_ms, size_bytes, bpm, created_at, search, tags from tracks where id = $1
`

func (q *Queries) GetTrack(ctx context.Context, id pgtype.UUID) (Track, error) {
	row := q.db.QueryRow(ctx, getTrack, id)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.UploadedBy,
		&i.Title,
		&i.Artist,
		&i.Album,
		&i.DurationMs,
		&i.SizeBytes,
		&i.Bpm,
		&i.CreatedAt,
		&i.Search,
		&i.Tags,
	)
	return i, err
}

const listTracks = `-- name: ListTracks :many
select t.id, t.sha256, t.uploaded_by, t.title, t.artist, t.album, t.duration_ms, t.size_bytes, t.bpm, t.created_at, t.search, t.tags, u.display_name as uploaded_by_name
from tracks t
join users u on u.id = t.uploaded_by
where ($1::text = ''
       or t.search @@ websearch_to_tsquery('simple', $1::text))
  and ($2::text = '' or $2::text = any(t.tags))
order by
    -- Ranked when there is a query, newest when there is not.
    case when $1::text = '' then 0
         else ts_rank(t.search, websearch_to_tsquery('simple', $1::text))
    end desc,
    t.created_at desc
limit $4 offset $3
`

type ListTracksParams struct {
	Search string
	Tag    string
	Off    int32
	Lim    int32
}

type ListTracksRow struct {
	ID             pgtype.UUID
	Sha256         string
	UploadedBy     pgtype.UUID
	Title          string
	Artist         string
	Album          string
	DurationMs     int32
	SizeBytes      int32
	Bpm            *int16
	CreatedAt      pgtype.Timestamptz
	Search         interface{}
	Tags           []string
	UploadedByName string
}

// The pool: one global library every signed-in rider browses (ADR-0015),
// newest first. Carries the uploader's name so a track has a face.
//
// An empty search returns everything: the browse view and the search view are
// one query, so a rider clearing the box gets the library back rather than a
// second code path that might disagree with the first.
func (q *Queries) ListTracks(ctx context.Context, arg ListTracksParams) ([]ListTracksRow, error) {
	rows, err := q.db.Query(ctx, listTracks,
		arg.Search,
		arg.Tag,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTracksRow
	for rows.Next() {
		var i ListTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Sha256,
			&i.UploadedBy,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.DurationMs,
			&i.SizeBytes,
			&i.Bpm,
			&i.CreatedAt,
			&i.Search,
			&i.Tags,
			&i.UploadedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trackBySha = `-- name: TrackBySha :one
select id, sha256, uploaded_by, title, artist, album, duration_ms, size_bytes, bpm, created_at, search, tags from tracks where sha256 = $1
`

func (q *Queries) TrackBySha(ctx context.Context, sha256 string) (Track, error) {
	row := q.db.QueryRow(ctx, trackBySha, sha256)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.UploadedBy,
		&i.Title,
		&i.Artist,
		&i.Album,
		&i.DurationMs,
		&i.SizeBytes,
		&i.Bpm,
		&i.CreatedAt,
		&i.Search,
		&i.Tags,
	)
	return i, err
}

const trackQuotaUsed = `-- name: TrackQuotaUsed :one
select coalesce(sum(size_bytes), 0)::bigint from tracks where uploaded_by = $1
`

// What this rider's uploads take up. Summed over their own rows, which is
// exact because a deduped upload never created one.
func (q *Queries) TrackQuotaUsed(ctx context.Context, uploadedBy pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, trackQuotaUsed, uploadedBy)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const trackTagCounts = `-- name: TrackTagCounts :many
select tag::text as tag, count(*)::bigint as tracks
from tracks, unnest(tags) as tag
group by tag
order by tracks desc, tag
limit 100
`

type TrackTagCountsRow struct {
	Tag    string
	Tracks int64
}

// The facet row: every tag in the pool with how many tracks wear it.
//
// Counted over the whole pool rather than over the current search, so a rider
// narrowing by text still sees the shelf they can jump to. Cheap enough to run
// beside every list — a pool of a few thousand rows aggregates in under a
// millisecond, and there is no page of tags to paginate.
// The cast is not decoration: without it sqlc types an unnested element as
// `interface{}` and the handler has to assert what the column already is.
func (q *Queries) TrackTagCounts(ctx context.Context) ([]TrackTagCountsRow, error) {
	rows, err := q.db.Query(ctx, trackTagCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackTagCountsRow
	for rows.Next() {
		var i TrackTagCountsRow
		if err := rows.Scan(&i.Tag, &i.Tracks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTrack = `-- name: UpdateTrack :one
update tracks set title = $3, artist = $4, album = $5, bpm = $6, tags = $7
where id = $1 and uploaded_by = $2
returning id, sha256, uploaded_by, title, artist, album, duration_ms, size_bytes, bpm, created_at, search, tags
`

type UpdateTrackParams struct {
	ID         pgtype.UUID
	UploadedBy pgtype.UUID
	Title      string
	Artist     string
	Album      string
	Bpm        *int16
	Tags       []string
}

// Every field editable in place: real-world tags are garbage and
// edit-beats-cleanup (ADR-0015). Uploader only — the where clause is the check.
func (q *Queries) UpdateTrack(ctx context.Context, arg UpdateTrackParams) (Track, error) {
	row := q.db.QueryRow(ctx, updateTrack,
		arg.ID,
		arg.UploadedBy,
		arg.Title,
		arg.Artist,
		arg.Album,
		arg.Bpm,
		arg.Tags,
	)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.UploadedBy,
		&i.Title,
		&i.Artist,
		&i.Album,
		&i.DurationMs,
		&i.SizeBytes,
		&i.Bpm,
		&i.CreatedAt,
		&i.Search,
		&i.Tags,
	)
	return i, err
}
