// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: track_plays.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const recordTrackPlay = `-- name: RecordTrackPlay :exec
insert into track_plays (track_id, room_id, queued_by, skipped)
values ($1, $2, $3, $4)
`

type RecordTrackPlayParams struct {
	TrackID  pgtype.UUID
	RoomID   pgtype.UUID
	QueuedBy pgtype.UUID
	Skipped  bool
}

// One thing a room did with a pool track (#269). Called from outside the
// room lock, after the deck has already moved on — nothing waits on it.
func (q *Queries) RecordTrackPlay(ctx context.Context, arg RecordTrackPlayParams) error {
	_, err := q.db.Exec(ctx, recordTrackPlay,
		arg.TrackID,
		arg.RoomID,
		arg.QueuedBy,
		arg.Skipped,
	)
	return err
}

const smartShuffleTracks = `-- name: SmartShuffleTracks :many
with history as (
    select p.track_id,
        max(p.at) filter (where not p.skipped) as last_played,
        count(*) filter (where p.skipped) as skips
    from track_plays p
    where p.room_id = $1
    group by p.track_id
),
recent as (
    select p.track_id, t.artist, t.tags
    from track_plays p
    join tracks t on t.id = p.track_id
    where p.room_id = $1 and not p.skipped
    order by p.at desc
    limit $8
),
liked as (
    select
        coalesce(array_agg(distinct track_id), '{}') as ids,
        coalesce(array_agg(distinct artist) filter (where artist <> ''), '{}') as artists,
        coalesce(array_agg(distinct tag) filter (where tag is not null), '{}') as tags
    from recent left join lateral unnest(recent.tags) as tag on true
)
select t.id, t.title, t.artist, w.weight
from tracks t
join memberships m on m.user_id = t.uploaded_by and m.room_id = $1
join visible_rooms v on v.room_id = m.room_id and v.user_id = m.user_id
left join history h on h.track_id = t.id
cross join liked l
cross join lateral (
    select (greatest(
        case
            when h.last_played is null then 1.0
            else least(extract(epoch from (now() - h.last_played)) / 14400.0, 1.0)
        end,
        0.05
    ) / (1 + coalesce(h.skips, 0))
    * case
        when $2::float8 <= 0 or t.bpm is null then 1.0
        when abs(t.bpm - $2::float8)
                 <= $2::float8 * $3::float8
          or abs(t.bpm - $2::float8 * 2)
                 <= $2::float8 * 2 * $3::float8
        then $4::float8
        else 1.0
      end
    * case
        -- A track the room just finished matches its OWN artist, and lifting
        -- it here would partly undo the recency penalty that exists to stop
        -- the room hearing it again. Affinity means "more like that one",
        -- never "that one again" — so the recency factor keeps this case.
        when t.id = any(l.ids) then 1.0
        -- A name is a name; a tag is a hint. Checked in that order so a
        -- track that is both does not earn the weaker one. An untitled
        -- artist cannot match another untitled artist: the ` + "`" + `filter` + "`" + ` on
        -- ` + "`" + `liked.artists` + "`" + ` above is what guarantees it, and is the ONLY thing
        -- that does — a second ` + "`" + `t.artist <> ''` + "`" + ` here would read as the
        -- guard while the filter quietly did the work.
        when t.artist = any(l.artists) then $5::float8
        when t.tags && l.tags then $6::float8
        else 1.0
      end)::float8 as weight
) w
order by random() ^ (1.0 / w.weight) desc
limit $7
`

type SmartShuffleTracksParams struct {
	RoomID         pgtype.UUID
	TargetRpm      float64
	BpmTolerance   float64
	BpmBoost       float64
	ArtistBoost    float64
	TagBoost       float64
	Lim            int32
	AffinityWindow int32
}

type SmartShuffleTracksRow struct {
	ID     pgtype.UUID
	Title  string
	Artist string
	Weight float64
}

// ADR-0015's smart selection, all of it, as ONE scoring pass: a weighted
// random draw over the pool where the weight is the product of four factors.
// No second query, no reranking step, no model (the ADR's ponytail ceiling).
//
// The ordering key is `random() ^ (1/weight)` taken descending — weighted
// sampling without replacement (Efraimidis–Spirakis). A plain
// `order by random() * weight` is NOT the same thing: it collapses toward
// picking the heaviest every time, where this draws in proportion.
//
// Weight is `recency × skip × bpm × affinity`, every number from docs/SPEC.md:
//
//	recency:  0.05 the instant a track ends, rising linearly to 1 over 4 h.
//	          The floor is why it is a penalty and not a ban.
//	skip:     divided by one more than the times this room skipped it, so
//	          one skip halves a track's chances and three quarter them.
//	bpm:      a BOOST (#270) for a track whose tempo fits the cadence the
//	          room is turning, at that cadence or at double it — the same
//	          beat, felt one pedal stroke at a time instead of two.
//	affinity: a BOOST (#271) for a track that resembles what this room has
//	          lately played THROUGH — same artist, or a tag in common. Same
//	          artist is the strong signal and earns more: tags are
//	          free-form with no taxonomy (ADR-0015), so a broad one says
//	          much less than a name does. A track the room just finished is
//	          excluded from its own affinity: "more like that", not "that
//	          again", which is what the recency penalty already answers.
//
// Every one of them is a boost or a penalty on a base of 1, so each is
// individually switch-off-able by its own inputs: no session means no BPM
// preference, an empty history means no affinity and no penalties, and a
// room with none of it draws uniformly at random. That is the pre-#269
// behaviour, reached by the arithmetic rather than by a branch.
//
// History is this room's only (privacy is architecture, WATTROOM.md): what
// one room finishes is not a fact about the pool, and must not reach another.
//
// And the POOL it draws from is this room's members' (#1095). Autoplay is the
// one path that reaches for a track nobody asked for by name, so an unscoped
// draw here would put a stranger's upload on the deck without ever appearing
// on a page or in a search — past every check the issue's own list names.
// Members rather than the acting rider: a room's shelf is what its people
// brought, which is already what the room permits (any member may queue their
// own track for everyone). Phase 2 replaces this join with the crew.
// `weight` is returned so a headless autoplay log can say WHY a track came
// up; the ordering is random and unexplainable after the fact otherwise.
// The last few tracks this room let finish. Bounded, and by COUNT rather
// than by time: a room's taste is the last things it enjoyed, and a room
// that rode yesterday should not come back to a blank slate.
// The shelves of the room's own MEMBERS, confirmed on purpose in #1103 over
// the crew: crew membership follows room membership, so a crew-wide draw
// would put a shelf into the rotation of rooms its owner never entered.
// Members who may still enter, through visible_rooms — a crew-banned member
// keeps their row but not their say in what the room plays (ADR-0038).
func (q *Queries) SmartShuffleTracks(ctx context.Context, arg SmartShuffleTracksParams) ([]SmartShuffleTracksRow, error) {
	rows, err := q.db.Query(ctx, smartShuffleTracks,
		arg.RoomID,
		arg.TargetRpm,
		arg.BpmTolerance,
		arg.BpmBoost,
		arg.ArtistBoost,
		arg.TagBoost,
		arg.Lim,
		arg.AffinityWindow,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SmartShuffleTracksRow
	for rows.Next() {
		var i SmartShuffleTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.Weight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
