// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: track_plays.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const recentChannelPlays = `-- name: RecentChannelPlays :many
select p.track_id, p.video_id, p.title, p.skipped,
    coalesce(t.title, '')::text as track_title,
    coalesce(t.artist, '')::text as track_artist,
    coalesce(t.bpm, 0)::int as track_bpm,
    coalesce(t.duration_ms, 0)::int as track_duration_ms,
    coalesce(u.display_name, '')::text as queued_by_name
from track_plays p
left join tracks t on t.id = p.track_id
left join users u on u.id = p.queued_by
where p.channel_id = $1 and (p.track_id is not null or p.video_id <> '')
order by p.at desc
limit $2
`

type RecentChannelPlaysParams struct {
	ChannelID pgtype.UUID
	Limit     int32
}

type RecentChannelPlaysRow struct {
	TrackID         pgtype.UUID
	VideoID         string
	Title           string
	Skipped         bool
	TrackTitle      string
	TrackArtist     string
	TrackBpm        int32
	TrackDurationMs int32
	QueuedByName    string
}

// A voice channel's "just played" as the database remembers it (#1432),
// newest first, both kinds — the channel's own, since each deck is its own
// (ADR-0058). A library row reads the track's current title and artist; a
// deleted file took its rows with it.
func (q *Queries) RecentChannelPlays(ctx context.Context, arg RecentChannelPlaysParams) ([]RecentChannelPlaysRow, error) {
	rows, err := q.db.Query(ctx, recentChannelPlays, arg.ChannelID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentChannelPlaysRow
	for rows.Next() {
		var i RecentChannelPlaysRow
		if err := rows.Scan(
			&i.TrackID,
			&i.VideoID,
			&i.Title,
			&i.Skipped,
			&i.TrackTitle,
			&i.TrackArtist,
			&i.TrackBpm,
			&i.TrackDurationMs,
			&i.QueuedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordTrackPlay = `-- name: RecordTrackPlay :exec
insert into track_plays (track_id, channel_id, queued_by, skipped, video_id, title)
values ($1, $2, $3, $4, $5, $6)
`

type RecordTrackPlayParams struct {
	TrackID   pgtype.UUID
	ChannelID pgtype.UUID
	QueuedBy  pgtype.UUID
	Skipped   bool
	VideoID   string
	Title     string
}

// One thing a voice channel's deck did with a track (#269, #1432, #2439): a
// library track by id or a video by its YouTube id and title. Called from
// outside the hub's lock, after the deck has already moved on — nothing
// waits on it.
func (q *Queries) RecordTrackPlay(ctx context.Context, arg RecordTrackPlayParams) error {
	_, err := q.db.Exec(ctx, recordTrackPlay,
		arg.TrackID,
		arg.ChannelID,
		arg.QueuedBy,
		arg.Skipped,
		arg.VideoID,
		arg.Title,
	)
	return err
}

const smartShuffleTracks = `-- name: SmartShuffleTracks :many
with history as (
    select p.track_id,
        max(p.at) filter (where not p.skipped) as last_played,
        count(*) filter (where p.skipped) as skips
    from track_plays p
    where p.channel_id = $1
    group by p.track_id
),
recent as (
    select p.track_id, t.artist, t.tags
    from track_plays p
    join tracks t on t.id = p.track_id
    where p.channel_id = $1 and not p.skipped
    order by p.at desc
    limit $9
),
liked as (
    select
        coalesce(array_agg(distinct track_id), '{}') as ids,
        coalesce(array_agg(distinct artist) filter (where artist <> ''), '{}') as artists,
        coalesce(array_agg(distinct tag) filter (where tag is not null), '{}') as tags
    from recent left join lateral unnest(recent.tags) as tag on true
)
select t.id, t.title, t.artist, coalesce(t.bpm, 0)::int as bpm, t.duration_ms, w.weight
from tracks t
join channels ch on ch.id = $1
join crews c on c.id = ch.crew_id
left join history h on h.track_id = t.id
cross join liked l
cross join lateral (
    select (greatest(
        case
            when h.last_played is null then 1.0
            else least(extract(epoch from (now() - h.last_played)) / 14400.0, 1.0)
        end,
        0.05
    ) / (1 + coalesce(h.skips, 0))
    * case
        when $2::float8 <= 0 or t.bpm is null then 1.0
        when abs(t.bpm - $2::float8)
                 <= $2::float8 * $3::float8
          or abs(t.bpm - $2::float8 * 2)
                 <= $2::float8 * 2 * $3::float8
        then $4::float8
        else 1.0
      end
    * case
        -- A track the channel just finished matches its OWN artist, and lifting
        -- it here would partly undo the recency penalty that exists to stop
        -- the channel hearing it again. Affinity means "more like that one",
        -- never "that one again" — so the recency factor keeps this case.
        when t.id = any(l.ids) then 1.0
        -- A name is a name; a tag is a hint. Checked in that order so a
        -- track that is both does not earn the weaker one. An untitled
        -- artist cannot match another untitled artist: the ` + "`" + `filter` + "`" + ` on
        -- ` + "`" + `liked.artists` + "`" + ` above is what guarantees it, and is the ONLY thing
        -- that does — a second ` + "`" + `t.artist <> ''` + "`" + ` here would read as the
        -- guard while the filter quietly did the work.
        when t.artist = any(l.artists) then $5::float8
        when t.tags && l.tags then $6::float8
        else 1.0
      end)::float8 as weight
) w
where (t.uploaded_by = c.owner_id
       or exists (
           select 1 from crew_roles cr
           where cr.crew_id = ch.crew_id and cr.user_id = t.uploaded_by
             and (cr.role = 'admin'
                  or (cr.role = 'member'
                      and (not ch.private
                           or exists (select 1 from channel_members cm
                                      where cm.channel_id = ch.id and cm.user_id = t.uploaded_by))))))
  and (coalesce(cardinality($7::uuid[]), 0) = 0
       or t.id = any($7::uuid[]))
order by random() ^ (1.0 / w.weight) desc
limit $8
`

type SmartShuffleTracksParams struct {
	ChannelID      pgtype.UUID
	TargetRpm      float64
	BpmTolerance   float64
	BpmBoost       float64
	ArtistBoost    float64
	TagBoost       float64
	Within         []pgtype.UUID
	Lim            int32
	AffinityWindow int32
}

type SmartShuffleTracksRow struct {
	ID         pgtype.UUID
	Title      string
	Artist     string
	Bpm        int32
	DurationMs int32
	Weight     float64
}

// ADR-0015's smart selection, all of it, as ONE scoring pass: a weighted
// random draw over the pool where the weight is the product of four factors.
// No second query, no reranking step, no model (the ADR's ponytail ceiling).
//
// The ordering key is `random() ^ (1/weight)` taken descending — weighted
// sampling without replacement (Efraimidis–Spirakis). A plain
// `order by random() * weight` is NOT the same thing: it collapses toward
// picking the heaviest every time, where this draws in proportion.
//
// Weight is `recency × skip × bpm × affinity`, every number from docs/SPEC.md:
//
//	recency:  0.05 the instant a track ends, rising linearly to 1 over 4 h.
//	          The floor is why it is a penalty and not a ban.
//	skip:     divided by one more than the times this channel skipped it, so
//	          one skip halves a track's chances and three quarter them.
//	bpm:      a BOOST (#270) for a track whose tempo fits the cadence the
//	          channel is turning, at that cadence or at double it — the same
//	          beat, felt one pedal stroke at a time instead of two.
//	affinity: a BOOST (#271) for a track that resembles what this channel has
//	          lately played THROUGH — same artist, or a tag in common. Same
//	          artist is the strong signal and earns more: tags are
//	          free-form with no taxonomy (ADR-0015), so a broad one says
//	          much less than a name does. A track the channel just finished is
//	          excluded from its own affinity: "more like that", not "that
//	          again", which is what the recency penalty already answers.
//
// Every one of them is a boost or a penalty on a base of 1, so each is
// individually switch-off-able by its own inputs: no session means no BPM
// preference, an empty history means no affinity and no penalties, and a
// channel with none of it draws uniformly at random. That is the pre-#269
// behaviour, reached by the arithmetic rather than by a branch.
//
// History is this voice channel's only (privacy is architecture,
// WATTROOM.md; ADR-0058): what one channel finishes is not a fact about the
// pool, and must not reach another.
//
// And the POOL it draws from is the libraries of the riders who may enter
// this channel (#1095, #2439). Autoplay is the one path that reaches for a
// track nobody asked for by name, so an unscoped draw here would put a
// stranger's upload on the deck without ever appearing on a page or in a
// search. Who may enter is `channels.mayEnter`'s rule, restated here because
// it filters rows: the crew's owner, its admins, and — unless the channel is
// private and they are not named into it — its members; never a banned one.
// It is the same set ADR-0045's audio door lets hear an uploader's track.
// `weight` is returned so a headless autoplay log can say WHY a track came
// up; the ordering is random and unexplainable after the fact otherwise.
// The last few tracks this channel let finish. Bounded, and by COUNT rather
// than by time: a channel's taste is the last things it enjoyed, and one
// that rode yesterday should not come back to a blank slate.
// The shelves of the riders who may enter the channel (see the head of this
// query). A crew-banned rider keeps a crew_roles row and loses their say in
// what the channel plays; a member taken out of a private channel loses it
// there and keeps it in the crew's open ones.
// Smart is an ORDER, not a source (#1429): with an active playlist that holds
// library tracks, the draw is over those and nothing else; `within` is empty
// when no list is active or the list holds no library track, and the draw
// is then the members' whole libraries as before. coalesce, because a nil
// slice arrives as NULL and NULL = 0 is not true.
func (q *Queries) SmartShuffleTracks(ctx context.Context, arg SmartShuffleTracksParams) ([]SmartShuffleTracksRow, error) {
	rows, err := q.db.Query(ctx, smartShuffleTracks,
		arg.ChannelID,
		arg.TargetRpm,
		arg.BpmTolerance,
		arg.BpmBoost,
		arg.ArtistBoost,
		arg.TagBoost,
		arg.Within,
		arg.Lim,
		arg.AffinityWindow,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SmartShuffleTracksRow
	for rows.Next() {
		var i SmartShuffleTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.Bpm,
			&i.DurationMs,
			&i.Weight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
