// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
insert into users (display_name, avatar_url, ftp_watts, weight_kg)
values ($1, $2, $3, $4)
returning id, display_name, avatar_url, ftp_watts, weight_kg, created_at, strava_upload, email, notify_planned, unsub_token, friend_code, avatar_preset, ics_token
`

type CreateUserParams struct {
	DisplayName string
	AvatarUrl   *string
	FtpWatts    int16
	WeightKg    int16
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.FtpWatts,
		arg.WeightKg,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.FtpWatts,
		&i.WeightKg,
		&i.CreatedAt,
		&i.StravaUpload,
		&i.Email,
		&i.NotifyPlanned,
		&i.UnsubToken,
		&i.FriendCode,
		&i.AvatarPreset,
		&i.IcsToken,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
select id, display_name, avatar_url, ftp_watts, weight_kg, created_at, strava_upload, email, notify_planned, unsub_token, friend_code, avatar_preset, ics_token from users where id = $1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.FtpWatts,
		&i.WeightKg,
		&i.CreatedAt,
		&i.StravaUpload,
		&i.Email,
		&i.NotifyPlanned,
		&i.UnsubToken,
		&i.FriendCode,
		&i.AvatarPreset,
		&i.IcsToken,
	)
	return i, err
}

const getUserByIcsToken = `-- name: GetUserByIcsToken :one
select id, display_name, avatar_url, ftp_watts, weight_kg, created_at, strava_upload, email, notify_planned, unsub_token, friend_code, avatar_preset, ics_token from users where ics_token = $1
`

func (q *Queries) GetUserByIcsToken(ctx context.Context, icsToken string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIcsToken, icsToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.FtpWatts,
		&i.WeightKg,
		&i.CreatedAt,
		&i.StravaUpload,
		&i.Email,
		&i.NotifyPlanned,
		&i.UnsubToken,
		&i.FriendCode,
		&i.AvatarPreset,
		&i.IcsToken,
	)
	return i, err
}

const listRoomNotifyTargets = `-- name: ListRoomNotifyTargets :many
select u.id, u.email, u.unsub_token
from memberships m
join users u on u.id = m.user_id
where m.room_id = $1 and u.notify_planned and u.email is not null and u.id <> $2
`

type ListRoomNotifyTargetsParams struct {
	RoomID pgtype.UUID
	ID     pgtype.UUID
}

type ListRoomNotifyTargetsRow struct {
	ID         pgtype.UUID
	Email      *string
	UnsubToken pgtype.UUID
}

// Members who asked for planned-session email — minus the planner, who knows.
func (q *Queries) ListRoomNotifyTargets(ctx context.Context, arg ListRoomNotifyTargetsParams) ([]ListRoomNotifyTargetsRow, error) {
	rows, err := q.db.Query(ctx, listRoomNotifyTargets, arg.RoomID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomNotifyTargetsRow
	for rows.Next() {
		var i ListRoomNotifyTargetsRow
		if err := rows.Scan(&i.ID, &i.Email, &i.UnsubToken); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateUserIcsToken = `-- name: RotateUserIcsToken :one
update users set ics_token = replace(gen_random_uuid()::text, '-', '')
where id = $1 returning ics_token
`

func (q *Queries) RotateUserIcsToken(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, rotateUserIcsToken, id)
	var ics_token string
	err := row.Scan(&ics_token)
	return ics_token, err
}

const unsubscribePlanned = `-- name: UnsubscribePlanned :execrows
update users set notify_planned = false where id = $1 and unsub_token = $2
`

type UnsubscribePlannedParams struct {
	ID         pgtype.UUID
	UnsubToken pgtype.UUID
}

func (q *Queries) UnsubscribePlanned(ctx context.Context, arg UnsubscribePlannedParams) (int64, error) {
	result, err := q.db.Exec(ctx, unsubscribePlanned, arg.ID, arg.UnsubToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserProfile = `-- name: UpdateUserProfile :one
update users
set display_name = $2, ftp_watts = $3, weight_kg = $4, strava_upload = $5,
    email = $6, notify_planned = $7, avatar_preset = $8
where id = $1
returning id, display_name, avatar_url, ftp_watts, weight_kg, created_at, strava_upload, email, notify_planned, unsub_token, friend_code, avatar_preset, ics_token
`

type UpdateUserProfileParams struct {
	ID            pgtype.UUID
	DisplayName   string
	FtpWatts      int16
	WeightKg      int16
	StravaUpload  bool
	Email         *string
	NotifyPlanned bool
	AvatarPreset  *string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.DisplayName,
		arg.FtpWatts,
		arg.WeightKg,
		arg.StravaUpload,
		arg.Email,
		arg.NotifyPlanned,
		arg.AvatarPreset,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.FtpWatts,
		&i.WeightKg,
		&i.CreatedAt,
		&i.StravaUpload,
		&i.Email,
		&i.NotifyPlanned,
		&i.UnsubToken,
		&i.FriendCode,
		&i.AvatarPreset,
		&i.IcsToken,
	)
	return i, err
}
