// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallet.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWalletEvent = `-- name: CreateWalletEvent :execrows
insert into wallet_events (user_id, source, amount, ref)
values ($1, $2, $3, $4)
on conflict (user_id, source, ref) do nothing
`

type CreateWalletEventParams struct {
	UserID pgtype.UUID
	Source string
	Amount int32
	Ref    string
}

// One row per rider per source per ref: a retried save writes nothing twice.
func (q *Queries) CreateWalletEvent(ctx context.Context, arg CreateWalletEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, createWalletEvent,
		arg.UserID,
		arg.Source,
		arg.Amount,
		arg.Ref,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const exportUserWallet = `-- name: ExportUserWallet :many
select source, amount, ref, created_at from wallet_events
where user_id = $1
order by created_at, id
limit $2
`

type ExportUserWalletParams struct {
	UserID pgtype.UUID
	Lim    int32
}

type ExportUserWalletRow struct {
	Source    string
	Amount    int32
	Ref       string
	CreatedAt pgtype.Timestamptz
}

// The ledger as the rider's export carries it (ADR-0053), oldest first.
func (q *Queries) ExportUserWallet(ctx context.Context, arg ExportUserWalletParams) ([]ExportUserWalletRow, error) {
	rows, err := q.db.Query(ctx, exportUserWallet, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportUserWalletRow
	for rows.Next() {
		var i ExportUserWalletRow
		if err := rows.Scan(
			&i.Source,
			&i.Amount,
			&i.Ref,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lastRideBatzen = `-- name: LastRideBatzen :one
select amount from wallet_events
where user_id = $1 and source = 'ride' and amount > 0
order by created_at desc, id desc
limit 1
`

// What the rider's last paid ride paid, for "about one ride like your last
// one" — a ride the day's cap took to 0 is no measure.
func (q *Queries) LastRideBatzen(ctx context.Context, userID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, lastRideBatzen, userID)
	var amount int32
	err := row.Scan(&amount)
	return amount, err
}

const listAccountsWithoutOpening = `-- name: ListAccountsWithoutOpening :many
select u.id from users u
where u.created_at < $1::timestamptz
  and not exists (select 1 from wallet_events w where w.user_id = u.id and w.source = 'opening')
  and not exists (select 1 from identities i where i.user_id = u.id and i.provider = 'synthetic')
`

// Every account the opening job still owes its one grant (ADR-0069): an
// existing rider's, made before the wallet arrived (#3513) — an account made
// since earns by riding, like everyone does from then on. The synthetic
// account is owed nothing.
func (q *Queries) ListAccountsWithoutOpening(ctx context.Context, walletArrived pgtype.Timestamptz) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAccountsWithoutOpening, walletArrived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGroupSession = `-- name: MarkGroupSession :exec
update rides set group_session = $1::boolean
where id = any($2::uuid[])
`

type MarkGroupSessionParams struct {
	GroupSession bool
	Ids          []pgtype.UUID
}

// The save's own answer to "a group session?", kept on each ride it wrote so
// an amendment pays the same × 1.2 (#3517).
func (q *Queries) MarkGroupSession(ctx context.Context, arg MarkGroupSessionParams) error {
	_, err := q.db.Exec(ctx, markGroupSession, arg.GroupSession, arg.Ids)
	return err
}

const openWallet = `-- name: OpenWallet :execrows
insert into wallet_events (user_id, source, amount, ref)
select $1::uuid, 'opening',
       least($2::integer, floor(coalesce(sum(least(
           r.kj * 1000.0 / (r.ftp_watts * 60.0),
           $3::float8 * r.seconds / 60.0)), 0)))::integer,
       'opening'
from rides r
where r.user_id = $1::uuid and r.ftp_watts > 0
  and not exists (
      select 1 from wallet_events w
      where w.user_id = r.user_id and w.source in ('ride', 'ride_grew')
        and (w.ref = r.id::text or w.ref like r.id::text || '@%'))
on conflict (user_id, source, ref) do nothing
`

type OpenWalletParams struct {
	UserID    pgtype.UUID
	GrantCap  int32
	PerMinute float64
}

// One account's opening grant (#3152): min(its history, the cap), where its
// history is the Batzen its rides saved before the wallet would have minted —
// a minute at the ride's own FTP, held to the per-ride ceiling — and a ride
// the wallet already paid counts nothing. Read under the rider's row lock, so
// a ride minting at the same moment cannot be counted twice.
func (q *Queries) OpenWallet(ctx context.Context, arg OpenWalletParams) (int64, error) {
	result, err := q.db.Exec(ctx, openWallet, arg.UserID, arg.GrantCap, arg.PerMinute)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rideGroupSession = `-- name: RideGroupSession :one
select group_session from rides where id = $1
`

func (q *Queries) RideGroupSession(ctx context.Context, id pgtype.UUID) (*bool, error) {
	row := q.db.QueryRow(ctx, rideGroupSession, id)
	var group_session *bool
	err := row.Scan(&group_session)
	return group_session, err
}

const userIsSynthetic = `-- name: UserIsSynthetic :one
select exists (
    select 1 from identities where user_id = $1 and provider = 'synthetic'
)::boolean
`

// The production ride monitor (#153) rides for real and earns nothing.
func (q *Queries) UserIsSynthetic(ctx context.Context, userID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, userIsSynthetic, userID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const walletBalance = `-- name: WalletBalance :one
select user_wallet_balance($1)::bigint
`

func (q *Queries) WalletBalance(ctx context.Context, rider pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, walletBalance, rider)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const walletMintedForRide = `-- name: WalletMintedForRide :one
select coalesce(sum(amount), 0)::integer from wallet_events
where user_id = $1 and source in ('ride', 'ride_grew')
  and (ref = $2::text or ref like $2::text || '@%')
`

type WalletMintedForRideParams struct {
	UserID pgtype.UUID
	Ride   string
}

// What one ride has minted so far: its save and every amendment since.
func (q *Queries) WalletMintedForRide(ctx context.Context, arg WalletMintedForRideParams) (int32, error) {
	row := q.db.QueryRow(ctx, walletMintedForRide, arg.UserID, arg.Ride)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const walletMintedToday = `-- name: WalletMintedToday :one
select coalesce(sum(amount), 0)::integer from wallet_events
where user_id = $1 and source in ('ride', 'ride_grew')
  and created_at >= (date_trunc('day', now() at time zone 'utc') at time zone 'utc')
`

// What riding has minted for this rider in the current UTC day (#3152,
// docs/SPEC.md "Wardrobe": the cap is per UTC day of the save). Read under
// the rider's row lock, so two saves cannot both find room.
func (q *Queries) WalletMintedToday(ctx context.Context, userID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, walletMintedToday, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
