// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wardrobe.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const exportUserWardrobe = `-- name: ExportUserWardrobe :many
select item_id, source, acquired_at, first_worn_at from wardrobe
where user_id = $1
order by acquired_at, item_id
limit $2
`

type ExportUserWardrobeParams struct {
	UserID pgtype.UUID
	Lim    int32
}

type ExportUserWardrobeRow struct {
	ItemID      string
	Source      string
	AcquiredAt  pgtype.Timestamptz
	FirstWornAt pgtype.Timestamptz
}

// What the rider owns, for the export (ADR-0053): by the catalogue's id, how
// it came and when, oldest first. Bounded like every category a rider runs up
// a row at a time.
func (q *Queries) ExportUserWardrobe(ctx context.Context, arg ExportUserWardrobeParams) ([]ExportUserWardrobeRow, error) {
	rows, err := q.db.Query(ctx, exportUserWardrobe, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportUserWardrobeRow
	for rows.Next() {
		var i ExportUserWardrobeRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Source,
			&i.AcquiredAt,
			&i.FirstWornAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserOutfit = `-- name: GetUserOutfit :one
select loadout, updated_at from outfits where user_id = $1
`

type GetUserOutfitRow struct {
	Loadout   []byte
	UpdatedAt pgtype.Timestamptz
}

// What the rider's figure wears (docs/SPEC.md: one owned item per slot).
func (q *Queries) GetUserOutfit(ctx context.Context, userID pgtype.UUID) (GetUserOutfitRow, error) {
	row := q.db.QueryRow(ctx, getUserOutfit, userID)
	var i GetUserOutfitRow
	err := row.Scan(&i.Loadout, &i.UpdatedAt)
	return i, err
}
