// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workouts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUserWorkouts = `-- name: CountUserWorkouts :one
select count(*) from workouts where owner_id = $1
`

// docs/SPEC.md's 200-workout ceiling (#1414). Called with the rider's row
// locked, inside the transaction that inserts — the same shape the owned-room
// cap needed (#1413), because a count followed by an unsynchronised insert is
// not a ceiling, it is a suggestion a burst ignores.
func (q *Queries) CountUserWorkouts(ctx context.Context, ownerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserWorkouts, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkout = `-- name: CreateWorkout :one
insert into workouts (owner_id, name, author, definition)
values ($1, $2, $3, $4)
returning id, owner_id, name, author, definition, created_at
`

type CreateWorkoutParams struct {
	OwnerID    pgtype.UUID
	Name       string
	Author     string
	Definition []byte
}

func (q *Queries) CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (Workout, error) {
	row := q.db.QueryRow(ctx, createWorkout,
		arg.OwnerID,
		arg.Name,
		arg.Author,
		arg.Definition,
	)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Author,
		&i.Definition,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWorkout = `-- name: DeleteWorkout :execrows
delete from workouts where id = $1 and owner_id = $2
`

type DeleteWorkoutParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) DeleteWorkout(ctx context.Context, arg DeleteWorkoutParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkout, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listUserWorkouts = `-- name: ListUserWorkouts :many
select id, owner_id, name, author, definition, created_at from workouts
where owner_id = $1
  and ($3::timestamptz is null or created_at < $3::timestamptz)
order by created_at desc
limit $2
`

type ListUserWorkoutsParams struct {
	OwnerID pgtype.UUID
	Limit   int32
	Before  pgtype.Timestamptz
}

// Paged by save time (#1414), the cursor shape ListUserRides uses: `before`
// is the oldest row the caller holds, null for the first page. The read used
// to stop at a flat `limit 1000` (#1416), which is the failure this issue is
// actually about — workout 1001 was gone with nothing said. A ceiling is not
// what keeps a read small; paging is.
func (q *Queries) ListUserWorkouts(ctx context.Context, arg ListUserWorkoutsParams) ([]Workout, error) {
	rows, err := q.db.Query(ctx, listUserWorkouts, arg.OwnerID, arg.Limit, arg.Before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workout
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Author,
			&i.Definition,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkout = `-- name: UpdateWorkout :one
update workouts set name = $3, author = $4, definition = $5
where id = $1 and owner_id = $2 returning id, owner_id, name, author, definition, created_at
`

type UpdateWorkoutParams struct {
	ID         pgtype.UUID
	OwnerID    pgtype.UUID
	Name       string
	Author     string
	Definition []byte
}

func (q *Queries) UpdateWorkout(ctx context.Context, arg UpdateWorkoutParams) (Workout, error) {
	row := q.db.QueryRow(ctx, updateWorkout,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Author,
		arg.Definition,
	)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Author,
		&i.Definition,
		&i.CreatedAt,
	)
	return i, err
}
