// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: world.sql

package db

import (
	"context"
)

const getWorldKey = `-- name: GetWorldKey :one
select key from world_key
`

// The one world key (#3225): what every world's secrets are derived from.
func (q *Queries) GetWorldKey(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, getWorldKey)
	var key []byte
	err := row.Scan(&key)
	return key, err
}
