package wardrobe

// The catalogue, v3 (schema wattroom.wardrobe/3): every item's id, slot, price tier
// and unlock rule, and nothing else — the names and the looks live in
// web/src/lib/wardrobe/catalogue.json, which TestTheCatalogueIsInStepWithTheClient
// holds this table to. Pure data.

// Schema is the catalogue's version, the client's `schema`.
const Schema = "wattroom.wardrobe/3"

// tierPrices is docs/SPEC.md "Wardrobe"'s price tiers, in Batzen.
var tierPrices = map[string]int32{
	"S":   60,
	"M":   150,
	"L":   400,
	"XL":  1200,
	"XXL": 2400,
}

// slots are the 39 places an item goes, in the catalogue's order.
var slots = []string{
	"frame",
	"finish",
	"fork",
	"wheels",
	"hub",
	"tyres",
	"groupset",
	"gsFinish",
	"crank",
	"ring",
	"pedals",
	"saddle",
	"bars",
	"tape",
	"bottles",
	"cages",
	"computer",
	"lights",
	"bell",
	"bags",
	"utility",
	"charm",
	"jersey",
	"cut",
	"layer",
	"shorts",
	"warmers",
	"socks",
	"shoes",
	"overshoes",
	"gloves",
	"helmet",
	"helmetDeco",
	"glasses",
	"lens",
	"cap",
	"plate",
	"armband",
	"hair",
}

var items = []Item{
	{ID: "frame.race", Slot: "frame", Starter: true},
	{ID: "frame.aero", Slot: "frame", Tier: "XL"},
	{ID: "frame.climb", Slot: "frame", Tier: "XL"},
	{ID: "frame.endurance", Slot: "frame", Tier: "XL"},
	{ID: "frame.gravel", Slot: "frame", Tier: "XL"},
	{ID: "frame.cross", Slot: "frame", Tier: "XL"},
	{ID: "frame.tt", Slot: "frame", Tier: "XL"},
	{ID: "frame.hour", Slot: "frame", Tier: "XXL"},
	{ID: "frame.steel", Slot: "frame", Tier: "XL"},
	{ID: "frame.zweihundert", Slot: "frame", Unlock: "earned:achievement:200-rides"},
	{ID: "frame.alu90", Slot: "frame", Tier: "XL"},
	{ID: "frame.carbon03", Slot: "frame", Tier: "XL"},
	{ID: "frame.rando", Slot: "frame", Tier: "XL"},
	{ID: "frame.track", Slot: "frame", Tier: "L"},
	{ID: "frame.ordonnanz", Slot: "frame", Tier: "XXL"},
	{ID: "fork.straight", Slot: "fork", Free: true},
	{ID: "fork.curved", Slot: "fork", Free: true},
	{ID: "fork.aero", Slot: "fork", Free: true},
	{ID: "finish.matte", Slot: "finish", Starter: true},
	{ID: "finish.gloss", Slot: "finish", Free: true},
	{ID: "finish.satin", Slot: "finish", Free: true},
	{ID: "finish.metallic", Slot: "finish", Tier: "S"},
	{ID: "finish.raw", Slot: "finish", Tier: "S"},
	{ID: "finish.fade", Slot: "finish", Tier: "S"},
	{ID: "finish.chrome", Slot: "finish", Tier: "M"},
	{ID: "finish.teamlack", Slot: "finish", Tier: "M"},
	{ID: "finish.jahresring", Slot: "finish", Unlock: "earned:streak:10-weeks"},
	{ID: "wheels.alloy", Slot: "wheels", Starter: true},
	{ID: "wheels.carbon", Slot: "wheels", Tier: "L"},
	{ID: "wheels.box", Slot: "wheels", Tier: "M"},
	{ID: "wheels.gravel", Slot: "wheels", Tier: "S"},
	{ID: "wheels.disc", Slot: "wheels", Tier: "L"},
	{ID: "wheels.blade3", Slot: "wheels", Tier: "L"},
	{ID: "wheels.blade5", Slot: "wheels", Tier: "L"},
	{ID: "wheels.army", Slot: "wheels", Unlock: "with:frame.ordonnanz"},
	{ID: "wheels.vinyl", Slot: "wheels", Unlock: "earned:achievement:dj"},
	{ID: "hub.quiet", Slot: "hub", Starter: true},
	{ID: "hub.buzz", Slot: "hub", Tier: "S"},
	{ID: "hub.bee", Slot: "hub", Tier: "S"},
	{ID: "hub.klick", Slot: "hub", Tier: "S"},
	{ID: "tyre.black", Slot: "tyres", Starter: true},
	{ID: "tyre.tan", Slot: "tyres", Tier: "S"},
	{ID: "tyre.cream", Slot: "tyres", Tier: "S"},
	{ID: "tyre.colourwall", Slot: "tyres", Tier: "S"},
	{ID: "tyre.file", Slot: "tyres", Tier: "S"},
	{ID: "tyre.knob", Slot: "tyres", Tier: "S"},
	{ID: "tyre.tubular", Slot: "tyres", Tier: "M"},
	{ID: "gs.mech", Slot: "groupset", Starter: true},
	{ID: "gs.elec", Slot: "groupset", Tier: "M"},
	{ID: "gs.downtube", Slot: "groupset", Tier: "S"},
	{ID: "gs.delta", Slot: "groupset", Tier: "S"},
	{ID: "gsf.black", Slot: "gsFinish", Starter: true},
	{ID: "gsf.silver", Slot: "gsFinish", Tier: "M"},
	{ID: "gsf.copper", Slot: "gsFinish", Tier: "M"},
	{ID: "gsf.anodised", Slot: "gsFinish", Tier: "S"},
	{ID: "crank.four", Slot: "crank", Starter: true},
	{ID: "crank.hohl", Slot: "crank", Tier: "S"},
	{ID: "crank.five", Slot: "crank", Tier: "S"},
	{ID: "ring.round", Slot: "ring", Starter: true},
	{ID: "ring.oval83", Slot: "ring", Tier: "S"},
	{ID: "ring.oval", Slot: "ring", Tier: "S"},
	{ID: "ring.aero", Slot: "ring", Tier: "S"},
	{ID: "ring.army", Slot: "ring", Unlock: "with:frame.ordonnanz"},
	{ID: "pedal.road", Slot: "pedals", Starter: true},
	{ID: "pedal.node", Slot: "pedals", Tier: "S"},
	{ID: "pedal.2bolt", Slot: "pedals", Tier: "S"},
	{ID: "pedal.flat", Slot: "pedals", Tier: "S"},
	{ID: "pedal.clips", Slot: "pedals", Tier: "S"},
	{ID: "saddle.race", Slot: "saddle", Starter: true},
	{ID: "saddle.short", Slot: "saddle", Tier: "S"},
	{ID: "saddle.cutout", Slot: "saddle", Tier: "S"},
	{ID: "saddle.lattice", Slot: "saddle", Tier: "M"},
	{ID: "saddle.leather", Slot: "saddle", Tier: "M"},
	{ID: "saddle.suede", Slot: "saddle", Tier: "S"},
	{ID: "bars.drop", Slot: "bars", Starter: true},
	{ID: "bars.aero", Slot: "bars", Tier: "M"},
	{ID: "bars.flare", Slot: "bars", Tier: "M"},
	{ID: "bars.track", Slot: "bars", Tier: "S"},
	{ID: "bars.bullhorn", Slot: "bars", Tier: "S"},
	{ID: "bars.clipon", Slot: "bars", Tier: "S"},
	{ID: "bars.tt", Slot: "bars", Unlock: "with:frame.tt|frame.hour"},
	{ID: "bars.upright", Slot: "bars", Unlock: "with:frame.ordonnanz"},
	{ID: "tape.plain", Slot: "tape", Starter: true},
	{ID: "tape.collection", Slot: "tape", Tier: "S"},
	{ID: "bottle.plastic", Slot: "bottles", Starter: true},
	{ID: "bottle.alu", Slot: "bottles", Tier: "S"},
	{ID: "bottle.insulated", Slot: "bottles", Tier: "S"},
	{ID: "bottle.rear", Slot: "bottles", Tier: "S"},
	{ID: "bottle.espresso", Slot: "bottles", Unlock: "earned:achievement:espresso-ride"},
	{ID: "bottle.gruppetto", Slot: "bottles", Unlock: "earned:together:10-group-sessions"},
	{ID: "cage.alloy", Slot: "cages", Starter: true},
	{ID: "cage.collection", Slot: "cages", Tier: "S"},
	{ID: "comp.none", Slot: "computer", Starter: true},
	{ID: "comp.tacho", Slot: "computer", Tier: "S"},
	{ID: "comp.cyclo85", Slot: "computer", Tier: "S"},
	{ID: "light.none", Slot: "lights", Starter: true},
	{ID: "light.clip", Slot: "lights", Tier: "S"},
	{ID: "light.dynamo", Slot: "lights", Tier: "S"},
	{ID: "bell.none", Slot: "bell", Starter: true},
	{ID: "bell.collection", Slot: "bell", Tier: "S"},
	{ID: "bag.none", Slot: "bags", Starter: true},
	{ID: "bag.wedge", Slot: "bags", Tier: "S"},
	{ID: "bag.toptube", Slot: "bags", Tier: "S"},
	{ID: "bag.halfframe", Slot: "bags", Tier: "M"},
	{ID: "bag.fullframe", Slot: "bags", Tier: "M"},
	{ID: "bag.barroll", Slot: "bags", Tier: "M"},
	{ID: "bag.rando", Slot: "bags", Tier: "M"},
	{ID: "bag.musette", Slot: "bags", Unlock: "earned:badge:soigneur"},
	{ID: "util.none", Slot: "utility", Starter: true},
	{ID: "util.pendler", Slot: "utility", Tier: "S"},
	{ID: "charm.none", Slot: "charm", Starter: true},
	{ID: "charm.cowbell", Slot: "charm", Unlock: "earned:season:chalandamarz"},
	{ID: "charm.lampion", Slot: "charm", Unlock: "earned:season:1-august"},
	{ID: "charm.lantern", Slot: "charm", Unlock: "earned:medal:lanterne-rouge"},
	{ID: "charm.hammer", Slot: "charm", Unlock: "earned:medal:hammer"},
	{ID: "jp.plain", Slot: "jersey", Starter: true},
	{ID: "jp.yoke", Slot: "jersey", Tier: "S"},
	{ID: "jp.sidepanel", Slot: "jersey", Tier: "S"},
	{ID: "jp.hoops", Slot: "jersey", Tier: "M"},
	{ID: "jp.sash", Slot: "jersey", Tier: "M"},
	{ID: "jp.stripes", Slot: "jersey", Tier: "M"},
	{ID: "jp.chevron", Slot: "jersey", Tier: "M"},
	{ID: "jp.fade", Slot: "jersey", Tier: "M"},
	{ID: "jp.blocks", Slot: "jersey", Tier: "M"},
	{ID: "jp.karo", Slot: "jersey", Tier: "M"},
	{ID: "jp.topo", Slot: "jersey", Tier: "M"},
	{ID: "jp.edelweiss", Slot: "jersey", Tier: "M"},
	{ID: "jp.jass", Slot: "jersey", Tier: "M"},
	{ID: "jp.stickerei", Slot: "jersey", Tier: "L"},
	{ID: "jp.scherenschnitt", Slot: "jersey", Tier: "L"},
	{ID: "jp.chrampfer", Slot: "jersey", Unlock: "earned:achievement:sufferfest-survivor"},
	{ID: "jp.sprinter", Slot: "jersey", Unlock: "earned:achievement:sprint-snob"},
	{ID: "jp.gipfelpunkte", Slot: "jersey", Unlock: "earned:badge:hors-categorie"},
	{ID: "jp.nebelkit", Slot: "jersey", Unlock: "earned:badge:nebelmeer"},
	{ID: "jp.raeppli", Slot: "jersey", Unlock: "earned:season:fasnacht"},
	{ID: "jp.crew", Slot: "jersey", CrewOnly: true},
	{ID: "cut.race", Slot: "cut", Starter: true},
	{ID: "cut.club", Slot: "cut", Tier: "S"},
	{ID: "cut.wool", Slot: "cut", Tier: "M"},
	{ID: "cut.skinsuit", Slot: "cut", Tier: "M"},
	{ID: "layer.none", Slot: "layer", Starter: true},
	{ID: "layer.gilet", Slot: "layer", Tier: "M"},
	{ID: "layer.rain", Slot: "layer", Tier: "M"},
	{ID: "layer.winter", Slot: "layer", Tier: "M"},
	{ID: "layer.solstice", Slot: "layer", Unlock: "earned:season:winter-solstice"},
	{ID: "bib.plain", Slot: "shorts", Starter: true},
	{ID: "bib.panels", Slot: "shorts", Tier: "S"},
	{ID: "bib.wool", Slot: "shorts", Tier: "S"},
	{ID: "warm.none", Slot: "warmers", Starter: true},
	{ID: "warm.collection", Slot: "warmers", Tier: "S"},
	{ID: "warm.nightbands", Slot: "warmers", Unlock: "earned:achievement:night-shift"},
	{ID: "sock.plain", Slot: "socks", Starter: true},
	{ID: "sock.stripe", Slot: "socks", Tier: "S"},
	{ID: "sock.nordic", Slot: "socks", Tier: "S"},
	{ID: "sock.jass", Slot: "socks", Tier: "S"},
	{ID: "sock.edelweiss", Slot: "socks", Tier: "S"},
	{ID: "sock.karo", Slot: "socks", Tier: "S"},
	{ID: "sock.z6", Slot: "socks", Unlock: "earned:achievement:hot-end"},
	{ID: "sock.metronome", Slot: "socks", Unlock: "earned:medal:metronome"},
	{ID: "sock.spring", Slot: "socks", Unlock: "earned:season:sechselaeuten"},
	{ID: "sock.souvenir", Slot: "socks", Unlock: "earned:souvenir:climb"},
	{ID: "shoe.dial", Slot: "shoes", Starter: true},
	{ID: "shoe.strap", Slot: "shoes", Tier: "S"},
	{ID: "shoe.buckle", Slot: "shoes", Tier: "S"},
	{ID: "shoe.lace", Slot: "shoes", Tier: "M"},
	{ID: "shoe.vintage", Slot: "shoes", Tier: "M"},
	{ID: "over.none", Slot: "overshoes", Starter: true},
	{ID: "over.collection", Slot: "overshoes", Tier: "S"},
	{ID: "glove.mitt", Slot: "gloves", Starter: true},
	{ID: "glove.none", Slot: "gloves", Free: true},
	{ID: "glove.full", Slot: "gloves", Tier: "S"},
	{ID: "glove.lobster", Slot: "gloves", Tier: "S"},
	{ID: "helmet.road", Slot: "helmet", Starter: true},
	{ID: "helmet.aero", Slot: "helmet", Tier: "L"},
	{ID: "helmet.tt", Slot: "helmet", Tier: "L"},
	{ID: "helmet.hardshell", Slot: "helmet", Tier: "M"},
	{ID: "helmet.hairnet", Slot: "helmet", Tier: "L"},
	{ID: "deco.none", Slot: "helmetDeco", Starter: true},
	{ID: "deco.hc", Slot: "helmetDeco", Unlock: "earned:badge:hors-categorie"},
	{ID: "deco.flowers", Slot: "helmetDeco", Unlock: "earned:season:alpabzug"},
	{ID: "glasses.wrap", Slot: "glasses", Starter: true},
	{ID: "glasses.none", Slot: "glasses", Free: true},
	{ID: "glasses.shield", Slot: "glasses", Tier: "S"},
	{ID: "glasses.round", Slot: "glasses", Tier: "S"},
	{ID: "glasses.halfrim", Slot: "glasses", Tier: "S"},
	{ID: "glasses.gletscher", Slot: "glasses", Tier: "M"},
	{ID: "lens.cat", Slot: "lens", Starter: true},
	{ID: "lens.mirror", Slot: "lens", Tier: "S"},
	{ID: "lens.morgenrot", Slot: "lens", Unlock: "earned:achievement:sunrise-club"},
	{ID: "cap.none", Slot: "cap", Starter: true},
	{ID: "cap.cotton", Slot: "cap", Tier: "S"},
	{ID: "cap.winter", Slot: "cap", Tier: "S"},
	{ID: "cap.headband", Slot: "cap", Tier: "S"},
	{ID: "cap.stammtisch", Slot: "cap", Unlock: "earned:achievement:lounge-lizard"},
	{ID: "cap.diesel", Slot: "cap", Unlock: "earned:medal:diesel"},
	{ID: "cap.chapeau", Slot: "cap", Unlock: "earned:badge:chapeau"},
	{ID: "cap.chlaus", Slot: "cap", Unlock: "earned:season:samichlaus"},
	{ID: "cap.longestday", Slot: "cap", Unlock: "earned:season:summer-solstice"},
	{ID: "cap.souvenir", Slot: "cap", Unlock: "earned:souvenir:climb"},
	{ID: "plate.none", Slot: "plate", Starter: true},
	{ID: "plate.back", Slot: "plate", Unlock: "earned:race:finish:1"},
	{ID: "plate.frame", Slot: "plate", Unlock: "earned:race:finish:10"},
	{ID: "armband.none", Slot: "armband", Starter: true},
	{ID: "armband.captain", Slot: "armband", Unlock: "earned:achievement:crew-chief"},
	{ID: "hair.short", Slot: "hair", Starter: true},
	{ID: "hair.ponytail", Slot: "hair", Free: true},
	{ID: "hair.bun", Slot: "hair", Free: true},
	{ID: "hair.braid", Slot: "hair", Free: true},
	{ID: "hair.curls", Slot: "hair", Free: true},
	{ID: "hair.none", Slot: "hair", Free: true},
}
